"""Coding bootcamp admissions: Foundry Code School (fictional), four cohorts a year."""
from ._common import conv, msg, v, UNKNOWN

SPEC = {
    "business": {
        "name": "Foundry Code School",
        "type": "bootcamp_admissions",
        "summary": "Coding bootcamp with four cohorts a year, full time and part time. Applicants arrive from the web form, Instagram, email, texts and event sign-ups.",
        "audience": "applicants",
    },
    "connectors": [
        {"key": "web_form", "kind": "web_form", "label": "Apply form", "auto_connect": True},
        {"key": "instagram", "kind": "instagram", "label": "Instagram DMs", "auto_connect": True},
        {"key": "email", "kind": "email", "label": "admissions@foundrycode.example.com", "auto_connect": True},
        {"key": "sms", "kind": "sms", "label": "Admissions text line", "auto_connect": True},
        {"key": "csv", "kind": "csv", "label": "Event sign-ups", "auto_connect": False},
        {"key": "voicemail", "kind": "voicemail", "label": "Admissions voicemail", "auto_connect": False},
    ],
    "fields": [
        {"key": "cohort", "label": "Cohort", "type": "enum",
         "options": ["oct_2026", "jan_2027", "apr_2027", "undecided"],
         "hint": "Which start they mention: October 2026, January 2027, April 2027, or undecided",
         "show_in_list": True},
        {"key": "track", "label": "Track", "type": "enum",
         "options": ["full_time", "part_time"],
         "hint": "Full time is weekdays; part time is evenings and weekends", "show_in_list": True},
        {"key": "financing_question", "label": "Financing question", "type": "bool",
         "hint": "Any question about tuition, cost, payment plans, loans, scholarships or income share"},
        {"key": "prior_coding", "label": "Prior coding", "type": "enum",
         "options": ["none", "some", "professional"],
         "hint": "None, some (tutorials, a class, side projects) or professional (paid work as a developer)"},
        {"key": "country", "label": "Country", "type": "text",
         "hint": "Country they live in if mentioned; write US or Canada for those two"},
        {"key": "application_status", "label": "Application status", "type": "enum",
         "options": ["not_started", "started", "submitted"],
         "hint": "Not started, started but not finished, or submitted", "show_in_list": True},
        {"key": "urgency", "label": "Urgency", "type": "enum",
         "options": ["low", "normal", "high"],
         "hint": "High when the cohort starts soon or they ask for a fast answer"},
    ],
    "stages": [
        {"key": "new", "label": "New", "tone": "brand"},
        {"key": "info_session", "label": "Info session", "tone": "info"},
        {"key": "applied", "label": "Applied", "tone": "warn"},
        {"key": "enrolled", "label": "Enrolled", "tone": "ok", "terminal": True},
        {"key": "not_a_fit", "label": "Not a fit", "tone": "neutral", "terminal": True},
    ],
    "views": [
        {"key": "inbox", "name": "All open",
         "filter": {"all": [{"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "needs_reply", "name": "Needs reply",
         "filter": {"all": [{"field": "awaiting_reply", "op": "eq", "value": True}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "hot", "name": "Hot",
         "filter": {"all": [{"field": "f.application_status", "op": "eq", "value": "started"},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "financing", "name": "Financing questions",
         "filter": {"all": [{"field": "f.financing_question", "op": "eq", "value": True},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "oct_2026", "name": "October cohort",
         "filter": {"all": [{"field": "f.cohort", "op": "eq", "value": "oct_2026"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}},
        {"key": "unassigned", "name": "Unassigned",
         "filter": {"all": [{"field": "assignee", "op": "is_empty"},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}},
    ],
    "rules": [
        {"key": "nudge_started", "name": "Started but not finished",
         "text": "Flag anyone who started the application and stopped",
         "when": {"all": [{"field": "f.application_status", "op": "eq", "value": "started"}]},
         "then": {"type": "flag", "label": "Nudge to finish", "tone": "warn"}},
        {"key": "flag_financing", "name": "Financing question",
         "text": "Flag anyone asking about tuition or financing",
         "when": {"all": [{"field": "f.financing_question", "op": "eq", "value": True}]},
         "then": {"type": "flag", "label": "Financing", "tone": "info"}},
        {"key": "october_first", "name": "October applicants go to the top",
         "text": "Mark new October cohort inquiries high priority",
         "when": {"all": [{"field": "f.cohort", "op": "eq", "value": "oct_2026"},
                          {"field": "stage", "op": "eq", "value": "new"}]},
         "then": {"type": "set_priority", "value": "high"}},
        {"key": "reject_outside", "name": "Outside the US and Canada",
         "text": "Auto reject anyone outside the US and Canada",
         "when": {"all": [{"field": "f.country", "op": "not_empty"},
                          {"field": "f.country", "op": "not_in", "value": ["US", "Canada"]}]},
         "then": {"type": "auto_reject", "stage": "not_a_fit"}},
    ],
    "approval_policy": {"routine": "auto_send", "pricing": "review",
                        "medical_legal": "review", "distress": "review"},
    "tone": {"voice": "upbeat", "length": "short", "signoff": "Theo at Foundry Code School",
             "presets": [
                 {"label": "Answer their question", "instruction": "Answer the question they just asked"},
                 {"label": "Invite to info session", "instruction": "Invite them to the next Tuesday 6pm Central info session and offer the link"},
                 {"label": "Nudge to finish", "instruction": "Encourage them to finish their saved application and offer help with the part they stopped at"},
                 {"label": "Offer advisor call", "instruction": "Offer a call with an advisor and ask which times work"}]},
    "agent": {"name": "Theo", "persona": "Admissions coordinator",
              "intro": "I read every new applicant, pull out cohort, track and where they are in the application, and draft the first reply for you to approve."},
    "playbook": "- Four cohorts a year; next starts are October 2026, January 2027 and April 2027.\n- Tuition and financing are explained on a call with an advisor, never quoted in chat.\n- Info sessions are every Tuesday at 6pm Central, online.\n- Part time meets evenings and weekends and covers the same curriculum as full time over a longer schedule.\n- No coding background is required to apply.\n- After submitting, applicants get a scheduling link for a technical conversation within two business days.\n- Never promise a job, an outcome or a salary after the program.",
    "guardrails": [
        {"key": "no_screening", "text": "Never collect or sort by age, disability, credit, national origin, citizenship or religion.",
         "enforce": "refuse_field",
         "patterns": ["age", "date of birth", "how old", "disability", "credit score",
                      "national origin", "citizenship", "religion"],
         "reason": "age, disability, credit and similar characteristics admissions should not screen on",
         "refusal": "I cannot add that. Admissions should not screen on age, disability, credit or similar characteristics. I can add fields that apply to every applicant the same way, like cohort, track, prior coding or application status."},
        {"key": "no_job_promise", "text": "Never guarantee a job, an outcome or a salary after the program.",
         "enforce": "never_promise"},
    ],
}

QUESTIONS = [
    {"id": "sources", "kind": "tiles", "multi": True,
     "prompt": "Where do applicants reach you?",
     "why": "Each one becomes a connector and a way to filter.",
     "options": ["web_form", "instagram", "email", "sms", "csv", "voicemail"],
     "default": ["web_form", "instagram", "email", "sms"], "patch": "set_connectors"},
    {"id": "business_name", "kind": "text", "prompt": "What is the school called?",
     "why": "It goes on every reply.", "default": "Foundry Code School", "patch": "set_business_name"},
    {"id": "extract_fields", "kind": "chips", "multi": True,
     "prompt": "What should I pull out of every new inquiry?",
     "why": "Each one becomes a column you can sort and filter by.",
     "options": [["cohort", "Which cohort"], ["track", "Full or part time"],
                 ["financing_question", "Asked about financing"], ["prior_coding", "Prior coding"],
                 ["country", "Country"], ["application_status", "Application status"],
                 ["urgency", "Urgency"]],
     "default": ["cohort", "track", "financing_question", "prior_coding", "country",
                 "application_status"], "patch": "pick_fields"},
    {"id": "slices", "kind": "chips", "multi": True,
     "prompt": "Which views do you want on the front of the inbox?",
     "why": "Views are saved filters. You can add more later by typing.",
     "options": [["hot", "Started, not finished"], ["financing", "Financing questions"],
                 ["oct_2026", "October cohort"], ["unassigned", "Unassigned"]],
     "default": ["hot", "financing"], "patch": "pick_views"},
    {"id": "approval", "kind": "chips", "multi": False,
     "prompt": "What may I send without you looking first?",
     "why": "Anything about tuition, financing or job outcomes always waits for you.",
     "options": [["routine", "Info session invites and scheduling"], ["none", "Nothing, I review every reply"]],
     "default": "routine", "patch": "set_approval"},
    {"id": "tone", "kind": "chips", "multi": False, "prompt": "How should replies sound?",
     "why": "Sets the voice for every draft.",
     "options": [["upbeat", "Upbeat"], ["warm", "Warm"], ["plain", "Plain"]],
     "default": "upbeat", "patch": "set_tone"},
]

LADDERS = {
    "reply": [
        (("guarantee", "job placement", "get hired", "salary", "placement rate", "promise a job"),
         "Thanks for asking, and I want to be straight with you: we do not guarantee a job, and I would be wary of any program that does. What we do is career support during the program and after it, including portfolio reviews, mock interviews and introductions to hiring partners. Want to hear how that works at Tuesday's info session at 6pm Central?"),
        (("tuition", "cost", "how much", "payment plan", "financing", "scholarship", "loan", "income share"),
         "Great question. Tuition and financing are something an advisor walks through on a short call so you get the whole picture rather than a number in a chat. What day and time work for you?"),
        (("info session", "open house", "visit", "tour", "sit in"),
         "Yes! Info sessions are every Tuesday at 6pm Central, online, and you can ask an instructor anything. Want me to add you to this Tuesday's list?"),
        (("never coded", "no experience", "beginner", "zero experience", "from scratch", "complete newbie"),
         "You do not need any coding background to apply, and most of our students start from zero. The best first step is an info session, every Tuesday at 6pm Central. Want the link?"),
        (("started the application", "stuck", "finish my application", "where i left off", "saved my application"),
         "No problem, your application is saved right where you left it, and you can pick it up any time. If something on the form is unclear, tell me which part and I will sort it out."),
        (("part time", "part-time", "work full time", "evenings", "weekends", "keep my job"),
         "The part-time track is built for people who work during the day: it meets evenings and weekends and covers the same curriculum as full time over a longer schedule. Want to see the schedule at Tuesday's info session at 6pm Central?"),
    ],
    "fallback": "Thanks for reaching out to Foundry Code School, {who}! Happy to help you figure out which cohort and track fit. The best first step is an info session, every Tuesday at 6pm Central. Want me to send you the link?",
    "check_in": "Hi {who}, checking in to see whether you are still thinking about Foundry. Your application is saved where you left it, and I am happy to answer anything.",
    "booking": "Hi {who}, here is the link to book a call with an advisor. Pick any time that suits you, and reply here if none of them work.",
    "thanks": "Thanks, {who}! I will be in touch soon, and you can reply here with any questions.",
    "decline": "Thank you for your interest in Foundry, {who}. Right now we can only enroll applicants who live in the US or Canada, so we cannot take your application this time. If that changes, I will be glad to reach out.",
    "ask_missing": "Thanks {who}! To point you the right way, which cohort are you thinking about, full time or part time, and how much coding have you done so far?",
}

SAMPLE_INPUTS = [
    {"label": "Sample forwarded email", "source": "email",
     "text": "From: Nadia Haddad <nadia.haddad@example.com>\nSubject: January part-time, financing?\n\nName: Nadia Haddad\nMessage: Hi, I am a paralegal in Milwaukee looking at the January part-time cohort. I have done a couple of Python tutorials. Do you offer payment plans, and is there an info session coming up?"},
    {"label": "Sample voicemail transcript", "source": "voicemail",
     "text": "Voicemail transcript, 5:48 pm: Hi, this is Felix Abara, I started the application for October full time last night and the page timed out on the coding challenge. Can someone let me know if my answers were saved? My number is 773 555 0129."},
]

C = [
    conv("bc_01", "web_form", "Maya Lindqvist", "maya.lindqvist@example.com",
         "October full-time, started the application",
         [msg("inbound", 240, "Hi! I started the application for the full-time October cohort last week but stopped at the coding challenge. I have done some freeCodeCamp and a Python class. I'm in Minneapolis, so US. Is it too late to finish for October?")],
         priority="high",
         fields={"cohort": v("oct_2026", 0.95, "October cohort"),
                 "track": v("full_time", 0.9, "full-time"),
                 "financing_question": v(False, 0.7, ""),
                 "prior_coding": v("some", 0.85, "some freeCodeCamp and a Python class"),
                 "country": v("US", 0.9, "US"),
                 "application_status": v("started", 0.95, "started the application"),
                 "urgency": v("high", 0.7, "Is it too late to finish for October")},
         drafts={"reply": "Hi Maya, great to hear from you, and not too late at all. Your application is saved right where you left it, so you can pick up the coding challenge whenever you are ready. If you want a walkthrough before you finish, the next info session is Tuesday at 6pm Central. Anything I can answer in the meantime?"},
         tricky="started and stopped: the nudge flag fires"),
    conv("bc_02", "instagram", "Diego Castillo", "ig:diego.codes",
         "DM: do you guarantee a job after",
         [msg("inbound", 95, "hey do you guarantee a job after the program? thinking about jan part time, i work full time rn. never coded before")],
         fields={"cohort": v("jan_2027", 0.85, "jan"),
                 "track": v("part_time", 0.9, "part time"),
                 "financing_question": UNKNOWN,
                 "prior_coding": v("none", 0.95, "never coded before"),
                 "country": UNKNOWN,
                 "application_status": v("not_started", 0.6, "thinking about"),
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Diego, thanks for asking, and I want to be straight with you: we do not guarantee a job, and I would be wary of any program that does. What we do is career support during the program and after it, including portfolio reviews, mock interviews and introductions to hiring partners. The January part-time cohort is built for people working full time, and you do not need any coding background to apply. Want to join Tuesday's info session at 6pm Central to hear more?"},
         tricky="forbidden claim: draft is honest about career support with no guarantee, routed to review"),
    conv("bc_03", "email", "Ingrid Varga", "ingrid.varga@example.com",
         "Is 52 too old for this?",
         [msg("inbound", 900, "Hello, I am 52 and have spent my career in accounting. I have been teaching myself JavaScript for about a year and I am considering the part-time April cohort. Honestly, is my age going to be a problem? And does the part-time schedule work for someone who works 9 to 5?")],
         fields={"cohort": v("apr_2027", 0.9, "April cohort"),
                 "track": v("part_time", 0.9, "part-time"),
                 "financing_question": UNKNOWN,
                 "prior_coding": v("some", 0.85, "teaching myself JavaScript for about a year"),
                 "country": UNKNOWN,
                 "application_status": v("not_started", 0.6, "considering"),
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Ingrid, thank you for writing, and welcome. A year of self-taught JavaScript plus a career in accounting is a strong place to start, and our cohorts are full of people changing careers. The part-time track is built for people who work during the day, so a 9 to 5 fits. Would you like to join Tuesday's info session at 6pm Central to see the schedule and meet an instructor?"},
         tricky="age mentioned: not extracted, draft welcomes them and answers the schedule question"),
    conv("bc_04", "sms", "Kwame Osei", "+1 (773) 555-0162",
         "Text: payment plans?",
         [msg("inbound", 40, "Hi do you have payment plans or is it all up front? Looking at October full time")],
         priority="high",
         fields={"cohort": v("oct_2026", 0.9, "October"),
                 "track": v("full_time", 0.9, "full time"),
                 "financing_question": v(True, 0.95, "payment plans"),
                 "prior_coding": UNKNOWN,
                 "country": UNKNOWN,
                 "application_status": UNKNOWN,
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Kwame, great question. Tuition and financing are something our advisors walk through on a short call so you get the whole picture rather than a number in a text. What day and time work for you? October full time is a great pick, and I can add you to Tuesday's info session at 6pm Central too."},
         tricky="financing question: review before sending, flag fires"),
    conv("bc_05", "web_form", "Rohan Patel", "rohan.patel@example.com",
         "Applying from Bangalore, India",
         [msg("inbound", 700, "Hi, I am a software tester in Bangalore, India with about two years of professional coding in Java. I would like to join the October full-time cohort remotely. Do you accept international students?")],
         fields={"cohort": v("oct_2026", 0.95, "October full-time cohort"),
                 "track": v("full_time", 0.95, "full-time"),
                 "financing_question": UNKNOWN,
                 "prior_coding": v("professional", 0.9, "two years of professional coding"),
                 "country": v("India", 0.95, "India"),
                 "application_status": v("not_started", 0.6, "would like to join"),
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Rohan, thank you for your interest and for telling me about your background. Right now we can only enroll applicants who live in the US or Canada, so I cannot take your application this time. If that changes, I will be glad to reach out."},
         tricky="outside the US and Canada: the auto reject rule fires"),
    conv("bc_06", "instagram", "Amara Abara", "ig:amara.builds",
         "DM: info session this week?",
         [msg("inbound", 2900, "hi! is there an info session this week? I'm leaning toward the January cohort, still deciding full or part time. I've done a few Codecademy courses. I'm in Vancouver, Canada btw"),
          msg("outbound", 2800, "Hi Amara, yes! Info sessions are every Tuesday at 6pm Central, so the next one is Tuesday. I will add you to the list and send the link here. Codecademy is a solid start, and you can pick full or part time after you have seen both schedules.", author="Theo"),
          msg("note", 2780, "Added to Tuesday's session list. Leaning January.", author="Theo")],
         stage="info_session", assignee="Theo", unread=False,
         fields={"cohort": v("jan_2027", 0.9, "January cohort"),
                 "track": UNKNOWN,
                 "financing_question": UNKNOWN,
                 "prior_coding": v("some", 0.85, "a few Codecademy courses"),
                 "country": v("Canada", 0.95, "Canada"),
                 "application_status": v("not_started", 0.6, "still deciding"),
                 "urgency": v("normal", 0.6, "")}),
    conv("bc_07", "email", "Felix Moreau", "felix.moreau@example.com",
         "Submitted my application for October",
         [msg("inbound", 6000, "Hi Theo, I just submitted my application for the October full-time cohort. I have been building small Flask apps for a couple of years on the side. I am in Portland, Oregon. What happens next?"),
          msg("outbound", 5900, "Hi Felix, congratulations on submitting! Next up is a short technical conversation with an instructor, and you will get a scheduling link within two business days. Flask side projects are a great thing to bring up in that conversation.", author="Nina"),
          msg("note", 5880, "Interview slot sent for Friday.", author="Nina")],
         stage="applied", assignee="Nina", unread=False,
         fields={"cohort": v("oct_2026", 0.95, "October full-time cohort"),
                 "track": v("full_time", 0.95, "full-time"),
                 "financing_question": UNKNOWN,
                 "prior_coding": v("some", 0.8, "small Flask apps"),
                 "country": v("US", 0.9, "Portland, Oregon"),
                 "application_status": v("submitted", 0.97, "submitted my application"),
                 "urgency": v("normal", 0.6, "")}),
    conv("bc_08", "sms", "Grace Brennan", "+1 (630) 555-0187",
         "Text: enrolled, thank you",
         [msg("inbound", 20000, "Hi this is Grace, I did the info session last month and submitted for October full time. Anything else I need to do?"),
          msg("outbound", 19900, "Hi Grace, welcome back! Your application is in review and you will hear from us within two business days. Nothing else needed right now.", author="Theo"),
          msg("inbound", 4300, "Just got the acceptance email and paid the deposit!! So excited"),
          msg("outbound", 4200, "Congratulations Grace, we are thrilled to have you in the October cohort. Watch for the welcome packet next week.", author="Theo")],
         stage="enrolled", status="resolved", unread=False, assignee="Theo",
         fields={"cohort": v("oct_2026", 0.95, "October full time"),
                 "track": v("full_time", 0.9, "full time"),
                 "financing_question": UNKNOWN,
                 "prior_coding": UNKNOWN,
                 "country": UNKNOWN,
                 "application_status": v("submitted", 0.95, "submitted for October"),
                 "urgency": v("normal", 0.6, "")}),
    conv("bc_09", "web_form", "Noah Haddad", "noah.haddad@example.com",
         "Undecided between cohorts, zero experience",
         [msg("inbound", 1300, "Hi there. I have never written a line of code but I want to switch out of retail management. I am not sure whether October or January makes more sense, or full time versus part time. I am in Columbus, Ohio, US. Where do I even start?")],
         fields={"cohort": v("undecided", 0.9, "not sure whether October or January"),
                 "track": UNKNOWN,
                 "financing_question": UNKNOWN,
                 "prior_coding": v("none", 0.95, "never written a line of code"),
                 "country": v("US", 0.95, "US"),
                 "application_status": v("not_started", 0.9, "Where do I even start"),
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Noah, welcome, and you are in exactly the right place to start. Plenty of our students came from retail and management with no coding at all, so nothing about that is a problem. The best first step is Tuesday's info session at 6pm Central, where you will see both schedules and can ask an instructor anything. Want me to send you the link?"}),
    conv("bc_10", "instagram", "Sofia Rinaldi", "ig:sofia.r",
         "DM: scholarships?",
         [msg("inbound", 330, "do you have scholarships or income share agreements? i'm a single mom and can't do full time so part time jan 2027 probably. did a coding class in college")],
         fields={"cohort": v("jan_2027", 0.9, "jan 2027"),
                 "track": v("part_time", 0.9, "part time"),
                 "financing_question": v(True, 0.95, "scholarships or income share"),
                 "prior_coding": v("some", 0.8, "a coding class in college"),
                 "country": UNKNOWN,
                 "application_status": UNKNOWN,
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Sofia, thanks for reaching out, and the part-time January cohort is built for people with a full life outside class. Scholarships and financing options are something an advisor walks through on a short call so you get the whole picture. What day and time work for you? I can also add you to Tuesday's info session at 6pm Central."},
         tricky="financing question: review before sending"),
    conv("bc_11", "csv", "Leo Nakamura", "leo.nakamura@example.com",
         "Event sign-up: Riverfront Tech Fair",
         [msg("inbound", 5000, "Event sign-up (Riverfront Tech Fair, Aug 22). Name: Leo Nakamura. Interest: October cohort, part time. Note: works as a data analyst, some SQL and Python. Wants a call about tuition.")],
         priority="high",
         fields={"cohort": v("oct_2026", 0.9, "October cohort"),
                 "track": v("part_time", 0.9, "part time"),
                 "financing_question": v(True, 0.9, "Wants a call about tuition"),
                 "prior_coding": v("some", 0.8, "some SQL and Python"),
                 "country": UNKNOWN,
                 "application_status": v("not_started", 0.5, "Interest"),
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Leo, great to meet you at the Riverfront Tech Fair. You asked about tuition, and an advisor can walk you through tuition and financing on a short call. What day and time work for you? The October part-time cohort would be a natural fit with your SQL and Python background."}),
    conv("bc_12", "voicemail", "Victor Delgado", "+1 (312) 555-0148",
         "Voicemail: switch from January to October",
         [msg("inbound", 150, "Voicemail transcript, 7:40 pm: Hi, this is Victor Delgado, I applied for January part time but my situation changed and I could start October full time instead. Can someone call me back tomorrow? 312 555 0148.")],
         priority="high",
         fields={"cohort": v("oct_2026", 0.7, "could start October full time"),
                 "track": v("full_time", 0.7, "October full time"),
                 "financing_question": UNKNOWN,
                 "prior_coding": UNKNOWN,
                 "country": UNKNOWN,
                 "application_status": v("submitted", 0.8, "I applied for January"),
                 "urgency": v("high", 0.8, "call me back tomorrow")},
         drafts={"reply": "Hi Victor, thanks for the voicemail, and yes, we can look at moving your application from January part time to October full time. Someone on the admissions team will call you tomorrow to confirm. If you want, reply here with the best time to reach you."}),
    conv("bc_13", "email", "Harper Quinn", "harper.quinn@example.org",
         "Not going ahead this year",
         [msg("inbound", 12000, "Hi, I attended the info session on the 11th and was planning on October full time, but I have decided to stay at my job for now. Thanks for all the help."),
          msg("outbound", 11900, "Hi Harper, thank you for letting us know, and best of luck at work. You are welcome back any time, and the January and April cohorts will be there if the timing changes.", author="Nina"),
          msg("note", 11880, "Closing. Attended the Aug 11 session. Not a fit for now, keep on the newsletter.", author="Nina")],
         stage="not_a_fit", status="resolved", unread=False, assignee="Nina",
         fields={"cohort": v("oct_2026", 0.9, "October full time"),
                 "track": v("full_time", 0.9, "full time"),
                 "financing_question": UNKNOWN,
                 "prior_coding": UNKNOWN,
                 "country": UNKNOWN,
                 "application_status": v("not_started", 0.6, "was planning on"),
                 "urgency": v("low", 0.8, "stay at my job for now")}),
    conv("bc_14", "web_form", "Yusuf Sato", "yusuf.sato@example.com",
         "Toronto applicant, prior dev experience",
         [msg("inbound", 2100, "Hello, I worked as a front-end developer in Toronto, Canada for three years before a layoff and want to formalize my backend skills. Is the full-time April 2027 cohort open for applications yet? I have not started one.")],
         fields={"cohort": v("apr_2027", 0.95, "April 2027 cohort"),
                 "track": v("full_time", 0.95, "full-time"),
                 "financing_question": UNKNOWN,
                 "prior_coding": v("professional", 0.95, "worked as a front-end developer"),
                 "country": v("Canada", 0.95, "Canada"),
                 "application_status": v("not_started", 0.95, "have not started"),
                 "urgency": v("low", 0.7, "April 2027")},
         drafts={"reply": "Hi Yusuf, thanks for reaching out, and three years of front-end work is a strong base for going deeper on the backend. I will check the date applications open for the April 2027 full-time cohort and let you know here. In the meantime, Tuesday's info session at 6pm Central is a good way to meet an instructor and see the curriculum."}),
    conv("bc_15", "sms", "Wren Ivers", "+1 (847) 555-0175",
         "Text: stuck on the application, laptop question",
         [msg("inbound", 25, "Hey I started the application but got stuck on the part asking for a project link, I don't have one. Also do I need my own laptop? October part time, I'm in Chicago")],
         priority="high",
         fields={"cohort": v("oct_2026", 0.9, "October part time"),
                 "track": v("part_time", 0.9, "part time"),
                 "financing_question": UNKNOWN,
                 "prior_coding": v("none", 0.5, "I don't have one"),
                 "country": v("US", 0.7, "Chicago"),
                 "application_status": v("started", 0.95, "started the application"),
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Wren, thanks for reaching out, and lots of people apply without a project to link. I will get that question and the laptop question cleared up with the team today and text you back. Your application is saved where you left it, so you can pick it up as soon as you hear from me."},
         tricky="started and stopped: the nudge flag fires"),
    conv("bc_16", "email", "Claire Doyle", "claire.doyle@example.com",
         "Coming to the info session, a few questions first",
         [msg("inbound", 4500, "Hi! I signed up for Tuesday's info session. Before then: I am a nurse in Denver, US, thinking about part time for January because I cannot leave my job. I have done a little HTML. Does the part-time track cover the same material as full time?"),
          msg("outbound", 4400, "Hi Claire, glad you are coming Tuesday! Yes, part time covers the same curriculum as full time, spread over a longer schedule, and it is built for people who work during the day. Bring your questions and an instructor will walk through it.", author="Theo"),
          msg("note", 4380, "On Tuesday's list. Part time, January.", author="Theo")],
         stage="info_session", assignee="Theo", unread=False,
         fields={"cohort": v("jan_2027", 0.9, "January"),
                 "track": v("part_time", 0.9, "part time"),
                 "financing_question": UNKNOWN,
                 "prior_coding": v("some", 0.8, "a little HTML"),
                 "country": v("US", 0.9, "US"),
                 "application_status": v("not_started", 0.6, "thinking about"),
                 "urgency": v("normal", 0.6, "")}),
    conv("bc_17", "web_form", "Omar Reyes", "omar.reyes@example.com",
         "Submitted for October, Austin",
         [msg("inbound", 30000, "Submitted for October full time. I'm in Austin, Texas and I've been coding professionally in PHP for a year, looking to move into a modern stack."),
          msg("outbound", 29900, "Hi Omar, congratulations on submitting! You will get a scheduling link for a short technical conversation with an instructor within two business days. A year of professional PHP is a great thing to talk about there.", author="Nina"),
          msg("inbound", 9000, "Accepted and deposit paid, see you in October!"),
          msg("outbound", 8900, "Welcome aboard, Omar! Watch for the welcome packet next week.", author="Nina")],
         stage="enrolled", status="resolved", unread=False, assignee="Nina",
         fields={"cohort": v("oct_2026", 0.95, "October full time"),
                 "track": v("full_time", 0.95, "full time"),
                 "financing_question": UNKNOWN,
                 "prior_coding": v("professional", 0.95, "coding professionally in PHP"),
                 "country": v("US", 0.9, "Austin, Texas"),
                 "application_status": v("submitted", 0.97, "Submitted for October"),
                 "urgency": v("normal", 0.6, "")}),
]

TEMPLATE = {
    "key": "bootcamp_admissions",
    "name": "Coding bootcamp admissions",
    "tagline": "Applicants from the web form, Instagram, email, texts and event sign-ups",
    "example_prompt": "Coding bootcamp. Applicants come from our web form, Instagram, email, texts and a CSV we import from events.",
    "signals": [("bootcamp", 5), ("code school", 4), ("cohort", 4), ("coding", 3),
                ("admissions", 3), ("info session", 3), ("applicant", 2), ("enroll", 2),
                ("tuition", 2), ("instagram", 1)],
    "must_review": ["pricing"],
    "spec": SPEC,
    "questions": QUESTIONS,
    "personas": ["Theo", "Nina"],
    "ladders": LADDERS,
    "sample_inputs": SAMPLE_INPUTS,
    "prompt_examples": ["add a field for whether they have their own laptop",
                        "add a view of part-time applicants for January",
                        "flag anyone who asks about a job guarantee"],
    "conversations": C,
}
