"""Clinical research site: Northwind Clinical Research (fictional), Naperville."""
from ._common import conv, msg, v, UNKNOWN

SPEC = {
    "business": {
        "name": "Northwind Clinical Research",
        "type": "clinical_trial_site",
        "summary": "Research site in Naperville running four studies: migraine prevention, type 2 diabetes, knee osteoarthritis and sleep apnea. Leads come from ClinicalTrials.gov, Facebook ads, the trial finder form and referring doctors.",
        "audience": "participants",
    },
    "connectors": [
        {"key": "web_form", "kind": "web_form", "label": "Trial finder form", "auto_connect": True},
        {"key": "email", "kind": "email", "label": "ClinicalTrials.gov and referral email", "auto_connect": True},
        {"key": "facebook_leads", "kind": "facebook_leads", "label": "Facebook Lead Ads", "auto_connect": True},
        {"key": "sms", "kind": "sms", "label": "Site text line", "auto_connect": True},
        {"key": "voicemail", "kind": "voicemail", "label": "After hours voicemail", "auto_connect": False},
        {"key": "referral", "kind": "referral", "label": "Physician referrals", "auto_connect": False},
    ],
    "fields": [
        {"key": "study_interest", "label": "Study", "type": "enum",
         "options": ["migraine_prevention", "type_2_diabetes", "knee_osteoarthritis", "sleep_apnea", "unsure"],
         "hint": "Which of the four studies they are asking about; unsure when they only describe symptoms",
         "show_in_list": True},
        {"key": "condition", "label": "Condition", "type": "text",
         "hint": "The condition in their own words", "show_in_list": True},
        {"key": "age", "label": "Age", "type": "number",
         "hint": "Age in years if stated"},
        {"key": "current_meds", "label": "Current medications", "type": "list",
         "hint": "Every medication they mention taking now, one per item"},
        {"key": "zip", "label": "ZIP code", "type": "text",
         "hint": "Five digit ZIP if mentioned"},
        {"key": "prior_study", "label": "Took part in a study before", "type": "bool",
         "hint": "Any mention of a previous or current research study"},
        {"key": "urgency", "label": "Urgency", "type": "enum",
         "options": ["low", "normal", "high"],
         "hint": "High when they describe a new or worsening symptom; normal for questions and interest",
         "show_in_list": True},
    ],
    "stages": [
        {"key": "new", "label": "New", "tone": "brand"},
        {"key": "prescreen", "label": "Pre-screen", "tone": "info"},
        {"key": "screening_visit", "label": "Screening visit", "tone": "warn"},
        {"key": "enrolled", "label": "Enrolled", "tone": "ok", "terminal": True},
        {"key": "not_a_fit", "label": "Not a fit", "tone": "neutral", "terminal": True},
    ],
    "views": [
        {"key": "inbox", "name": "All open",
         "filter": {"all": [{"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "needs_reply", "name": "Needs reply",
         "filter": {"all": [{"field": "awaiting_reply", "op": "eq", "value": True}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "likely_fits", "name": "Likely fits",
         "filter": {"all": [{"field": "f.prior_study", "op": "neq", "value": True},
                            {"field": "f.condition", "op": "not_empty"},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "on_insulin", "name": "On insulin",
         "filter": {"all": [{"field": "f.current_meds", "op": "contains", "value": "insulin"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "urgent", "name": "Urgent",
         "filter": {"any": [{"field": "priority", "op": "eq", "value": "urgent"},
                            {"field": "f.urgency", "op": "eq", "value": "high"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}},
        {"key": "referred", "name": "Referred by a doctor",
         "filter": {"all": [{"field": "source", "op": "eq", "value": "referral"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}},
    ],
    "rules": [
        {"key": "flag_insulin", "name": "Insulin exclusion check",
         "text": "Flag anyone on insulin so the coordinator checks the exclusion",
         "when": {"all": [{"field": "f.current_meds", "op": "contains", "value": "insulin"}]},
         "then": {"type": "flag", "label": "Check exclusion: insulin", "tone": "warn"}},
        {"key": "urgent_symptoms", "name": "New symptoms go to the top",
         "text": "Mark anyone describing a new or worsening symptom as urgent",
         "when": {"all": [{"field": "f.urgency", "op": "eq", "value": "high"}]},
         "then": {"type": "set_priority", "value": "urgent"}},
        {"key": "flag_repeat", "name": "Repeat participant",
         "text": "Flag anyone who has been in a study before",
         "when": {"all": [{"field": "f.prior_study", "op": "eq", "value": True}]},
         "then": {"type": "flag", "label": "Repeat participant", "tone": "info"}},
        {"key": "reject_minors", "name": "Adults only",
         "text": "Auto reject anyone under 18",
         "when": {"all": [{"field": "f.age", "op": "lt", "value": 18}]},
         "then": {"type": "auto_reject", "stage": "not_a_fit"}},
    ],
    "approval_policy": {"routine": "auto_send", "pricing": "review",
                        "medical_legal": "review", "distress": "review"},
    "tone": {"voice": "warm", "length": "short", "signoff": "Bridget at Northwind Clinical Research",
             "presets": [
                 {"label": "Answer their question", "instruction": "Answer the question they just asked"},
                 {"label": "Offer a pre-screen call", "instruction": "Offer a 15 minute pre-screen call with the coordinator and ask which times work"},
                 {"label": "Ask about their condition", "instruction": "Ask which condition they have, their age, and what medications they take"},
                 {"label": "Check in", "instruction": "Check in and ask whether they are still interested"}]},
    "agent": {"name": "Bridget", "persona": "Study coordinator's assistant",
              "intro": "I read every new inquiry, pull out the condition, age and medications, and draft the first reply for the coordinator to approve."},
    "playbook": "- Four studies are enrolling: migraine prevention, type 2 diabetes, knee osteoarthritis and sleep apnea.\n- Visits are at the site in Naperville. Parking is free.\n- Never state whether someone qualifies; the pre-screen call decides that.\n- Never state payment amounts in writing.",
    "guardrails": [
        {"key": "no_eligibility", "text": "Never state whether someone qualifies for a study or what they will be paid.",
         "enforce": "never_promise"},
        {"key": "symptoms_escalate", "text": "New or worsening symptoms go to the coordinator today.",
         "enforce": "escalate"},
    ],
}

QUESTIONS = [
    {"id": "sources", "kind": "tiles", "multi": True,
     "prompt": "Where do new participants come in?",
     "why": "Each one becomes a connector and a way to filter.",
     "options": ["web_form", "email", "facebook_leads", "sms", "voicemail", "referral"],
     "default": ["web_form", "email", "facebook_leads", "sms"], "patch": "set_connectors"},
    {"id": "business_name", "kind": "text", "prompt": "What is the site called?",
     "why": "It goes on every reply.", "default": "Northwind Clinical Research", "patch": "set_business_name"},
    {"id": "extract_fields", "kind": "chips", "multi": True,
     "prompt": "What should I pull out of every new inquiry?",
     "why": "Each one becomes a column you can sort and filter by.",
     "options": [["study_interest", "Which study"], ["condition", "Their condition"],
                 ["age", "Age"], ["current_meds", "Current medications"],
                 ["zip", "ZIP code"], ["prior_study", "Been in a study before"],
                 ["urgency", "Urgency"]],
     "default": ["study_interest", "condition", "age", "current_meds", "zip", "urgency"],
     "patch": "pick_fields"},
    {"id": "slices", "kind": "chips", "multi": True,
     "prompt": "Which views do you want on the front of the inbox?",
     "why": "Views are saved filters. You can add more later by typing.",
     "options": [["likely_fits", "Likely fits"], ["on_insulin", "On insulin"],
                 ["urgent", "Urgent"], ["referred", "Referred by a doctor"]],
     "default": ["likely_fits", "on_insulin"], "patch": "pick_views"},
    {"id": "approval", "kind": "chips", "multi": False,
     "prompt": "What may I send without you looking first?",
     "why": "Anything about eligibility, payment, or symptoms always waits for the coordinator.",
     "options": [["routine", "Acknowledgements and scheduling"], ["none", "Nothing, I review every reply"]],
     "default": "routine", "patch": "set_approval"},
    {"id": "tone", "kind": "chips", "multi": False, "prompt": "How should replies sound?",
     "why": "Sets the voice for every draft.",
     "options": [["warm", "Warm"], ["plain", "Plain"], ["formal", "Formal"]],
     "default": "warm", "patch": "set_tone"},
]

LADDERS = {
    "reply": [
        (("eligible", "qualify", "do i fit", "am i a candidate", "criteria", "can i be in"),
         "Thanks for reaching out. Whether a study is a fit is something the coordinator works out with you on a short pre-screen call, so I cannot answer that in writing. Visits are at our site in Naperville and parking is free. What days and times work for a call?"),
        (("how much", "paid", "do you pay", "compensation", "stipend", "cost", "reimburse"),
         "Good question. Anything about payment or costs is something the coordinator goes over on the pre-screen call rather than in writing. The call takes about 15 minutes. What days and times work for you?"),
        (("still enrolling", "still open", "still recruiting", "spots left", "still taking"),
         "Thanks for asking. The coordinator can tell you where the study stands and what taking part involves on a short pre-screen call. Visits are at our site in Naperville and parking is free. What days and times work for you?"),
        (("symptom", "getting worse", "chest", "dizzy", "fainted", "bleeding", "short of breath"),
         "Thank you for telling us right away. Please contact your doctor today, and call 911 if it gets worse or you feel unwell. The coordinator will call you today to talk it through."),
        (("my doctor suggested", "referred by", "neurologist", "endocrinologist", "my doctor said"),
         "Thanks for reaching out, and thanks to your doctor for pointing you our way. The next step is a short pre-screen call with our coordinator. Visits are at our site in Naperville and parking is free. What days and times work?"),
        (("parking", "where are you", "location", "address", "how far"),
         "Visits are at our site in Naperville and parking is free. The coordinator can go over the visit schedule with you on a short pre-screen call. What days and times work for you?"),
    ],
    "fallback": "Thanks for reaching out to Northwind Clinical Research, {who}. The first step is a short pre-screen call with our coordinator, who will go over what the study involves and ask a few questions about your health. Visits are at our site in Naperville and parking is free. What days and times work for you?",
    "check_in": "Hi {who}, checking in to see whether you would still like to set up a pre-screen call about the study. Reply here any time and I will find a time that works.",
    "booking": "Hi {who}, here is the link to book your pre-screen call. Pick any time that suits you, and reply here if none of them work.",
    "thanks": "Thank you, {who}. The coordinator will be in touch soon, and you can reply here with any questions.",
    "decline": "Thank you for reaching out, {who}. The studies we are running right now are not a match for what you described, but ClinicalTrials.gov lets you search by condition and location, and you are welcome to check back with us later.",
    "ask_missing": "Thanks {who}. To point you to the right study, could you tell me which condition you have, your age, and what medications you take?",
}

SAMPLE_INPUTS = [
    {"label": "Sample ClinicalTrials.gov email", "source": "email",
     "text": "From: ClinicalTrials.gov contact form <no-reply@example.org>\nSubject: Inquiry about your listing: Migraine Prevention Study\n\nName: Renee Castillo\nEmail: renee.castillo@example.com\nMessage: I get about 10 migraines a month and my neurologist suggested looking at studies. I am 36 and take topiramate. I live in Naperville. Is this study still enrolling and what would I need to do?"},
    {"label": "Sample voicemail transcript", "source": "voicemail",
     "text": "Voicemail transcript, 6:40 pm: Hi, this is Walter Osei, I saw your ad about the knee study. I am 64, my knees have been bad for years and I take ibuprofen most days. I have never done a study before. Please call me back at 630 555 0161."},
]

C = [
    conv("ct_01", "web_form", "Nadia Haddad", "nadia.haddad@example.com",
         "Migraine study: am I eligible and how much do you pay",
         [msg("inbound", 150, "Hi, I saw the migraine prevention study on your trial finder. I get 10 to 12 migraines a month and I am 34. I take sumatriptan when they hit. Am I eligible and how much do you pay for this? I am in 60540.")],
         fields={"study_interest": v("migraine_prevention", 0.97, "migraine prevention study"),
                 "condition": v("migraines", 0.95, "10 to 12 migraines a month"),
                 "age": v(34, 0.95, "I am 34"),
                 "current_meds": v(["sumatriptan"], 0.9, "sumatriptan"),
                 "zip": v("60540", 0.95, "60540"),
                 "prior_study": UNKNOWN,
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Nadia, thanks for reaching out about the migraine prevention study. Whether a study is a fit, and what taking part involves, is something the coordinator goes over with you on a short pre-screen call, so I cannot answer either in writing. Visits are at our site in Naperville and parking is free. What days and times work for a 15 minute call?"},
         tricky="asks eligibility and pay: the draft answers neither, pricing stays in review"),
    conv("ct_02", "facebook_leads", "Kwame Osei", "kwame.osei@example.com",
         "Facebook lead: type 2 diabetes study",
         [msg("inbound", 320, "Lead form: Type 2 diabetes study\nName: Kwame Osei\nAge: 52\nZip: 60563\nMessage: Diagnosed with type 2 diabetes about 6 years ago. On metformin and I started insulin last spring. Interested in the diabetes study, what does it involve?")],
         fields={"study_interest": v("type_2_diabetes", 0.97, "type 2 diabetes study"),
                 "condition": v("type 2 diabetes", 0.95, "diagnosed with type 2 diabetes"),
                 "age": v(52, 0.95, "Age: 52"),
                 "current_meds": v(["metformin", "insulin"], 0.9, "On metformin and I started insulin"),
                 "zip": v("60563", 0.95, "Zip: 60563"),
                 "prior_study": UNKNOWN,
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Kwame, thanks for your interest in the type 2 diabetes study. The coordinator walks through what the study involves and asks a few questions about your health and medications on a short pre-screen call. Visits are at our site in Naperville and parking is free. What days and times work for a call?"},
         tricky="on insulin: the exclusion flag fires"),
    conv("ct_03", "email", "Ingrid Lindqvist", "ingrid.l@example.com",
         "ClinicalTrials.gov inquiry: knee osteoarthritis study",
         [msg("inbound", 540, "Hello, I found your knee osteoarthritis study listing on ClinicalTrials.gov. I have had osteoarthritis in my right knee for about four years and I am 61. I take naproxen most days. I live in Wheaton, 60187. I was in a study at a university a few years ago for a cholesterol drug, so I know the routine. Is the study still enrolling?")],
         fields={"study_interest": v("knee_osteoarthritis", 0.97, "knee osteoarthritis study"),
                 "condition": v("osteoarthritis in my right knee", 0.95, "osteoarthritis in my right knee"),
                 "age": v(61, 0.95, "I am 61"),
                 "current_meds": v(["naproxen"], 0.9, "naproxen"),
                 "zip": v("60187", 0.95, "60187"),
                 "prior_study": v(True, 0.9, "I was in a study at a university a few years ago"),
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Ingrid, thanks for reaching out about the knee osteoarthritis study, and for finding us on ClinicalTrials.gov. The coordinator can tell you where the study stands and what taking part involves on a short pre-screen call. Visits are at our site in Naperville and parking is free. What days and times work for you?"},
         tricky="repeat participant flag"),
    conv("ct_04", "sms", "Felix Varga", "+1 (630) 555-0158",
         "Text: chest tightness before Thursday visit",
         [msg("inbound", 10100, "Hi, I filled out the form for the sleep apnea study. I was diagnosed with sleep apnea in March and I am 47. I use a CPAP. Zip 60565. When can I come in?"),
          msg("outbound", 9950, "Hi Felix, thanks for your interest in the sleep apnea study. Omar, our coordinator, went through the pre-screen with you by phone and has you down for a screening visit next Thursday at 10am at our site in Naperville. Parking is free. Reply here with any questions.", author="Omar"),
          msg("note", 9940, "Pre-screen done by phone. CPAP user, no exclusions noted. Screening visit 8/27 10am.", author="Omar"),
          msg("inbound", 35, "hi its felix, since sunday ive had chest tightness when i lay down and im short of breath. is that from the cpap? should i still come thursday")],
         stage="screening_visit", assignee="Omar", priority="urgent",
         fields={"study_interest": v("sleep_apnea", 0.97, "sleep apnea study"),
                 "condition": v("sleep apnea", 0.95, "diagnosed with sleep apnea"),
                 "age": v(47, 0.95, "I am 47"),
                 "current_meds": UNKNOWN,
                 "zip": v("60565", 0.95, "Zip 60565"),
                 "prior_study": UNKNOWN,
                 "urgency": v("high", 0.95, "chest tightness")},
         drafts={"reply": "Hi Felix, thank you for telling us right away. Chest tightness and shortness of breath are not something to wait on: please contact your doctor today, and if it gets worse or you feel unwell, call 911. Omar will call you today to talk it through and to sort out Thursday."},
         tricky="new symptom that sounds urgent: urgency high, distress stays in review"),
    conv("ct_05", "referral", "Theo Rinaldi", "+1 (630) 555-0148",
         "Referral from Dr. Moreau: chronic migraine",
         [msg("inbound", 700, "Referral logged from Dr. Elena Moreau, Prairie Neurology. Patient Theo Rinaldi, 29, chronic migraine, 15 or more headache days a month, currently on topiramate and rizatriptan. Lives in Lisle, 60532. Dr. Moreau says he has asked about research options. Best number 630 555 0148, prefers afternoons.")],
         fields={"study_interest": v("migraine_prevention", 0.85, "chronic migraine"),
                 "condition": v("chronic migraine", 0.95, "chronic migraine"),
                 "age": v(29, 0.9, "29"),
                 "current_meds": v(["topiramate", "rizatriptan"], 0.9, "topiramate and rizatriptan"),
                 "zip": v("60532", 0.95, "60532"),
                 "prior_study": UNKNOWN,
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Theo, Dr. Moreau's office let us know you were interested in research options for your migraines. We are running a migraine prevention study at our site in Naperville, and the first step is a short pre-screen call with our coordinator. Parking is free when you visit. You mentioned afternoons work best; what days suit you?"},
         tricky="physician referral logged by hand"),
    conv("ct_06", "web_form", "Harper Quinn", "harper.quinn@example.com",
         "Trial finder: type 2 diabetes, age 16",
         [msg("inbound", 900, "My mom said I should fill this out. I have type 2 diabetes, got diagnosed last year, I am 16 and take metformin. We live in Aurora 60504. Can I be in the diabetes study?")],
         fields={"study_interest": v("type_2_diabetes", 0.95, "diabetes study"),
                 "condition": v("type 2 diabetes", 0.95, "type 2 diabetes"),
                 "age": v(16, 0.97, "I am 16"),
                 "current_meds": v(["metformin"], 0.9, "metformin"),
                 "zip": v("60504", 0.95, "60504"),
                 "prior_study": UNKNOWN,
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Harper, thank you for reaching out, and please thank your mom for us. The studies we are running right now are for adults, so we are not able to include you at this time. Your doctor can tell you about research options for younger people, and you are welcome to check back with us later."},
         tricky="under 18: the auto reject rule fires"),
    conv("ct_07", "facebook_leads", "Sofia Delgado", "sofia.delgado@example.com",
         "Facebook lead: knee pain, not sure which study",
         [msg("inbound", 1100, "Lead form: Which study are you interested in? Not sure\nName: Sofia Delgado\nMessage: Both my knees hurt going up stairs, my doctor said it is probably arthritis but I have not had an xray. I am 58, zip 60540. Not on anything except ibuprofen.")],
         fields={"study_interest": v("unsure", 0.9, "Not sure"),
                 "condition": v("knee pain, probably arthritis", 0.85, "probably arthritis"),
                 "age": v(58, 0.95, "I am 58"),
                 "current_meds": v(["ibuprofen"], 0.9, "ibuprofen"),
                 "zip": v("60540", 0.95, "zip 60540"),
                 "prior_study": UNKNOWN,
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Sofia, thanks for reaching out. From what you describe, the knee osteoarthritis study is the one to ask about, and the coordinator can go over what it involves on a short pre-screen call. Visits are at our site in Naperville and parking is free. What days and times work for a call?"}),
    conv("ct_08", "sms", "Rohan Patel", "+1 (331) 555-0119",
         "Text: sleep apnea study, screening times",
         [msg("inbound", 2900, "Hi, I saw the sleep apnea study on facebook. I am 44, diagnosed with sleep apnea two years ago and I cant tolerate the cpap. 60564. What times do you have for the screening?"),
          msg("outbound", 2800, "Hi Rohan, thanks for reaching out about the sleep apnea study. The first step is a short pre-screen call with our coordinator; visits after that are at our site in Naperville, and parking is free. Would tomorrow morning or afternoon suit you?", author="Bridget"),
          msg("inbound", 2700, "tomorrow afternoon around 1 is good"),
          msg("outbound", 2650, "Perfect, Omar will call you tomorrow at 1pm. Reply here if anything changes.", author="Omar"),
          msg("note", 2640, "Pre-screen call set for 1pm. Ask when CPAP was stopped.", author="Omar")],
         stage="prescreen", assignee="Omar", unread=False,
         fields={"study_interest": v("sleep_apnea", 0.97, "sleep apnea study"),
                 "condition": v("sleep apnea", 0.95, "diagnosed with sleep apnea"),
                 "age": v(44, 0.95, "I am 44"),
                 "current_meds": UNKNOWN,
                 "zip": v("60564", 0.9, "60564"),
                 "prior_study": UNKNOWN,
                 "urgency": v("normal", 0.8, "")}),
    conv("ct_09", "email", "Grace Brennan", "grace.brennan@example.org",
         "Enrolled in the migraine study, thank you",
         [msg("inbound", 20000, "Hello, I saw the migraine prevention study on ClinicalTrials.gov. I am 39 and have had migraines since my twenties, around 8 a month. I take propranolol and sumatriptan. I live in Naperville, 60540. I have not been in a study before."),
          msg("outbound", 19900, "Hi Grace, thanks for reaching out about the migraine prevention study. The first step is a short pre-screen call with our coordinator, and visits after that are at our site in Naperville with free parking. What days and times work for a call?", author="Bridget"),
          msg("inbound", 19700, "Thursday morning works."),
          msg("outbound", 19600, "Thursday at 9am is set. Omar will call you then.", author="Omar"),
          msg("inbound", 2800, "Thank you both, the first visit went smoothly and the parking really was free!"),
          msg("note", 2500, "Pre-screen done 8/13. Screening visit 8/19, consented and enrolled 8/24. Closing intake.", author="Omar")],
         stage="enrolled", status="resolved", unread=False, assignee="Omar",
         fields={"study_interest": v("migraine_prevention", 0.97, "migraine prevention study"),
                 "condition": v("migraines", 0.95, "have had migraines since my twenties"),
                 "age": v(39, 0.95, "I am 39"),
                 "current_meds": v(["propranolol", "sumatriptan"], 0.9, "propranolol and sumatriptan"),
                 "zip": v("60540", 0.95, "60540"),
                 "prior_study": v(False, 0.95, "I have not been in a study before"),
                 "urgency": v("normal", 0.8, "")}),
    conv("ct_10", "web_form", "Yusuf Abara", "yusuf.abara@example.com",
         "Trial finder: diabetes, already in another study",
         [msg("inbound", 6000, "I have type 2 diabetes, 49 years old, on metformin and glipizide. I am currently in a study at a hospital downtown for a different diabetes drug that runs until December. Can I do yours too? Zip 60502."),
          msg("outbound", 5900, "Hi Yusuf, thanks for reaching out about the type 2 diabetes study. Being in another study at the same time is something the coordinator has to check, so I have passed this to Omar and he will call you.", author="Bridget"),
          msg("inbound", 5700, "ok thanks"),
          msg("outbound", 5000, "Hi Yusuf, Omar here. Thanks for the call. As we discussed, taking part in two studies at once is not possible, but please reach back out when your current study wraps up in December and we will see what is enrolling.", author="Omar"),
          msg("note", 4990, "Concurrent study, excluded for now. Recontact in January.", author="Omar")],
         stage="not_a_fit", status="resolved", unread=False, assignee="Omar",
         fields={"study_interest": v("type_2_diabetes", 0.95, "type 2 diabetes"),
                 "condition": v("type 2 diabetes", 0.95, "type 2 diabetes"),
                 "age": v(49, 0.95, "49 years old"),
                 "current_meds": v(["metformin", "glipizide"], 0.9, "metformin and glipizide"),
                 "zip": v("60502", 0.95, "Zip 60502"),
                 "prior_study": v(True, 0.9, "currently in a study at a hospital downtown"),
                 "urgency": v("normal", 0.8, "")}),
    conv("ct_11", "facebook_leads", "Claire Ivers", "claire.ivers@example.com",
         "Facebook lead: migraine study, evenings only",
         [msg("inbound", 1700, "Lead form: Migraine prevention study\nName: Claire Ivers\nMessage: I get about 6 migraines a month, 41 years old, on amitriptyline. I work days so I could only do visits after 5 or on Saturdays. Is that possible? 60563")],
         fields={"study_interest": v("migraine_prevention", 0.97, "Migraine prevention study"),
                 "condition": v("migraines", 0.95, "6 migraines a month"),
                 "age": v(41, 0.95, "41 years old"),
                 "current_meds": v(["amitriptyline"], 0.9, "amitriptyline"),
                 "zip": v("60563", 0.9, "60563"),
                 "prior_study": UNKNOWN,
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Claire, thanks for reaching out about the migraine prevention study. Visit scheduling is something the coordinator can go over with you, along with what the study involves, on a short pre-screen call. Visits are at our site in Naperville and parking is free. What days and times work for the call, keeping in mind you are free after 5?"}),
    conv("ct_12", "sms", "Leo Nakamura", "+1 (847) 555-0166",
         "Text: does the study cost anything",
         [msg("inbound", 240, "does the study cost me anything? i have type 2 diabetes, im 66 on medicare, take metformin and jardiance. zip 60540")],
         fields={"study_interest": v("type_2_diabetes", 0.95, "type 2 diabetes"),
                 "condition": v("type 2 diabetes", 0.95, "type 2 diabetes"),
                 "age": v(66, 0.95, "im 66"),
                 "current_meds": v(["metformin", "jardiance"], 0.9, "metformin and jardiance"),
                 "zip": v("60540", 0.95, "zip 60540"),
                 "prior_study": UNKNOWN,
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Leo, thanks for reaching out about the type 2 diabetes study. Costs and what taking part involves are things the coordinator goes over on a short pre-screen call, so I will leave that to them rather than answer in writing. Visits are at our site in Naperville and parking is free. What days and times work for a call?"},
         tricky="cost question: pricing stays in review"),
    conv("ct_13", "email", "Amara Okonkwo", "amara.okonkwo@example.com",
         "Knee study: screening visit booked",
         [msg("inbound", 7300, "Hi, I found the knee osteoarthritis study through ClinicalTrials.gov. I am 63, osteoarthritis in both knees for six years, I take meloxicam and I had a cortisone shot in June. Zip 60517. I did a flu vaccine study in 2019."),
          msg("outbound", 7200, "Hi Amara, thanks for reaching out about the knee osteoarthritis study. The first step is a short pre-screen call with our coordinator, and visits are at our site in Naperville with free parking. What days and times work for a call?", author="Bridget"),
          msg("inbound", 7000, "Any morning this week is fine, 630 555 0172."),
          msg("outbound", 5600, "Hi Amara, thank you for the call this morning. Your screening visit is set for Tuesday September 1 at 9:30am at our Naperville site. Please bring your medication list. Parking is free.", author="Omar"),
          msg("note", 5590, "Pre-screen done. Cortisone shot in June, check the washout window at screening.", author="Omar")],
         stage="screening_visit", assignee="Omar", unread=False,
         fields={"study_interest": v("knee_osteoarthritis", 0.97, "knee osteoarthritis study"),
                 "condition": v("osteoarthritis in both knees", 0.95, "osteoarthritis in both knees"),
                 "age": v(63, 0.95, "I am 63"),
                 "current_meds": v(["meloxicam"], 0.9, "meloxicam"),
                 "zip": v("60517", 0.95, "Zip 60517"),
                 "prior_study": v(True, 0.95, "I did a flu vaccine study in 2019"),
                 "urgency": v("normal", 0.8, "")}),
    conv("ct_14", "web_form", "Victor Sato", "victor.sato@example.com",
         "Trial finder: anything for rheumatoid arthritis",
         [msg("inbound", 9000, "I have rheumatoid arthritis, mostly in my hands, and my rheumatologist said to look for studies. I am 45, on methotrexate. Zip 60540. Do you have anything for RA?"),
          msg("outbound", 8900, "Hi Victor, thanks for reaching out. The four studies we are running right now are for migraine prevention, type 2 diabetes, knee osteoarthritis and sleep apnea, so we do not have a rheumatoid arthritis study at the moment. ClinicalTrials.gov lets you search by condition and location, and you are welcome to check back with us later.", author="Bridget"),
          msg("note", 8890, "No RA study. Closed.", author="Bridget")],
         stage="not_a_fit", status="resolved", unread=False, assignee="Bridget",
         fields={"study_interest": UNKNOWN,
                 "condition": v("rheumatoid arthritis", 0.95, "rheumatoid arthritis"),
                 "age": v(45, 0.95, "I am 45"),
                 "current_meds": v(["methotrexate"], 0.9, "methotrexate"),
                 "zip": v("60540", 0.95, "Zip 60540"),
                 "prior_study": UNKNOWN,
                 "urgency": v("normal", 0.8, "")}),
    conv("ct_15", "voicemail", "Wren Castillo", "+1 (815) 555-0139",
         "Voicemail: diabetes study, call back evenings",
         [msg("inbound", 80, "Voicemail transcript, 7:48 pm: Hi, this is Wren Castillo, I am calling about the diabetes study I saw on Facebook. I am 55, I have type 2 diabetes, I take metformin and I am on insulin at night. I live in Plainfield, 60585. Please call me back at 815 555 0139, evenings are best.")],
         fields={"study_interest": v("type_2_diabetes", 0.95, "diabetes study"),
                 "condition": v("type 2 diabetes", 0.95, "type 2 diabetes"),
                 "age": v(55, 0.95, "I am 55"),
                 "current_meds": v(["metformin", "insulin"], 0.9, "metformin and I am on insulin"),
                 "zip": v("60585", 0.95, "60585"),
                 "prior_study": UNKNOWN,
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Wren, thanks for calling about the type 2 diabetes study. Our coordinator will call you back in the evening, since you said that works best. The call is a short pre-screen where they go over what the study involves and ask a few questions about your health and medications. Visits are at our site in Naperville and parking is free."},
         tricky="on insulin: the exclusion flag fires"),
    conv("ct_16", "email", "Noah Haddad", "noah.haddad@example.org",
         "Sleep apnea study: asking for my father",
         [msg("inbound", 400, "Hi, I am writing for my father who is 71 and has sleep apnea. He was diagnosed a couple of years ago and refuses to use the CPAP. He takes lisinopril and a statin. He lives with us in Naperville, 60564. Is he too old for the sleep apnea study?")],
         fields={"study_interest": v("sleep_apnea", 0.97, "sleep apnea study"),
                 "condition": v("sleep apnea", 0.95, "has sleep apnea"),
                 "age": v(71, 0.95, "71"),
                 "current_meds": v(["lisinopril", "statin"], 0.85, "lisinopril and a statin"),
                 "zip": v("60564", 0.95, "60564"),
                 "prior_study": UNKNOWN,
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Noah, thanks for reaching out on your father's behalf. Age and health questions are exactly what the coordinator goes over on a short pre-screen call, so I cannot say in writing whether the sleep apnea study is a fit. Visits are at our site in Naperville and parking is free. Would your father be able to take a call, and what days and times work?"},
         tricky="eligibility question asked on behalf of someone else"),
]

TEMPLATE = {
    "key": "clinical_trial_site",
    "name": "Clinical research site",
    "tagline": "Study leads from ClinicalTrials.gov, Facebook ads, the trial finder and referring doctors",
    "example_prompt": "We run a clinical research site. Leads come from ClinicalTrials.gov, Facebook ads, our trial finder form, and referring doctors by email.",
    "signals": [("clinical trial", 5), ("clinical research", 5), ("research site", 4),
                ("clinicaltrials.gov", 5), ("trial finder", 4), ("study", 2), ("studies", 2),
                ("enroll", 2), ("participant", 2), ("referring doctor", 2)],
    "must_review": ["medical_legal", "pricing"],
    "spec": SPEC,
    "questions": QUESTIONS,
    "personas": ["Bridget", "Omar"],
    "ladders": LADDERS,
    "sample_inputs": SAMPLE_INPUTS,
    "prompt_examples": ["add a field for how many headache days a month",
                        "add a view of sleep apnea leads with no reply in 3 days",
                        "flag anyone who mentions being pregnant"],
    "conversations": C,
}
