"""Dental office with a med spa: Lakeshore Dental and Aesthetics (fictional), Chicago."""
from ._common import conv, msg, v, UNKNOWN

SPEC = {
    "business": {
        "name": "Lakeshore Dental and Aesthetics",
        "type": "dental_medspa",
        "summary": "Family dental practice with an in-house med spa, two Chicago locations (North on Clark St, South on Halsted). Cleanings, emergencies, Invisalign, whitening, Botox and filler.",
        "audience": "patients",
    },
    "connectors": [
        {"key": "zocdoc", "kind": "zocdoc", "label": "Zocdoc requests", "auto_connect": True},
        {"key": "instagram", "kind": "instagram", "label": "Instagram DMs", "auto_connect": True},
        {"key": "sms", "kind": "sms", "label": "Office text line", "auto_connect": True},
        {"key": "web_form", "kind": "web_form", "label": "Website request form", "auto_connect": True},
        {"key": "email", "kind": "email", "label": "hello@lakeshoredental.example.com", "auto_connect": True},
        {"key": "voicemail", "kind": "voicemail", "label": "After hours voicemail", "auto_connect": False},
    ],
    "fields": [
        {"key": "request_type", "label": "Request", "type": "enum",
         "options": ["cleaning", "emergency", "invisalign", "whitening", "botox", "filler", "consult", "other"],
         "hint": "What they are asking for; broken teeth, swelling and bad pain are emergencies", "show_in_list": True},
        {"key": "patient_status", "label": "Patient status", "type": "enum",
         "options": ["new", "existing"],
         "hint": "New if they say they have never been in; existing if they mention a past visit or their dentist here", "show_in_list": True},
        {"key": "insurance", "label": "Insurance", "type": "text",
         "hint": "Dental plan name if mentioned, or None if they say they have no insurance"},
        {"key": "location", "label": "Location", "type": "enum",
         "options": ["north", "south"],
         "hint": "North is Clark St, South is Halsted"},
        {"key": "preferred_time", "label": "Preferred time", "type": "text",
         "hint": "Days or times they say work for them"},
        {"key": "pain_level", "label": "Pain", "type": "enum",
         "options": ["none", "mild", "severe"],
         "hint": "Severe if they say a lot of pain, cannot eat or sleep, or swelling", "show_in_list": True},
        {"key": "urgency", "label": "Urgency", "type": "enum",
         "options": ["low", "normal", "high"],
         "hint": "High if they need to be seen today; normal if this week"},
    ],
    "stages": [
        {"key": "new", "label": "New", "tone": "brand"},
        {"key": "contacted", "label": "Contacted", "tone": "info"},
        {"key": "booked", "label": "Booked", "tone": "warn"},
        {"key": "seen", "label": "Seen", "tone": "ok", "terminal": True},
        {"key": "not_a_fit", "label": "Not a fit", "tone": "neutral", "terminal": True},
    ],
    "views": [
        {"key": "inbox", "name": "All open",
         "filter": {"all": [{"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "needs_reply", "name": "Needs reply",
         "filter": {"all": [{"field": "awaiting_reply", "op": "eq", "value": True}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "same_day", "name": "Same day",
         "filter": {"all": [{"any": [{"field": "f.pain_level", "op": "eq", "value": "severe"},
                                     {"field": "f.request_type", "op": "eq", "value": "emergency"}]},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "new_patients", "name": "New patients",
         "filter": {"all": [{"field": "f.patient_status", "op": "eq", "value": "new"},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "pricing_q", "name": "Pricing questions",
         "filter": {"all": [{"field": "flags", "op": "has_flag", "value": "pricing_q"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}},
        {"key": "unassigned", "name": "Unassigned",
         "filter": {"all": [{"field": "assignee", "op": "is_empty"},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}},
    ],
    "rules": [
        {"key": "urgent_pain", "name": "Pain and emergencies go to the top",
         "text": "Mark severe pain or an emergency as urgent",
         "when": {"any": [{"field": "f.pain_level", "op": "eq", "value": "severe"},
                          {"field": "f.request_type", "op": "eq", "value": "emergency"}]},
         "then": {"type": "set_priority", "value": "urgent"}},
        {"key": "same_day", "name": "Emergencies get a same-day slot",
         "text": "Flag emergencies for a same-day appointment",
         "when": {"all": [{"field": "f.request_type", "op": "eq", "value": "emergency"}]},
         "then": {"type": "flag", "label": "Same day", "tone": "danger"}},
        {"key": "aesthetics", "name": "Med spa requests",
         "text": "Flag Botox, filler and whitening so the injector sees them",
         "when": {"all": [{"field": "f.request_type", "op": "in", "value": ["botox", "filler", "whitening"]}]},
         "then": {"type": "flag", "label": "Aesthetics", "tone": "info"}},
        {"key": "pricing_q", "name": "Flag pricing questions",
         "text": "Botox and filler requests need a quote from the injector, never a price in writing",
         "when": {"all": [{"field": "f.request_type", "op": "in", "value": ["botox", "filler"]}]},
         "then": {"type": "flag", "label": "Quote needed", "tone": "warn"}},
    ],
    "approval_policy": {"routine": "auto_send", "pricing": "review",
                        "medical_legal": "review", "distress": "review"},
    "tone": {"voice": "warm", "length": "short", "signoff": "Jules at Lakeshore Dental and Aesthetics",
             "presets": [
                 {"label": "Answer their question", "instruction": "Answer the question they just asked"},
                 {"label": "Offer times", "instruction": "Offer the next open times at their location and ask which works"},
                 {"label": "Send the new patient form", "instruction": "Welcome them and send the link to the online new patient form"},
                 {"label": "Check in", "instruction": "Check in and ask whether they still want to come in"}]},
    "agent": {"name": "Jules", "persona": "Front desk coordinator at a dental office with a med spa",
              "intro": "I read every request, pull out what matters, and draft the first reply for you to approve."},
    "playbook": "- New patients get the link to the online new patient form before their first visit.\n- Emergencies (broken teeth, swelling, bad pain) get a same-day slot.\n- Never quote Botox or filler prices in writing; offer a consult where the injector gives an exact quote.\n- Two locations: North on Clark St and South on Halsted.",
    "guardrails": [
        {"key": "no_prices_or_treatment", "text": "Never quote a price for Botox, filler or any procedure in writing, and never say what treatment someone needs. Offer a consult.",
         "enforce": "never_promise"},
        {"key": "post_op_escalate", "text": "Swelling, fever or bleeding after a procedure goes to a clinician now: tell them to call the office or go to urgent care, and the dentist calls them.",
         "enforce": "escalate"},
    ],
}

QUESTIONS = [
    {"id": "sources", "kind": "tiles", "multi": True,
     "prompt": "Where do requests come in?",
     "why": "Each one becomes a connector and a way to filter.",
     "options": ["zocdoc", "instagram", "sms", "web_form", "email", "voicemail"],
     "default": ["zocdoc", "instagram", "sms", "web_form", "email"], "patch": "set_connectors"},
    {"id": "business_name", "kind": "text", "prompt": "What is the practice called?",
     "why": "It goes on every reply.", "default": "Lakeshore Dental and Aesthetics", "patch": "set_business_name"},
    {"id": "extract_fields", "kind": "chips", "multi": True,
     "prompt": "What should I pull out of every request?",
     "why": "Each one becomes a column you can sort and filter by.",
     "options": [["request_type", "What they want"], ["patient_status", "New or existing"],
                 ["insurance", "Insurance"], ["location", "Location"],
                 ["preferred_time", "Preferred time"], ["pain_level", "Pain"],
                 ["urgency", "Urgency"]],
     "default": ["request_type", "patient_status", "insurance", "location", "pain_level", "urgency"],
     "patch": "pick_fields"},
    {"id": "slices", "kind": "chips", "multi": True,
     "prompt": "Which views do you want on the front of the inbox?",
     "why": "Views are saved filters. You can add more later by typing.",
     "options": [["same_day", "Same day"], ["new_patients", "New patients"],
                 ["pricing_q", "Pricing questions"], ["unassigned", "Unassigned"]],
     "default": ["same_day", "new_patients"], "patch": "pick_views"},
    {"id": "approval", "kind": "chips", "multi": False,
     "prompt": "What may I send without you looking first?",
     "why": "Anything about prices, treatment, or a patient in pain always waits for you.",
     "options": [["routine", "Scheduling and the new patient form"], ["none", "Nothing, I review every reply"]],
     "default": "routine", "patch": "set_approval"},
    {"id": "tone", "kind": "chips", "multi": False, "prompt": "How should replies sound?",
     "why": "Sets the voice for every draft.",
     "options": [["warm", "Warm"], ["upbeat", "Upbeat"], ["plain", "Plain"]],
     "default": "warm", "patch": "set_tone"},
]

LADDERS = {
    "reply": [
        (("swelling", "swollen", "fever", "bleeding", "cannot open", "can't open"),
         "Thank you for writing, and I am sorry you are feeling this way. Please call the office right now so we can get you in front of the dentist today, and if you cannot reach us or it is getting worse, go to urgent care. I am flagging this to the dentist now and they will call you."),
        (("botox", "filler", "per unit", "syringe", "lip"),
         "Thanks for reaching out. Pricing for Botox and filler depends on what you would like to treat, so rather than guess here we book a short consult where the injector looks at the area, answers your questions and gives you an exact quote before anything is scheduled. Which days work best for you?"),
        (("broke", "broken", "cracked", "chipped", "knocked out", "hurts", "pain", "toothache"),
         "I am sorry, that sounds painful. Thank you for reaching out. We keep same-day slots for exactly this, so tell me which location is closer, North on Clark St or South on Halsted, and I will send you a time today."),
        (("whitening", "whiter", "brighter", "wedding", "stain"),
         "Thanks for reaching out, and that sounds like a great occasion. The best first step is a short visit so the dentist can look at your teeth and go over whitening options and timing with you. Which location and which days work best?"),
        (("invisalign", "aligners", "braces", "straighten", "crooked"),
         "Thanks for asking about Invisalign. The first step is a consult where the dentist looks at your teeth and walks through whether aligners are a good fit and what the plan would look like. Which location and which days work best for you?"),
        (("insurance", "cover", "covered", "self pay", "no insurance", "how much", "cost"),
         "Good question. What your plan covers depends on the specific plan, so I will have our insurance coordinator check your benefits and send you the numbers before anything is scheduled. Which plan are you on, and which location is closer to you?"),
    ],
    "fallback": "Thanks for reaching out to Lakeshore Dental and Aesthetics, {who}. I would be glad to get you in. Which location is closer, North on Clark St or South on Halsted, and which days and times work best for you?",
    "check_in": "Hi {who}, checking in to see whether you would still like to come in. Reply here any time and I will find a time that works at either location.",
    "booking": "Hi {who}, here is the link to book your visit. Pick any time that suits you, and reply here if none of them work.",
    "thanks": "Thank you, {who}. We will see you soon, and you can reply here with any questions before your visit.",
    "decline": "Thank you for reaching out, {who}. That is not a service we offer, but I am happy to help with a cleaning, Invisalign, whitening, Botox or filler if any of those are of interest.",
    "ask_missing": "Thanks {who}. To get you the right appointment, could you tell me which location is closer, whether you have been in before, and what days and times work for you?",
}

SAMPLE_INPUTS = [
    {"label": "Sample Zocdoc request", "source": "zocdoc",
     "text": "From: Zocdoc <bookings@zocdoc.example.com>\nSubject: New appointment request\n\nName: Renee Castillo\nNew patient: yes\nReason for visit: Cleaning and exam\nInsurance: Lakefront Dental PPO\nPreferred: Lakeshore Dental North, Friday September 4 at 3:00 pm\nMessage: It has been a while since my last cleaning and one of my back teeth is a little sensitive to cold. No real pain."},
    {"label": "Sample voicemail transcript", "source": "voicemail",
     "text": "Voicemail transcript, 9:05 pm: Hi, this is Walter Osei, I'm a patient at the Halsted office. I bit down on something at dinner and a piece of my back tooth came off. It's not bleeding but it's pretty sore. Can someone call me back first thing tomorrow at 312 555 0161 and get me in? Thanks."},
]

C = [
    conv("dm_01", "zocdoc", "Nora Lindqvist", "zocdoc:nora.lindqvist",
         "Zocdoc: new patient cleaning request",
         [msg("inbound", 240, "Zocdoc appointment request. Patient: Nora Lindqvist. New patient: yes. Reason for visit: Cleaning and exam. Insurance: Lakefront Dental PPO. Preferred: Lakeshore Dental North, Tuesday September 1 at 9:00 am. Note from patient: It has been about two years since my last cleaning, no pain, just want to get back on track.")],
         fields={"request_type": v("cleaning", 0.97, "Cleaning and exam"),
                 "patient_status": v("new", 0.95, "New patient: yes"),
                 "insurance": v("Lakefront Dental PPO", 0.95, "Lakefront Dental PPO"),
                 "location": v("north", 0.95, "Lakeshore Dental North"),
                 "preferred_time": v("Tuesday September 1 at 9:00 am", 0.95, "Tuesday September 1 at 9:00 am"),
                 "pain_level": v("none", 0.9, "no pain"),
                 "urgency": v("low", 0.8, "just want to get back on track")},
         drafts={"reply": "Hi Nora, thanks for requesting a visit through Zocdoc, and welcome. I am checking Tuesday September 1 at 9:00 am at our North office on Clark St now and will confirm it here shortly. Since you are new to us, I will send the online new patient form next; it takes about five minutes and saves you time at the desk."}),
    conv("dm_02", "instagram", "Sofia Rinaldi", "@sofia.rinaldi",
         "Whitening before my wedding",
         [msg("inbound", 55, "hi!! my wedding is October 10 and I want to get my teeth whitened before then. how much does it cost and how long does it take? I have never been to your office, I am closer to the Halsted location. no sensitivity or anything")],
         fields={"request_type": v("whitening", 0.96, "teeth whitened"),
                 "patient_status": v("new", 0.95, "never been to your office"),
                 "insurance": UNKNOWN,
                 "location": v("south", 0.9, "Halsted location"),
                 "preferred_time": v("before October 10", 0.8, "my wedding is October 10"),
                 "pain_level": v("none", 0.85, "no sensitivity or anything"),
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Sofia, congratulations on the wedding! Thanks for messaging us. The best first step is a short visit at our South office on Halsted so the dentist can look at your teeth and go over whitening options, timing and cost with you in person. Since you are new to us, I will send the online new patient form and a few open times. Which days work best?"},
         tricky="pricing question in a DM: review before sending"),
    conv("dm_03", "sms", "Kwame Osei", "+1 (773) 555-0118",
         "Text: chipped filling, sensitive to cold",
         [msg("inbound", 1500, "Hi this is Kwame Osei, I'm an existing patient at the North office. A filling on my lower left molar chipped last night eating popcorn. It's sensitive to cold but not really painful. Can I get in this week? Mornings are best."),
          msg("outbound", 1440, "Hi Kwame, thanks for texting, and sorry about the filling. I am checking the North schedule for a morning this week and will send you two options in a few minutes.", author="Jules"),
          msg("note", 1430, "Existing patient, chart 40-2217. Dr. Haddad has 8:30 Thursday or 9:15 Friday at North.", author="Jules"),
          msg("inbound", 60, "Thursday 8:30 works, thanks!")],
         stage="contacted", assignee="Jules",
         fields={"request_type": v("other", 0.7, "filling on my lower left molar chipped"),
                 "patient_status": v("existing", 0.95, "I'm an existing patient"),
                 "insurance": UNKNOWN,
                 "location": v("north", 0.95, "North office"),
                 "preferred_time": v("Mornings", 0.9, "Mornings are best"),
                 "pain_level": v("mild", 0.85, "sensitive to cold but not really painful"),
                 "urgency": v("normal", 0.8, "Can I get in this week?")},
         drafts={"reply": "Great, Kwame. I will book Thursday at 8:30 at the North office for you and send a confirmation text shortly. Reply here if anything changes."}),
    conv("dm_04", "web_form", "Elena Varga", "elena.varga@example.com",
         "Facial swelling and fever after extraction",
         [msg("inbound", 20, "I had a tooth pulled at your South office on Monday (wisdom tooth, lower right). Since yesterday the right side of my face is swollen and I have a fever of 101. It is very painful and I can barely open my mouth. I am an existing patient. Please tell me what to do.")],
         priority="urgent",
         fields={"request_type": v("emergency", 0.95, "swollen and I have a fever"),
                 "patient_status": v("existing", 0.95, "I am an existing patient"),
                 "insurance": UNKNOWN,
                 "location": v("south", 0.9, "South office"),
                 "preferred_time": UNKNOWN,
                 "pain_level": v("severe", 0.95, "very painful"),
                 "urgency": v("high", 0.95, "fever of 101")},
         drafts={"reply": "Elena, thank you for writing, and I am sorry you are feeling this way. Please call the office right now at (312) 555-0140 so we can get you in front of the dentist today, and if you cannot reach us or the swelling is making it hard to breathe or swallow, go to urgent care or the emergency room. I am flagging this to Dr. Haddad now and the dentist will call you."},
         tricky="swelling and fever after a procedure: distress and escalate, clinician now"),
    conv("dm_05", "email", "Theo Brennan", "theo.brennan@example.com",
         "How much is Botox per unit",
         [msg("inbound", 320, "Hi, I saw on Instagram that you do Botox at the North location. How much is Botox per unit and do you run any specials? I have never been in before. I am thinking forehead lines. Thanks.")],
         fields={"request_type": v("botox", 0.97, "Botox per unit"),
                 "patient_status": v("new", 0.9, "never been in before"),
                 "insurance": UNKNOWN,
                 "location": v("north", 0.9, "North location"),
                 "preferred_time": UNKNOWN,
                 "pain_level": UNKNOWN,
                 "urgency": v("low", 0.6, "")},
         drafts={"reply": "Hi Theo, thanks for reaching out, and welcome. Botox pricing depends on what you would like to treat, so rather than quote a number here, we set up a short consult at the North office on Clark St where the injector looks at the area and gives you an exact quote before anything is booked. Which days work best for you?"},
         tricky="Botox price question: quote needed flag, review before sending"),
    conv("dm_06", "zocdoc", "Rohan Patel", "zocdoc:rohan.patel",
         "Zocdoc: Invisalign consult",
         [msg("inbound", 700, "Zocdoc appointment request. Patient: Rohan Patel. New patient: yes. Reason for visit: Invisalign consultation. Insurance: Summit Dental. Preferred: Lakeshore Dental South, Thursday September 3 at 4:30 pm. Note from patient: My bottom teeth have shifted since I stopped wearing my retainer. Does insurance cover any of this?")],
         fields={"request_type": v("invisalign", 0.97, "Invisalign consultation"),
                 "patient_status": v("new", 0.95, "New patient: yes"),
                 "insurance": v("Summit Dental", 0.95, "Summit Dental"),
                 "location": v("south", 0.95, "Lakeshore Dental South"),
                 "preferred_time": v("Thursday September 3 at 4:30 pm", 0.95, "Thursday September 3 at 4:30 pm"),
                 "pain_level": UNKNOWN,
                 "urgency": v("low", 0.6, "")},
         drafts={"reply": "Hi Rohan, thanks for requesting an Invisalign consult through Zocdoc. I am checking Thursday September 3 at 4:30 pm at our South office on Halsted and will confirm here shortly. What Summit Dental covers depends on your plan, so bring your card and we will check your benefits before the visit. Since you are new to us, I will send the online new patient form next."}),
    conv("dm_07", "instagram", "Maya Nakamura", "@maya.nak",
         "Lip filler, is it painful",
         [msg("inbound", 95, "Hey! Thinking about lip filler for the first time. Is it painful? And what does it run? I'm already a patient at Halsted for cleanings")],
         fields={"request_type": v("filler", 0.96, "lip filler"),
                 "patient_status": v("existing", 0.9, "already a patient"),
                 "insurance": UNKNOWN,
                 "location": v("south", 0.85, "Halsted"),
                 "preferred_time": UNKNOWN,
                 "pain_level": UNKNOWN,
                 "urgency": v("low", 0.6, "Thinking about")},
         drafts={"reply": "Hi Maya, thanks for the message, and it is lovely to hear from a Halsted regular. Filler pricing depends on the product and the amount, so rather than guess here we book a short consult where the injector answers the comfort question in person, walks through what to expect and gives you an exact quote. Which days work best for you?"},
         tricky="filler price question: quote needed flag, review before sending"),
    conv("dm_08", "sms", "Diego Delgado", "+1 (312) 555-0163",
         "Text: broke a front tooth, in a lot of pain",
         [msg("inbound", 15, "I fell playing basketball an hour ago and broke my front tooth in half. It hurts really bad and it's bleeding a little. I'm not a patient yet, I'm near the Clark St office. Can someone see me today?")],
         priority="urgent",
         fields={"request_type": v("emergency", 0.97, "broke my front tooth"),
                 "patient_status": v("new", 0.95, "not a patient yet"),
                 "insurance": UNKNOWN,
                 "location": v("north", 0.9, "Clark St office"),
                 "preferred_time": v("today", 0.9, "see me today"),
                 "pain_level": v("severe", 0.9, "hurts really bad"),
                 "urgency": v("high", 0.95, "Can someone see me today?")},
         drafts={"reply": "Diego, I am sorry, that sounds awful. Yes, please come to the North office on Clark St. I am holding a same-day emergency slot and will text you the time in the next few minutes. If you have the broken piece, bring it with you, and call (312) 555-0140 if the bleeding does not slow down."}),
    conv("dm_09", "zocdoc", "Grace Moreau", "zocdoc:grace.moreau",
         "Zocdoc: cleanings for two kids",
         [msg("inbound", 2900, "Zocdoc appointment request. Patient: Grace Moreau (booking for two children, ages 7 and 10). New patient: no. Reason for visit: Cleaning and exam. Insurance: Northwind Dental HMO. Preferred: Lakeshore Dental North, Saturday August 29 at 10:00 am. Note from patient: Back to school cleanings, both kids, back to back if possible."),
          msg("outbound", 2800, "Hi Grace, thanks for the request. Both kids are booked back to back at the North office this Saturday August 29 at 10:00 am and 10:40 am with our hygienist. A confirmation is on its way.", author="Andre"),
          msg("note", 2790, "Two 40 minute hygiene slots with Renata, 10:00 and 10:40. Northwind on file, verified.", author="Andre")],
         stage="booked", assignee="Andre", unread=False,
         fields={"request_type": v("cleaning", 0.97, "Cleaning and exam"),
                 "patient_status": v("existing", 0.95, "New patient: no"),
                 "insurance": v("Northwind Dental HMO", 0.95, "Northwind Dental HMO"),
                 "location": v("north", 0.95, "Lakeshore Dental North"),
                 "preferred_time": v("Saturday August 29 at 10:00 am", 0.95, "Saturday August 29 at 10:00 am"),
                 "pain_level": UNKNOWN,
                 "urgency": v("low", 0.7, "Back to school cleanings")}),
    conv("dm_10", "email", "Ingrid Sato", "ingrid.sato@example.com",
         "Cleaning at South, existing patient",
         [msg("inbound", 20000, "Hello, I would like to book a cleaning at the South office, I am an existing patient. Any afternoon next week is fine. My insurance is Beacon Dental."),
          msg("outbound", 19900, "Hi Ingrid, thanks for reaching out. You are set for Wednesday August 19 at 2:00 pm at the South office. A confirmation is on its way.", author="Jules"),
          msg("inbound", 9500, "Thank you, the cleaning went well, see you in six months.")],
         stage="seen", status="resolved", unread=False, assignee="Jules",
         fields={"request_type": v("cleaning", 0.97, "book a cleaning"),
                 "patient_status": v("existing", 0.95, "existing patient"),
                 "insurance": v("Beacon Dental", 0.95, "Beacon Dental"),
                 "location": v("south", 0.95, "South office"),
                 "preferred_time": v("Any afternoon next week", 0.9, "Any afternoon next week"),
                 "pain_level": UNKNOWN,
                 "urgency": v("low", 0.7, "")}),
    conv("dm_11", "web_form", "Yusuf Abara", "yusuf.abara@example.com",
         "New patient, no insurance, cleaning cost",
         [msg("inbound", 900, "Name: Yusuf Abara\nPhone: (773) 555-0182\nLocation: North\nI moved to Chicago in July and need a new dentist. I do not have dental insurance right now. Looking for a cleaning and checkup, and I want to know what a visit costs without insurance before I book. Evenings after 5 work best.")],
         fields={"request_type": v("cleaning", 0.95, "cleaning and checkup"),
                 "patient_status": v("new", 0.9, "need a new dentist"),
                 "insurance": v("None", 0.95, "do not have dental insurance"),
                 "location": v("north", 0.95, "Location: North"),
                 "preferred_time": v("Evenings after 5", 0.9, "Evenings after 5 work best"),
                 "pain_level": UNKNOWN,
                 "urgency": v("low", 0.7, "")},
         drafts={"reply": "Hi Yusuf, welcome to Chicago, and thanks for reaching out. I will have the front desk send you the self-pay fee sheet for a new patient cleaning and exam so you have the numbers before you book anything. I will also check for evening openings after 5 at the North office on Clark St and send the online new patient form next. Reply here with any questions."},
         tricky="self-pay pricing: review before sending"),
    conv("dm_12", "web_form", "Claire Ivers", "claire.ivers@example.com",
         "Botox consult request",
         [msg("inbound", 4300, "Name: Claire Ivers\nLocation: South\nI would like to book a Botox consult. I have had Botox before at another office. Existing dental patient here. Free most weekday mornings."),
          msg("outbound", 4200, "Hi Claire, thanks for reaching out. You are booked for a Botox consult with our injector at the South office on Monday August 31 at 9:30 am. The injector will go over what you are looking for and give you an exact quote at the visit.", author="Jules"),
          msg("note", 4190, "Consult with Nina (injector) Mon 8/31 9:30. Prior Botox elsewhere, no records needed.", author="Jules")],
         stage="booked", assignee="Jules", unread=False,
         fields={"request_type": v("botox", 0.97, "Botox consult"),
                 "patient_status": v("existing", 0.95, "Existing dental patient"),
                 "insurance": UNKNOWN,
                 "location": v("south", 0.95, "Location: South"),
                 "preferred_time": v("weekday mornings", 0.9, "most weekday mornings"),
                 "pain_level": UNKNOWN,
                 "urgency": v("low", 0.6, "")}),
    conv("dm_13", "instagram", "Harper Quinn", "@harperq",
         "Laser hair removal?",
         [msg("inbound", 6000, "Do you guys do laser hair removal? Looking for underarms and legs"),
          msg("outbound", 5900, "Hi Harper, thanks for asking! Laser hair removal is not something we offer; our med spa side is Botox, filler and whitening. Happy to help if any of those are of interest.", author="Andre"),
          msg("inbound", 5800, "ok thanks anyway")],
         stage="not_a_fit", status="resolved", unread=False, assignee="Andre",
         fields={"request_type": v("other", 0.9, "laser hair removal"),
                 "patient_status": UNKNOWN,
                 "insurance": UNKNOWN,
                 "location": UNKNOWN,
                 "preferred_time": UNKNOWN,
                 "pain_level": UNKNOWN,
                 "urgency": v("low", 0.6, "")}),
    conv("dm_14", "voicemail", "Victor Castillo", "+1 (708) 555-0139",
         "Voicemail: existing patient, cracked tooth",
         [msg("inbound", 750, "Voicemail transcript, 7:48 pm: Hi, this is Victor Castillo, I'm a patient of Dr. Haddad at the South office. I think I cracked a tooth, upper left, biting down on an olive pit at dinner. It's a dull ache, nothing terrible, but it's sensitive when I chew. Could you call me back tomorrow morning and get me in this week? My number is 708 555 0139. Thanks.")],
         fields={"request_type": v("emergency", 0.7, "cracked a tooth"),
                 "patient_status": v("existing", 0.95, "a patient of Dr. Haddad"),
                 "insurance": UNKNOWN,
                 "location": v("south", 0.95, "South office"),
                 "preferred_time": v("this week, mornings", 0.7, "get me in this week"),
                 "pain_level": v("mild", 0.85, "dull ache, nothing terrible"),
                 "urgency": v("normal", 0.8, "get me in this week")},
         drafts={"reply": "Hi Victor, thanks for the voicemail, and sorry about the tooth. I am looking at Dr. Haddad's schedule at the South office for this week and will call you this morning with a couple of options. If the ache gets worse before then, call the office and we will move you up."}),
    conv("dm_15", "sms", "Leo Ferreira", "+1 (847) 555-0121",
         "Text: whitening touch up",
         [msg("inbound", 30000, "Hi, existing patient at North. Can I come in for a whitening touch up before the 15th? Any weekday after 4."),
          msg("outbound", 29900, "Hi Leo, thanks for texting. You are booked for a whitening touch up at the North office on Thursday August 13 at 4:30 pm. A confirmation is on its way.", author="Andre"),
          msg("inbound", 18000, "Done, looks great, thanks Andre")],
         stage="seen", status="resolved", unread=False, assignee="Andre",
         fields={"request_type": v("whitening", 0.97, "whitening touch up"),
                 "patient_status": v("existing", 0.95, "existing patient"),
                 "insurance": UNKNOWN,
                 "location": v("north", 0.9, "at North"),
                 "preferred_time": v("weekday after 4", 0.9, "Any weekday after 4"),
                 "pain_level": UNKNOWN,
                 "urgency": v("low", 0.7, "")}),
    conv("dm_16", "email", "Amara Okonkwo", "amara.okonkwo@example.com",
         "Does my plan cover Invisalign for my daughter",
         [msg("inbound", 1300, "Hi, I'm an existing patient at the Clark St office. My daughter (14) was told at her cleaning she might be a candidate for Invisalign. We have Harbor Benefits dental through my work. Can you tell me if the plan covers it and what our part would be? We would need after school appointments.")],
         fields={"request_type": v("invisalign", 0.95, "Invisalign"),
                 "patient_status": v("existing", 0.95, "existing patient"),
                 "insurance": v("Harbor Benefits", 0.9, "Harbor Benefits dental"),
                 "location": v("north", 0.9, "Clark St office"),
                 "preferred_time": v("after school", 0.9, "after school appointments"),
                 "pain_level": UNKNOWN,
                 "urgency": v("low", 0.7, "")},
         drafts={"reply": "Hi Amara, thanks for reaching out. Harbor Benefits coverage for Invisalign depends on the specific plan, so I will have our insurance coordinator run your daughter's benefits and email you what the plan covers and what your part would be before anything is scheduled. Once you have the numbers, we can set up an after school consult at the North office. Reply here with any questions."},
         tricky="coverage and cost question: review before sending"),
]

TEMPLATE = {
    "key": "dental_medspa",
    "name": "Dental office with a med spa",
    "tagline": "Appointment requests from Zocdoc, Instagram, texts, email, the site form and voicemail",
    "example_prompt": "Dental office with a med spa, two locations. Requests come through Zocdoc, Instagram DMs, texts, email, our web form and voicemail.",
    "signals": [("dental", 4), ("dentist", 4), ("med spa", 5), ("medspa", 5), ("botox", 4),
                ("filler", 3), ("invisalign", 3), ("whitening", 3), ("zocdoc", 3), ("cleaning", 1)],
    "must_review": ["pricing", "medical_legal"],
    "spec": SPEC,
    "questions": QUESTIONS,
    "personas": ["Jules", "Andre"],
    "ladders": LADDERS,
    "sample_inputs": SAMPLE_INPUTS,
    "prompt_examples": ["add a field for which dentist they see",
                        "add a view of Invisalign consults at South",
                        "flag anyone asking about financing"],
    "conversations": C,
}
