"""Generic fallback: any small business inbox. The conversations read like a
small local studio or workshop, but nothing in the spec assumes a vertical."""
from ._common import conv, msg, v, UNKNOWN

SPEC = {
    "business": {
        "name": "Your business",
        "type": "generic",
        "summary": "",
        "audience": "leads",
    },
    "connectors": [
        {"key": "email", "kind": "email", "label": "Email inbox", "auto_connect": True},
        {"key": "web_form", "kind": "web_form", "label": "Website form", "auto_connect": True},
        {"key": "instagram", "kind": "instagram", "label": "Instagram DMs", "auto_connect": True},
        {"key": "sms", "kind": "sms", "label": "Text line", "auto_connect": True},
        {"key": "voicemail", "kind": "voicemail", "label": "Phone and voicemail", "auto_connect": False},
        {"key": "webhook", "kind": "webhook", "label": "Zapier or webhook", "auto_connect": False},
        {"key": "csv", "kind": "csv", "label": "CSV import", "auto_connect": False},
    ],
    "fields": [
        {"key": "topic", "label": "Topic", "type": "enum",
         "options": ["quote", "booking", "question", "complaint", "other"],
         "hint": "What they are writing about", "show_in_list": True},
        {"key": "urgency", "label": "Urgency", "type": "enum",
         "options": ["low", "normal", "high"],
         "hint": "High when they say urgent, today, asap, or something has gone wrong", "show_in_list": True},
        {"key": "contact_preference", "label": "Contact preference", "type": "enum",
         "options": ["email", "phone", "text", "either"],
         "hint": "How they want to hear back, only if they say"},
        {"key": "budget", "label": "Budget", "type": "number",
         "hint": "A dollar amount they say they want to spend"},
        {"key": "preferred_dates", "label": "Preferred dates", "type": "list",
         "hint": "Dates or days they ask for, as ISO dates when possible", "show_in_list": True},
        {"key": "next_step", "label": "Next step", "type": "text",
         "hint": "What they want to happen next"},
    ],
    "stages": [
        {"key": "new", "label": "New", "tone": "brand"},
        {"key": "replied", "label": "Replied", "tone": "info"},
        {"key": "waiting", "label": "Waiting", "tone": "warn"},
        {"key": "done", "label": "Done", "tone": "ok", "terminal": True},
        {"key": "not_a_fit", "label": "Not a fit", "tone": "neutral", "terminal": True},
    ],
    "views": [
        {"key": "inbox", "name": "All open",
         "filter": {"all": [{"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "needs_reply", "name": "Needs reply",
         "filter": {"all": [{"field": "awaiting_reply", "op": "eq", "value": True}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "urgent", "name": "Urgent",
         "filter": {"all": [{"field": "f.urgency", "op": "eq", "value": "high"},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "quotes", "name": "Quotes",
         "filter": {"all": [{"field": "f.topic", "op": "eq", "value": "quote"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "bookings", "name": "Bookings",
         "filter": {"all": [{"field": "f.topic", "op": "eq", "value": "booking"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}},
        {"key": "complaints", "name": "Complaints",
         "filter": {"all": [{"field": "f.topic", "op": "eq", "value": "complaint"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}},
    ],
    "rules": [
        {"key": "complaint_high", "name": "Complaints go to the top",
         "text": "Mark complaints as high priority",
         "when": {"all": [{"field": "f.topic", "op": "eq", "value": "complaint"}]},
         "then": {"type": "set_priority", "value": "high"}},
        {"key": "flag_complaint", "name": "Complaint",
         "text": "Flag complaints so they are easy to spot",
         "when": {"all": [{"field": "f.topic", "op": "eq", "value": "complaint"}]},
         "then": {"type": "flag", "label": "Complaint", "tone": "warn"}},
        {"key": "urgent_urgent", "name": "Urgent messages",
         "text": "Mark anything urgent as urgent priority",
         "when": {"all": [{"field": "f.urgency", "op": "eq", "value": "high"}]},
         "then": {"type": "set_priority", "value": "urgent"}},
    ],
    "approval_policy": {"routine": "auto_send", "pricing": "review",
                        "medical_legal": "review", "distress": "review"},
    "tone": {"voice": "warm", "length": "short", "signoff": "",
             "presets": [
                 {"label": "Answer their question", "instruction": "Answer the question they just asked"},
                 {"label": "Offer a time", "instruction": "Offer a time and ask which days work"},
                 {"label": "Ask for details", "instruction": "Ask for the details we still need"},
                 {"label": "Check in", "instruction": "Check in and ask whether they are still interested"}]},
    "agent": {"name": "Omni", "persona": "Intake coordinator",
              "intro": "I read every new message, pull out what matters, and draft the first reply for you to approve."},
    "playbook": "- Reply within one business day.\n- Never quote prices that are not on the price list.\n- If you do not know the answer, say so and say who will follow up.",
    "guardrails": [
        {"key": "no_invented_prices", "text": "Never invent prices or availability. If it is not on the price list or the calendar, say you will confirm.",
         "enforce": "never_promise"},
    ],
}

QUESTIONS = [
    {"id": "business_type", "kind": "text", "prompt": "What kind of business is this?",
     "why": "It shapes the fields and the voice.", "default": "", "patch": "set_business_summary"},
    {"id": "sources", "kind": "tiles", "multi": True,
     "prompt": "Where do new messages come in?",
     "why": "Each one becomes a connector and a way to filter.",
     "options": ["email", "web_form", "instagram", "sms", "voicemail", "webhook", "csv"],
     "default": ["email", "web_form", "instagram", "sms"], "patch": "set_connectors"},
    {"id": "business_name", "kind": "text", "prompt": "What is the business called?",
     "why": "It goes on every reply.", "default": "Your business", "patch": "set_business_name"},
    {"id": "extract_fields", "kind": "chips", "multi": True,
     "prompt": "What should I pull out of every new message?",
     "why": "Each one becomes a column you can sort and filter by.",
     "options": [["topic", "What it is about"], ["urgency", "How urgent"],
                 ["contact_preference", "How to reach them"], ["budget", "Budget"],
                 ["preferred_dates", "Dates they want"], ["next_step", "What they want next"]],
     "default": ["topic", "urgency", "contact_preference", "preferred_dates"],
     "patch": "pick_fields"},
    {"id": "slices", "kind": "chips", "multi": True,
     "prompt": "Which views do you want on the front of the inbox?",
     "why": "Views are saved filters. You can add more later by typing.",
     "options": [["urgent", "Urgent"], ["quotes", "Quotes"],
                 ["bookings", "Bookings"], ["complaints", "Complaints"]],
     "default": ["urgent", "quotes"], "patch": "pick_views"},
    {"id": "approval", "kind": "chips", "multi": False,
     "prompt": "What may I send without you looking first?",
     "why": "Anything about prices, or anything that reads as a complaint or distress, always waits for you.",
     "options": [["routine", "Acknowledgements and scheduling"], ["none", "Nothing, I review every reply"]],
     "default": "routine", "patch": "set_approval"},
    {"id": "tone", "kind": "chips", "multi": False, "prompt": "How should replies sound?",
     "why": "Sets the voice for every draft.",
     "options": [["warm", "Warm"], ["plain", "Plain"], ["formal", "Formal"]],
     "default": "warm", "patch": "set_tone"},
]

LADDERS = {
    "reply": [
        (("quote", "price", "how much", "cost", "estimate", "rate"),
         "Thanks for reaching out. I would be glad to put a quote together; I will confirm the pricing against our price list and get back to you within one business day. If you can tell me a little more about what you need and when, that speeds things up."),
        (("book", "booking", "appointment", "schedule", "reserve", "sign up", "spot"),
         "Thanks for reaching out. I would be glad to get you booked; tell me which days and times work best and I will confirm within one business day."),
        (("cancel", "reschedule", "move my", "change my", "push back"),
         "No problem at all. Tell me which new days and times work and I will move your booking and confirm here once it is done."),
        (("late", "wrong", "damaged", "refund", "disappointed", "never arrived", "charged twice", "complaint"),
         "I am sorry about this, and thank you for telling us. I am looking into it now and will get back to you within one business day with what happened and how we will put it right."),
        (("gift certificate", "gift card", "voucher"),
         "Thank you for thinking of us for a gift. Tell me the amount you have in mind and who it is for, and I will let you know how to get it to you."),
        (("hours", "open", "closed", "where are you", "location", "address"),
         "Thanks for asking. I will confirm the details you asked about and reply with a clear answer within one business day."),
    ],
    "fallback": "Thanks for reaching out, {who}. I have your message and will get back to you within one business day. If there is anything else you want me to know, reply here any time.",
    "check_in": "Hi {who}, checking in on your message. Is this still something you would like help with? Reply here any time.",
    "booking": "Hi {who}, here is the link to book a time. Pick whatever suits you and reply here if none of the times work.",
    "thanks": "Thank you, {who}. We will be in touch soon, and you can reply here with any questions.",
    "decline": "Thank you for reaching out, {who}. This is not something we can help with, but I appreciate you thinking of us.",
    "ask_missing": "Thanks {who}. To point you in the right direction, could you tell me a bit more about what you need and when you need it?",
}

SAMPLE_INPUTS = [
    {"label": "Sample forwarded email", "source": "email",
     "text": "From: Elena Quinn <elena.quinn@example.com>\nSubject: Custom order for a wedding\n\nHi there, I found you through a friend. I am looking for something custom for a wedding on October 17 and wanted to know what the process is and roughly what it costs. Email is best for me. Thanks!"},
    {"label": "Sample web form submission", "source": "web_form",
     "text": "Website form submission\nName: Kwame Lindqvist\nEmail: kwame.lindqvist@example.com\nPhone: (312) 555-0119\nHow can we help: I would like to book a spot in a Saturday session in September, either the 12th or the 19th. Is there space?"},
]

C = [
    conv("g_01", "email", "Grace Lindqvist", "grace.lindqvist@example.com",
         "Quote for a custom piece",
         [msg("inbound", 240, "Hi, I would like a quote for a custom piece, roughly 24 by 36 inches. My budget is around $400 and I would need it by mid October. Email is easiest for me. Thanks, Grace")],
         fields={"topic": v("quote", 0.95, "a quote for a custom piece"),
                 "urgency": v("normal", 0.7, ""),
                 "contact_preference": v("email", 0.9, "Email is easiest"),
                 "budget": v(400, 0.9, "around $400"),
                 "preferred_dates": v(["2026-10-15"], 0.5, "mid October"),
                 "next_step": v("a quote for a 24 by 36 inch custom piece", 0.85, "24 by 36 inches")},
         drafts={"reply": "Hi Grace, thanks for reaching out. I would be glad to put a quote together for a 24 by 36 custom piece with mid October in mind; I will confirm pricing against our price list and email you within one business day. If there is anything specific you are picturing, reply here and I will factor it in."},
         tricky="pricing: review before sending"),
    conv("g_02", "web_form", "Noah Ivers", "noah.ivers@example.com",
         "Two spots in the Saturday workshop on the 5th",
         [msg("inbound", 90, "Website form submission\nName: Noah Ivers\nEmail: noah.ivers@example.com\nHow can we help: I would like to book two spots in the Saturday workshop on the 5th. Can I pay when we arrive? Text is best.")],
         fields={"topic": v("booking", 0.95, "book two spots"),
                 "urgency": v("normal", 0.7, ""),
                 "contact_preference": v("text", 0.9, "Text is best"),
                 "budget": UNKNOWN,
                 "preferred_dates": v(["2026-09-05"], 0.8, "Saturday workshop on the 5th"),
                 "next_step": v("book two spots in the September 5 workshop", 0.85, "book two spots")},
         drafts={"reply": "Hi Noah, thanks for reaching out. I will check that there are two spots open in the Saturday workshop on the 5th and confirm by text, along with how payment works. If the 5th ends up full, I will send you the nearest date with space."}),
    conv("g_03", "instagram", "Maya Sato", "ig:maya.sato",
         "Open Sunday afternoon?",
         [msg("inbound", 30, "hi!! are you open sunday afternoon? wanted to stop by and see the space before booking anything")],
         fields={"topic": v("question", 0.9, "are you open sunday"),
                 "urgency": v("normal", 0.7, ""),
                 "contact_preference": UNKNOWN,
                 "budget": UNKNOWN,
                 "preferred_dates": v(["2026-08-30"], 0.7, "sunday afternoon"),
                 "next_step": v("stop by Sunday afternoon to see the space", 0.8, "stop by and see the space")},
         drafts={"reply": "Hi Maya, thanks for the message. I will confirm our Sunday hours and get right back to you here so you know before you head over. You are welcome to come see the space before booking anything."}),
    conv("g_04", "email", "Victor Abara", "victor.abara@example.com",
         "Order 4471 is two weeks late",
         [msg("inbound", 2900, "Order 4471 was supposed to ship on August 10 and it is now two weeks late. I have emailed twice with no response. I need this by the end of the month or I want a refund. Please call me at (773) 555-0141."),
          msg("outbound", 2800, "Victor, I am sorry, you should not have had to write three times. I have order 4471 in front of me and am finding out exactly where it is. I will call you at the number you gave by end of day today with a straight answer, and if we cannot get it to you by the end of the month I will refund it in full.", author="Alex"),
          msg("note", 2790, "Order 4471 held at the finisher. Called Victor, he will take delivery by the 29th. Following up with the finisher Thursday.", author="Alex")],
         stage="waiting", assignee="Alex", unread=False, priority="high",
         fields={"topic": v("complaint", 0.97, "two weeks late"),
                 "urgency": v("high", 0.9, "I need this by the end of the month"),
                 "contact_preference": v("phone", 0.9, "call me at"),
                 "budget": UNKNOWN,
                 "preferred_dates": v(["2026-08-31"], 0.6, "end of the month"),
                 "next_step": v("ship order 4471 by the end of the month or refund it", 0.9, "I want a refund")},
         tricky="complaint: flagged and high priority, already answered"),
    conv("g_05", "sms", "Amara Delgado", "+1 (312) 555-0157",
         "Move Thursday 2pm to next week",
         [msg("inbound", 60, "Hi, something came up, can I move my Thursday 2pm to next Thursday same time? Sorry for the short notice")],
         fields={"topic": v("booking", 0.95, "move my Thursday 2pm"),
                 "urgency": v("normal", 0.7, ""),
                 "contact_preference": UNKNOWN,
                 "budget": UNKNOWN,
                 "preferred_dates": v(["2026-09-03"], 0.85, "next Thursday same time"),
                 "next_step": v("move the Thursday 2pm booking to next Thursday", 0.9, "move my Thursday 2pm")},
         drafts={"reply": "Hi Amara, no problem at all. I will move your Thursday 2pm to next Thursday at the same time and confirm here once it is done. Thanks for letting me know ahead of time."}),
    conv("g_06", "web_form", "Tom Rinaldi", "tom.rinaldi@example.com",
         "Gift certificate for a friend",
         [msg("inbound", 1500, "Website form submission\nName: Tom Rinaldi\nEmail: tom.rinaldi@example.com\nHow can we help: I would like to buy a gift certificate for a friend's birthday on September 12. Something around $100. Can it be emailed to me?"),
          msg("outbound", 1400, "Hi Tom, thank you for thinking of us for the gift. Yes, a gift certificate can be emailed to you, and $100 works. I have sent a payment link to this email; once it goes through, the certificate follows within the hour, well ahead of the 12th.", author="Alex"),
          msg("note", 1390, "Payment link sent for a $100 certificate. Waiting on payment.", author="Alex")],
         stage="replied", assignee="Alex", unread=False,
         fields={"topic": v("other", 0.7, "gift certificate"),
                 "urgency": v("normal", 0.7, ""),
                 "contact_preference": v("email", 0.85, "Can it be emailed to me"),
                 "budget": v(100, 0.9, "around $100"),
                 "preferred_dates": v(["2026-09-12"], 0.85, "September 12"),
                 "next_step": v("email a $100 gift certificate", 0.85, "buy a gift certificate")}),
    conv("g_07", "email", "Wren Castillo", "wren.castillo@example.org",
         "Get more five star reviews on autopilot",
         [msg("inbound", 700, "Hi there, I run a review automation platform and businesses like yours see three times more reviews in 30 days. Can I grab 15 minutes this week to show you a demo?"),
          msg("note", 650, "Vendor pitch. No reply.", author="Alex")],
         stage="not_a_fit", status="resolved", unread=False, assignee="Alex",
         fields={"topic": v("other", 0.9, "review automation platform"),
                 "urgency": v("low", 0.8, ""),
                 "contact_preference": UNKNOWN,
                 "budget": UNKNOWN,
                 "preferred_dates": UNKNOWN,
                 "next_step": v("a 15 minute demo call", 0.8, "15 minutes this week")},
         tricky="vendor pitch: not a fit, no reply"),
    conv("g_08", "instagram", "Rohan Kim", "ig:rohan.kim",
         "Do you do repairs?",
         [msg("inbound", 400, "Do you do repairs? I have a piece I bought from you a couple years ago and one corner got damaged in a move. Would love to get it fixed rather than replace it")],
         fields={"topic": v("question", 0.9, "Do you do repairs"),
                 "urgency": v("normal", 0.7, ""),
                 "contact_preference": UNKNOWN,
                 "budget": UNKNOWN,
                 "preferred_dates": UNKNOWN,
                 "next_step": v("repair a damaged corner on an older piece", 0.85, "get it fixed")},
         drafts={"reply": "Hi Rohan, thanks for the message, and sorry to hear about the move damage. I will check whether a corner repair on that piece is something we can take on and get back to you within one business day. If you can send a photo of the damage here, that will help me give you a straight answer."}),
    conv("g_09", "email", "Claire Nakamura", "claire.nakamura@example.com",
         "Quote for 12 pieces for an October event",
         [msg("inbound", 4300, "Hello, I am organizing a company event on October 10 and would like a quote for 12 matching pieces as gifts for the team. Our budget is about $1,500 all in. Could you let me know if that is doable and what the options are?"),
          msg("outbound", 4200, "Hi Claire, thanks for reaching out, and this sounds like a lovely gift for the team. Twelve pieces for October 10 works on the calendar. I am putting together options and pricing from our price list against a $1,500 budget and will email them to you by Thursday.", author="Alex"),
          msg("note", 300, "Sent options and pricing. Waiting on Claire to pick one.", author="Alex")],
         stage="waiting", assignee="Alex", unread=False,
         fields={"topic": v("quote", 0.95, "a quote for 12 matching pieces"),
                 "urgency": v("normal", 0.7, ""),
                 "contact_preference": UNKNOWN,
                 "budget": v(1500, 0.95, "about $1,500"),
                 "preferred_dates": v(["2026-10-10"], 0.9, "October 10"),
                 "next_step": v("options and pricing for 12 matching pieces", 0.85, "what the options are")}),
    conv("g_10", "sms", "Felix Okafor", "+1 (708) 555-0182",
         "Picked up the order, thank you",
         [msg("inbound", 2000, "Picked up the order today, it is perfect. Thank you so much!"),
          msg("outbound", 1950, "Felix, that made my day. Thank you for letting us know, and enjoy it.", author="Alex")],
         stage="done", status="resolved", unread=False, assignee="Alex",
         fields={"topic": v("other", 0.8, "Thank you"),
                 "urgency": v("low", 0.8, ""),
                 "contact_preference": UNKNOWN,
                 "budget": UNKNOWN,
                 "preferred_dates": UNKNOWN,
                 "next_step": v("nothing, a thank you", 0.7, "Thank you so much")}),
    conv("g_11", "web_form", "Ana Torres", "ana.torres@example.com",
         "Charged twice for my booking",
         [msg("inbound", 150, "Website form submission\nName: Ana Torres\nEmail: ana.torres@example.com\nHow can we help: I was charged twice for my booking on August 22, $85 each time. I only booked one spot. Please refund the duplicate charge. Email is fine but this is urgent.")],
         priority="high",
         fields={"topic": v("complaint", 0.95, "charged twice"),
                 "urgency": v("high", 0.9, "this is urgent"),
                 "contact_preference": v("email", 0.85, "Email is fine"),
                 "budget": UNKNOWN,
                 "preferred_dates": UNKNOWN,
                 "next_step": v("refund the duplicate $85 charge", 0.95, "refund the duplicate charge")},
         drafts={"reply": "Hi Ana, I am sorry about the double charge, and thank you for flagging it. I am pulling up your August 22 booking now to confirm the duplicate $85 charge and get the refund started. I will email you today with confirmation and how long the refund takes to show up."},
         tricky="complaint: flag and high priority, distress stays in review"),
    conv("g_12", "voicemail", "Miguel Ferreira", "+1 (708) 555-0137",
         "Voicemail: callback about the beginner class",
         [msg("inbound", 500, "Voicemail transcript, 5:52 pm: Hi, this is Miguel Ferreira, I am interested in the beginner class you posted, the one on Saturday mornings. Could someone call me back at 708 555 0137 to talk about dates? Thanks.")],
         fields={"topic": v("booking", 0.85, "interested in the beginner class"),
                 "urgency": v("normal", 0.7, ""),
                 "contact_preference": v("phone", 0.95, "call me back"),
                 "budget": UNKNOWN,
                 "preferred_dates": UNKNOWN,
                 "next_step": v("a callback about beginner class dates", 0.9, "call me back at 708 555 0137 to talk about dates")},
         drafts={"reply": "Hi Miguel, thanks for calling about the Saturday morning beginner class. I will give you a call back at the number you left to go over the upcoming dates and get you signed up. If a particular time of day is best for the call, reply here and I will aim for it."}),
    conv("g_13", "email", "Ingrid Bell", "ingrid.bell@example.com",
         "Moving my September 2 appointment",
         [msg("inbound", 5000, "Hi, I need to move my appointment on September 2 at 10am. Could I do the following Wednesday instead, same time?"),
          msg("outbound", 4900, "Hi Ingrid, of course. I have moved you to Wednesday September 9 at 10am. See you then.", author="Alex"),
          msg("inbound", 4800, "Perfect, thank you!")],
         stage="done", status="resolved", unread=False, assignee="Alex",
         fields={"topic": v("booking", 0.95, "move my appointment"),
                 "urgency": v("normal", 0.7, ""),
                 "contact_preference": UNKNOWN,
                 "budget": UNKNOWN,
                 "preferred_dates": v(["2026-09-09"], 0.85, "the following Wednesday"),
                 "next_step": v("move the September 2 appointment to September 9", 0.9, "move my appointment on September 2")}),
    conv("g_14", "instagram", "Yusuf Marsh", "ig:yusuf.marsh",
         "How much for a small one?",
         [msg("inbound", 20, "how much for a small one like the one in your last post? and do you ship")],
         fields={"topic": v("quote", 0.9, "how much for a small one"),
                 "urgency": v("normal", 0.7, ""),
                 "contact_preference": UNKNOWN,
                 "budget": UNKNOWN,
                 "preferred_dates": UNKNOWN,
                 "next_step": v("price and shipping for a small piece like the last post", 0.8, "do you ship")},
         drafts={"reply": "Hi Yusuf, thanks for the message, and glad you liked the post. I will confirm the price for a small one against our price list, along with whether we can ship to you, and reply here within one business day."},
         tricky="pricing: review before sending"),
    conv("g_15", "web_form", "Harper Adler", "+1 (224) 555-0158",
         "Weekend availability in September",
         [msg("inbound", 1100, "Website form submission\nName: Harper Adler\nPhone: (224) 555-0158\nHow can we help: Do you have any weekend availability in September? Ideally September 12 or 13. There would be four of us. Call or text either way.")],
         fields={"topic": v("booking", 0.9, "weekend availability"),
                 "urgency": v("normal", 0.7, ""),
                 "contact_preference": v("either", 0.85, "Call or text either way"),
                 "budget": UNKNOWN,
                 "preferred_dates": v(["2026-09-12", "2026-09-13"], 0.9, "September 12 or 13"),
                 "next_step": v("book a weekend session for four on September 12 or 13", 0.85, "four of us")},
         drafts={"reply": "Hi Harper, thanks for reaching out. I will check what we have open on September 12 and 13 for a group of four and get back to you by phone or text within one business day. If those dates are full, I will send the nearest weekend with space."}),
]

TEMPLATE = {
    "key": "generic",
    "name": "Any business",
    "tagline": "A starting point for any inbox",
    "example_prompt": "",
    "signals": [],
    "must_review": [],
    "spec": SPEC,
    "questions": QUESTIONS,
    "personas": ["Omni", "Alex"],
    "ladders": LADDERS,
    "sample_inputs": SAMPLE_INPUTS,
    "prompt_examples": ["add a field for how they heard about us",
                        "add a view of bookings for next week",
                        "flag anyone asking for a refund"],
    "conversations": C,
}
