"""Group therapy practice: Cedar Grove Group Therapy (fictional), nine clinicians."""
from ._common import conv, msg, v, UNKNOWN

SPEC = {
    "business": {
        "name": "Cedar Grove Group Therapy",
        "type": "group_therapy",
        "summary": "Group therapy practice with nine clinicians running adult, teen and parent groups for anxiety, depression, grief, substance use, relationships and trauma. Every new client starts with a free 15 minute intake call.",
        "audience": "clients",
    },
    "connectors": [
        {"key": "psychology_today", "kind": "psychology_today", "label": "Psychology Today inquiries", "auto_connect": True},
        {"key": "web_form", "kind": "web_form", "label": "Website inquiry form", "auto_connect": True},
        {"key": "instagram", "kind": "instagram", "label": "Instagram DMs", "auto_connect": True},
        {"key": "sms", "kind": "sms", "label": "Practice text line", "auto_connect": True},
        {"key": "voicemail", "kind": "voicemail", "label": "Voicemail", "auto_connect": False},
        {"key": "email", "kind": "email", "label": "intake@cedargrovegroups.example.com", "auto_connect": True},
    ],
    "fields": [
        {"key": "concern", "label": "Concern", "type": "enum",
         "options": ["anxiety", "depression", "grief", "substance_use", "relationships", "trauma", "other"],
         "hint": "The main thing they say they need help with", "show_in_list": True},
        {"key": "group_preference", "label": "Group", "type": "enum",
         "options": ["adult", "teen", "parent"],
         "hint": "Adult when the person writing is the one joining; teen when it is for someone under 18; parent when a parent wants support for themselves",
         "show_in_list": True},
        {"key": "insurance", "label": "Insurance", "type": "text",
         "hint": "Insurer or plan they name, or self pay, or no insurance"},
        {"key": "availability", "label": "Availability", "type": "list",
         "hint": "Days or times they say they are free, one per item"},
        {"key": "referral_source", "label": "Referred by", "type": "text",
         "hint": "Who or what pointed them here: a therapist, doctor, school, friend, or a listing"},
        {"key": "is_for_minor", "label": "For someone under 18", "type": "bool",
         "hint": "True when the person who would join the group is under 18"},
        {"key": "urgency", "label": "Urgency", "type": "enum",
         "options": ["low", "normal", "high"],
         "hint": "High for any mention of self-harm, danger, or not wanting to be here; normal for everything else",
         "show_in_list": True},
    ],
    "stages": [
        {"key": "new", "label": "New", "tone": "brand"},
        {"key": "contacted", "label": "Contacted", "tone": "info"},
        {"key": "intake_scheduled", "label": "Intake scheduled", "tone": "warn"},
        {"key": "in_group", "label": "In a group", "tone": "ok", "terminal": True},
        {"key": "closed", "label": "Closed", "tone": "neutral", "terminal": True},
    ],
    "views": [
        {"key": "inbox", "name": "All open",
         "filter": {"all": [{"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "needs_reply", "name": "Needs reply",
         "filter": {"all": [{"field": "awaiting_reply", "op": "eq", "value": True}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "urgent", "name": "Urgent",
         "filter": {"any": [{"field": "priority", "op": "eq", "value": "urgent"},
                            {"field": "f.urgency", "op": "eq", "value": "high"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "teens", "name": "Teens",
         "filter": {"all": [{"field": "f.group_preference", "op": "eq", "value": "teen"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "insurance_questions", "name": "Insurance questions",
         "filter": {"all": [{"field": "f.insurance", "op": "not_empty"},
                            {"field": "stage", "op": "in", "value": ["new", "contacted"]}]},
         "sort": {"by": "last_message_at", "dir": "desc"}},
        {"key": "unassigned", "name": "Unassigned",
         "filter": {"all": [{"field": "assignee", "op": "is_empty"},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}},
    ],
    "rules": [
        {"key": "urgent_priority", "name": "Safety concerns go to the top",
         "text": "Mark anyone mentioning self-harm or danger as urgent",
         "when": {"all": [{"field": "f.urgency", "op": "eq", "value": "high"}]},
         "then": {"type": "set_priority", "value": "urgent"}},
        {"key": "clinician_today", "name": "Clinician the same day",
         "text": "Flag anyone mentioning self-harm or danger for a clinician today",
         "when": {"all": [{"field": "f.urgency", "op": "eq", "value": "high"}]},
         "then": {"type": "flag", "label": "Clinician today", "tone": "danger"}},
        {"key": "parent_consent", "name": "Parent consent for minors",
         "text": "Flag anyone under 18 so we collect parent consent",
         "when": {"all": [{"field": "f.is_for_minor", "op": "eq", "value": True}]},
         "then": {"type": "flag", "label": "Parent consent", "tone": "info"}},
        {"key": "cost_question", "name": "Insurance and cost questions",
         "text": "Flag anyone who mentions insurance or cost",
         "when": {"all": [{"field": "f.insurance", "op": "not_empty"}]},
         "then": {"type": "flag", "label": "Cost question", "tone": "warn"}},
    ],
    "approval_policy": {"routine": "review", "pricing": "review",
                        "medical_legal": "review", "distress": "review"},
    "tone": {"voice": "warm", "length": "short", "signoff": "Maya at Cedar Grove Group Therapy",
             "presets": [
                 {"label": "Answer their question", "instruction": "Answer the question they just asked"},
                 {"label": "Offer the intake call", "instruction": "Offer the free 15 minute intake call and ask which times work"},
                 {"label": "Ask what brings them in", "instruction": "Ask what brings them in and which days they are usually free"},
                 {"label": "Check in", "instruction": "Check in and ask whether they are still interested"}]},
    "agent": {"name": "Maya", "persona": "Intake coordinator at a group practice",
              "intro": "I read every inquiry, pull out what matters, and draft a reply for you to review before anything goes out."},
    "playbook": "- Groups meet on set days; the intake call is where we match someone to a group.\n- The intake call is a free 15 minute call with a clinician.\n- Never quote fees or sliding scale amounts in writing.\n- If someone is in danger, give them 988 and the nearest ER, and get a clinician on it today.",
    "guardrails": [
        {"key": "no_fees_or_placement", "text": "Never quote fees or say which group someone will join; the intake call decides both.",
         "enforce": "never_promise"},
        {"key": "safety_escalate", "text": "Any mention of self-harm or danger goes to a clinician the same day.",
         "enforce": "escalate"},
    ],
}

QUESTIONS = [
    {"id": "sources", "kind": "tiles", "multi": True,
     "prompt": "Where do new inquiries come in?",
     "why": "Each one becomes a connector and a way to filter.",
     "options": ["psychology_today", "web_form", "instagram", "sms", "voicemail", "email"],
     "default": ["psychology_today", "web_form", "instagram", "sms", "email"], "patch": "set_connectors"},
    {"id": "business_name", "kind": "text", "prompt": "What is the practice called?",
     "why": "It goes on every reply.", "default": "Cedar Grove Group Therapy", "patch": "set_business_name"},
    {"id": "extract_fields", "kind": "chips", "multi": True,
     "prompt": "What should I pull out of every new inquiry?",
     "why": "Each one becomes a column you can sort and filter by.",
     "options": [["concern", "What they need help with"], ["group_preference", "Adult, teen or parent group"],
                 ["insurance", "Insurance"], ["availability", "When they are free"],
                 ["referral_source", "Who referred them"], ["is_for_minor", "For someone under 18"],
                 ["urgency", "Urgency"]],
     "default": ["concern", "group_preference", "insurance", "availability", "is_for_minor", "urgency"],
     "patch": "pick_fields"},
    {"id": "slices", "kind": "chips", "multi": True,
     "prompt": "Which views do you want on the front of the inbox?",
     "why": "Views are saved filters. You can add more later by typing.",
     "options": [["urgent", "Urgent"], ["teens", "Teens"],
                 ["insurance_questions", "Insurance questions"], ["unassigned", "Unassigned"]],
     "default": ["urgent", "teens"], "patch": "pick_views"},
    {"id": "approval", "kind": "chips", "multi": False,
     "prompt": "What may I send without you looking first?",
     "why": "Most practices review every reply. Anything about fees or safety always waits for a clinician either way.",
     "options": [["routine", "Acknowledgements and scheduling"], ["none", "Nothing, I review every reply"]],
     "default": "none", "patch": "set_approval"},
    {"id": "tone", "kind": "chips", "multi": False, "prompt": "How should replies sound?",
     "why": "Sets the voice for every draft.",
     "options": [["warm", "Warm"], ["plain", "Plain"], ["formal", "Formal"]],
     "default": "warm", "patch": "set_tone"},
]

LADDERS = {
    "reply": [
        (("dont want to be here", "don't want to be here", "hurt myself", "end it all", "suicid", "kill myself", "not safe"),
         "Thank you for telling me, and I am glad you reached out. If you are thinking about hurting yourself, please call or text 988 any time, day or night, or go to the nearest emergency room. One of our clinicians will call you today. What is the best number to reach you?"),
        (("sliding scale", "how much", "cost", "fee", "price", "afford", "self pay"),
         "Thank you for asking. Fees and sliding scale are things we go over on the intake call rather than in writing, so you get a straight answer for your situation. The call is free and takes about 15 minutes. What days and times work for you?"),
        (("insurance", "in network", "medicaid", "medicare", "blue cross", "aetna", "cigna", "united"),
         "Thanks for telling me about your insurance. Coverage is something we confirm on the intake call so the answer is accurate for your plan. The call is free and takes about 15 minutes with one of our clinicians. What days and times work?"),
        (("my daughter", "my son", "teen", "teenager", "my kid", "year old"),
         "Thank you for reaching out about your child. The next step is a free 15 minute intake call with one of our clinicians, where we will also walk through the consent steps for someone under 18. What days and times work for you?"),
        (("which group", "what group", "when does", "what day", "schedule", "meet"),
         "Good question. Groups meet on set days, and which one fits is something we work out together on the intake call, a free 15 minute call with one of our clinicians. What days and times work for you?"),
        (("individual", "one on one", "1 on 1", "private sessions"),
         "Thanks for reaching out. We are a group practice, so all of our care happens in groups. If a group might work for you, the intake call is a free 15 minute conversation with a clinician. Would you like to set one up?"),
    ],
    "fallback": "Thank you for reaching out to Cedar Grove Group Therapy, {who}. The next step is a free 15 minute intake call with one of our clinicians to talk through what you are looking for. What days and times work for you?",
    "check_in": "Hi {who}, checking in to see whether you would still like to set up a free intake call. Reply here any time and I will find a time that works.",
    "booking": "Hi {who}, here is the link to book your free 15 minute intake call. Pick any time that suits you, and reply here if none of them work.",
    "thanks": "Thank you, {who}. A clinician will be in touch soon, and you can reply here with any questions.",
    "decline": "Thank you for reaching out, {who}. What you are describing is not something our groups are set up for, but Psychology Today and your insurer's directory can point you to a therapist who is. Take care.",
    "ask_missing": "Thanks {who}. So I can point you to the right clinician, could you tell me a little about what brings you in and which days you are usually free?",
}

SAMPLE_INPUTS = [
    {"label": "Sample Psychology Today inquiry", "source": "psychology_today",
     "text": "From: Psychology Today <no-reply@example.org>\nSubject: New client inquiry from your profile\n\nName: Renee Castillo\nEmail: renee.castillo@example.com\nPhone: 312 555 0161\nMessage: I have been struggling with anxiety since a job change in the spring and I think a group might help more than one on one. I have Blue Cross. I am free most evenings after 6."},
    {"label": "Sample voicemail transcript", "source": "voicemail",
     "text": "Voicemail transcript, 8:12 pm: Hi, this is Walter Osei, my doctor gave me your number. My wife passed in April and I have not been doing well. I am retired so any time works. I have Medicare. Please call me back at 773 555 0161."},
]

C = [
    conv("gt_01", "web_form", "Elena Varga", "elena.varga@example.com",
         "Anxiety, some days I don't want to be here",
         [msg("inbound", 40, "I have been dealing with anxiety for years and lately its gotten a lot worse, I cant sleep and some days i dont want to be here anymore. A friend said a group might help. I have Blue Cross. I am free evenings.")],
         priority="urgent",
         fields={"concern": v("anxiety", 0.95, "dealing with anxiety"),
                 "group_preference": v("adult", 0.6, ""),
                 "insurance": v("Blue Cross", 0.95, "Blue Cross"),
                 "availability": v(["evenings"], 0.9, "free evenings"),
                 "referral_source": v("a friend", 0.85, "A friend said"),
                 "is_for_minor": v(False, 0.6, ""),
                 "urgency": v("high", 0.97, "some days i dont want to be here anymore")},
         drafts={"reply": "Hi Elena, thank you for reaching out and for telling me how hard things have been. I want to make sure you are safe: if you are thinking about hurting yourself, please call or text 988 any time, day or night, or go to the nearest emergency room. One of our clinicians will call you today. What is the best number to reach you?"},
         tricky="distress: 988 and a clinician today, never auto-sent"),
    conv("gt_02", "psychology_today", "Omar Rinaldi", "omar.rinaldi@example.com",
         "Sliding scale for the grief group?",
         [msg("inbound", 210, "Hi, I lost my dad in May and I have not been doing well. I saw you have a grief group. I do not have insurance right now, do you offer a sliding scale and what would it cost? I can do weekday mornings.")],
         fields={"concern": v("grief", 0.95, "grief group"),
                 "group_preference": v("adult", 0.6, ""),
                 "insurance": v("no insurance", 0.9, "do not have insurance right now"),
                 "availability": v(["weekday mornings"], 0.9, "weekday mornings"),
                 "referral_source": UNKNOWN,
                 "is_for_minor": v(False, 0.6, ""),
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Omar, I am so sorry about your dad, and thank you for reaching out. Fees and sliding scale are things we go over on the intake call rather than in writing, so you get a straight answer for your situation. The call is free and takes about 15 minutes with one of our clinicians. Would a weekday morning this week work for you?"},
         tricky="sliding scale question: pricing stays in review"),
    conv("gt_03", "sms", "Hannah Moreau", "+1 (630) 555-0127",
         "Text: parent asking about the teen group",
         [msg("inbound", 95, "Hi, my daughter is 15 and has been really anxious since school started, panic attacks before tests. Her pediatrician mentioned you have a teen group. We have Aetna. She is free after 4 on weekdays.")],
         fields={"concern": v("anxiety", 0.95, "really anxious"),
                 "group_preference": v("teen", 0.95, "teen group"),
                 "insurance": v("Aetna", 0.95, "Aetna"),
                 "availability": v(["weekdays after 4"], 0.9, "after 4 on weekdays"),
                 "referral_source": v("pediatrician", 0.9, "Her pediatrician mentioned"),
                 "is_for_minor": v(True, 0.97, "my daughter is 15"),
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Hannah, thank you for reaching out about your daughter, and thank you to her pediatrician for the mention. The next step is a free 15 minute intake call with one of our clinicians, where you can talk through what she has been going through and what a group would look like. Since she is under 18, we will walk through the consent steps with you on that call. What days and times work for you?"},
         tricky="parent asking for a teen: the consent flag fires"),
    conv("gt_04", "email", "Devon Brennan", "devon.brennan@example.org",
         "Referral from Wilder Middle School counselor",
         [msg("inbound", 480, "Hello, I am the counselor at Wilder Middle School. I am writing with a parent's permission about a 13 year old student who lost his older brother in a car accident in July and is struggling. The family has Medicaid and is asking about your teen grief group. His mother, Nadia Abara, can be reached at 331 555 0126 and is available after 3pm most days.")],
         fields={"concern": v("grief", 0.95, "lost his older brother"),
                 "group_preference": v("teen", 0.95, "teen grief group"),
                 "insurance": v("Medicaid", 0.95, "Medicaid"),
                 "availability": v(["after 3pm most days"], 0.9, "after 3pm most days"),
                 "referral_source": v("school counselor", 0.95, "counselor at Wilder Middle School"),
                 "is_for_minor": v(True, 0.97, "13 year old student"),
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Devon, thank you for reaching out on the family's behalf, and I am so sorry for their loss. The next step is a free 15 minute intake call with one of our clinicians. I will reach out to his mother at the number you gave, after 3pm as you suggested, and we will go through the consent steps with her. Please let her know to expect our call."},
         tricky="school counselor referral for a minor"),
    conv("gt_05", "instagram", "Wren Quinn", "ig:wren.quinn",
         "IG DM: relationships group for partners?",
         [msg("inbound", 130, "hey saw your post about the relationships group. me and my partner keep having the same fight over and over, is the group for couples or just individuals? we both work till 6")],
         fields={"concern": v("relationships", 0.95, "relationships group"),
                 "group_preference": v("adult", 0.7, ""),
                 "insurance": UNKNOWN,
                 "availability": v(["after 6"], 0.8, "work till 6"),
                 "referral_source": v("Instagram post", 0.9, "saw your post"),
                 "is_for_minor": v(False, 0.7, ""),
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Wren, thanks for the message. Which group is the right fit, and how it works when you come as partners, is exactly what the intake call is for. It is a free 15 minute call with one of our clinicians. Would an evening after 6 work for you both?"}),
    conv("gt_06", "psychology_today", "Victor Adler", "victor.adler@example.com",
         "Substance use group after outpatient program",
         [msg("inbound", 1500, "I have been sober for 60 days and my counselor at the outpatient program said I should find a group for after I finish there in September. I have Cigna. I work nights so daytime is better."),
          msg("outbound", 1450, "Hi Victor, congratulations on 60 days, and thank you for reaching out. The next step is a free 15 minute intake call with one of our clinicians to talk through what you are looking for and what a group could look like after your program wraps up. Since daytime is better for you, what days work?", author="Maya"),
          msg("inbound", 1300, "Tuesday or Thursday around 11 works."),
          msg("outbound", 1250, "Thursday at 11am is set with Jonah. He will call you then.", author="Jonah"),
          msg("note", 1240, "Intake call Thu 11am. Coming from an outpatient program, finishing in September.", author="Jonah")],
         stage="intake_scheduled", assignee="Jonah", unread=False,
         fields={"concern": v("substance_use", 0.95, "sober for 60 days"),
                 "group_preference": v("adult", 0.75, ""),
                 "insurance": v("Cigna", 0.95, "Cigna"),
                 "availability": v(["daytime"], 0.9, "daytime is better"),
                 "referral_source": v("outpatient program counselor", 0.9, "counselor at the outpatient program"),
                 "is_for_minor": v(False, 0.8, ""),
                 "urgency": v("normal", 0.8, "")}),
    conv("gt_07", "web_form", "Ana Lindqvist", "ana.lindqvist@example.com",
         "Depression group, weeknight availability",
         [msg("inbound", 3000, "I was diagnosed with depression last year and my therapist is moving away, she suggested a group. I have United Healthcare. I can do Monday or Thursday evenings. I am 34."),
          msg("outbound", 2900, "Hi Ana, thank you for reaching out, and thank you to your therapist for the suggestion. The next step is a free 15 minute intake call with one of our clinicians to talk through what you are looking for. Would a call on Monday or Thursday evening suit you?", author="Maya"),
          msg("inbound", 2700, "Thursday evening works, 6pm?"),
          msg("outbound", 2600, "Thursday at 6pm is set with Jonah. He will call you then.", author="Jonah"),
          msg("note", 2590, "Intake call Thu 6pm. Therapist relocating, wants continuity.", author="Jonah")],
         stage="intake_scheduled", assignee="Jonah", unread=False,
         fields={"concern": v("depression", 0.95, "diagnosed with depression"),
                 "group_preference": v("adult", 0.85, "I am 34"),
                 "insurance": v("United Healthcare", 0.95, "United Healthcare"),
                 "availability": v(["Monday evenings", "Thursday evenings"], 0.9, "Monday or Thursday evenings"),
                 "referral_source": v("therapist", 0.9, "my therapist"),
                 "is_for_minor": v(False, 0.95, "I am 34"),
                 "urgency": v("normal", 0.8, "")}),
    conv("gt_08", "sms", "Theo Sato", "+1 (708) 555-0144",
         "Text: trauma group after a car accident",
         [msg("inbound", 260, "hi, i was in a bad car accident in april and i cant drive without shaking. my doctor said trauma group. do you take medicare? im 67, free most days")],
         fields={"concern": v("trauma", 0.95, "trauma group"),
                 "group_preference": v("adult", 0.85, "im 67"),
                 "insurance": v("Medicare", 0.95, "medicare"),
                 "availability": v(["most days"], 0.9, "free most days"),
                 "referral_source": v("doctor", 0.9, "my doctor said"),
                 "is_for_minor": v(False, 0.95, "im 67"),
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Theo, thank you for reaching out, and I am sorry about the accident. Insurance and coverage are things we confirm on the intake call so the answer is accurate for your plan. The call is free and takes about 15 minutes with one of our clinicians. Since you are free most days, what time of day is best for you?"},
         tricky="insurance question: the cost flag fires"),
    conv("gt_09", "instagram", "Sofia Haddad", "ig:sofia.haddad",
         "IG DM: remove me from your list",
         [msg("inbound", 8000, "please remove me from your list, i signed up for the newsletter by accident. thanks"),
          msg("outbound", 7900, "Done, Sofia. You will not hear from us again unless you reach out. Take care.", author="Maya"),
          msg("note", 7890, "Opt out. Removed from the newsletter list.", author="Maya")],
         stage="closed", status="resolved", unread=False, assignee="Maya",
         fields={"concern": UNKNOWN,
                 "group_preference": UNKNOWN,
                 "insurance": UNKNOWN,
                 "availability": UNKNOWN,
                 "referral_source": UNKNOWN,
                 "is_for_minor": UNKNOWN,
                 "urgency": v("low", 0.8, "")},
         tricky="opt out: closed and resolved, no reply needed"),
    conv("gt_10", "psychology_today", "Priya Kim", "priya.kim@example.com",
         "In the anxiety group now, thank you",
         [msg("inbound", 25000, "Hi, I found you on Psychology Today. I have had anxiety since college and it is affecting my work. I have Blue Cross PPO. Evenings after 6 are best."),
          msg("outbound", 24900, "Hi Priya, thank you for reaching out. The next step is a free 15 minute intake call with one of our clinicians to talk through what you are looking for. Would an evening after 6 work?", author="Maya"),
          msg("inbound", 24700, "Yes, Thursday evening please."),
          msg("outbound", 24600, "Thursday at 6:30pm is set with Jonah. He will call you then.", author="Jonah"),
          msg("inbound", 60, "Just wanted to say the first session last night went really well, thank you both."),
          msg("note", 50, "Started in the Tuesday evening adult anxiety group 8/25. Closing intake.", author="Jonah")],
         stage="in_group", status="resolved", unread=False, assignee="Jonah",
         fields={"concern": v("anxiety", 0.95, "had anxiety since college"),
                 "group_preference": v("adult", 0.7, ""),
                 "insurance": v("Blue Cross PPO", 0.95, "Blue Cross PPO"),
                 "availability": v(["evenings after 6"], 0.9, "Evenings after 6"),
                 "referral_source": v("Psychology Today", 0.95, "found you on Psychology Today"),
                 "is_for_minor": v(False, 0.7, ""),
                 "urgency": v("normal", 0.8, "")}),
    conv("gt_11", "email", "Ruth Nakamura", "ruth.nakamura@example.org",
         "Parent group for a kid with separation anxiety",
         [msg("inbound", 620, "Hello, my son is 9 and has severe separation anxiety. His therapist thinks a parent group would help my husband and me handle it better at home. Do you have a parent group and when does it meet? We have Aetna. Weekends are easiest for us.")],
         fields={"concern": v("anxiety", 0.9, "separation anxiety"),
                 "group_preference": v("parent", 0.95, "parent group"),
                 "insurance": v("Aetna", 0.95, "Aetna"),
                 "availability": v(["weekends"], 0.9, "Weekends are easiest"),
                 "referral_source": v("son's therapist", 0.9, "His therapist thinks"),
                 "is_for_minor": v(False, 0.7, "parent group"),
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Ruth, thank you for reaching out. It sounds like you and your husband are really looking out for your son. We do run parent groups, and the meeting days and whether one fits your weekends are things we go over on the intake call, which is a free 15 minute call with one of our clinicians. What days and times work for you?"}),
    conv("gt_12", "sms", "Jordan Abara", "+1 (773) 555-0181",
         "Text: individual therapy only",
         [msg("inbound", 6000, "hi do you do individual therapy? i dont really want a group. i have bcbs"),
          msg("outbound", 5900, "Hi Jordan, thanks for reaching out. We are a group practice, so all of our care happens in groups rather than one to one. Psychology Today lets you filter for individual therapists who take BCBS, and if you ever want to try a group, the intake call is free. Take care.", author="Maya"),
          msg("note", 5890, "Wants individual only. Closed, pointed to directories.", author="Maya")],
         stage="closed", status="resolved", unread=False, assignee="Maya",
         fields={"concern": UNKNOWN,
                 "group_preference": UNKNOWN,
                 "insurance": v("BCBS", 0.9, "bcbs"),
                 "availability": UNKNOWN,
                 "referral_source": UNKNOWN,
                 "is_for_minor": UNKNOWN,
                 "urgency": v("low", 0.7, "")},
         tricky="asks for individual therapy only: closed by hand, not by a rule"),
    conv("gt_13", "psychology_today", "Kwame Ferreira", "kwame.ferreira@example.com",
         "Grief group after my wife passed",
         [msg("inbound", 2600, "My wife passed away in June after a long illness. I am 58 and retired so my schedule is open. I have Medicare and a supplement. A neighbor who was in your grief group recommended you."),
          msg("outbound", 2500, "Hi Kwame, I am so sorry for the loss of your wife, and thank you for reaching out. The next step is a free 15 minute intake call with one of our clinicians. Since your schedule is open, would tomorrow morning or afternoon suit you better?", author="Maya"),
          msg("note", 2490, "Referred by a former group member. Waiting on a time.", author="Maya")],
         stage="contacted", assignee="Maya", unread=False,
         fields={"concern": v("grief", 0.95, "My wife passed away"),
                 "group_preference": v("adult", 0.85, "I am 58"),
                 "insurance": v("Medicare and a supplement", 0.95, "Medicare and a supplement"),
                 "availability": v(["open"], 0.9, "my schedule is open"),
                 "referral_source": v("neighbor, former group member", 0.9, "A neighbor who was in your grief group"),
                 "is_for_minor": v(False, 0.95, "I am 58"),
                 "urgency": v("normal", 0.8, "")}),
    conv("gt_14", "instagram", "Leo Delgado", "ig:leo.delgado",
         "IG DM: 16 year old asking for himself",
         [msg("inbound", 170, "hi im 16 and i think i have depression, my parents dont really get it. can i join the teen group without them knowing? i can do after school")],
         fields={"concern": v("depression", 0.9, "i think i have depression"),
                 "group_preference": v("teen", 0.95, "teen group"),
                 "insurance": UNKNOWN,
                 "availability": v(["after school"], 0.9, "after school"),
                 "referral_source": UNKNOWN,
                 "is_for_minor": v(True, 0.97, "im 16"),
                 "urgency": v("normal", 0.7, "")},
         drafts={"reply": "Hi Leo, thank you for reaching out, that took courage. Because you are 16, a parent or guardian needs to be part of setting up the intake call, and one of our clinicians can talk with you about how to bring it up with them. If you ever feel unsafe, you can call or text 988 any time. Would you like me to have a clinician reach out?"},
         tricky="minor asking for himself: the consent flag fires"),
    conv("gt_15", "voicemail", "Beatrice Osei", "+1 (708) 555-0183",
         "Voicemail: daughter with panic attacks",
         [msg("inbound", 610, "Voicemail transcript, 9:05 pm: Hi, this is Beatrice Osei, I got your number from my daughter's school counselor. She is 17 and has been having panic attacks, she is a senior and it is really bad right now. We have Blue Cross. Please call me back at 708 555 0183, any time tomorrow.")],
         fields={"concern": v("anxiety", 0.9, "panic attacks"),
                 "group_preference": v("teen", 0.85, "She is 17"),
                 "insurance": v("Blue Cross", 0.95, "Blue Cross"),
                 "availability": v(["any time tomorrow"], 0.9, "any time tomorrow"),
                 "referral_source": v("school counselor", 0.9, "daughter's school counselor"),
                 "is_for_minor": v(True, 0.95, "She is 17"),
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Beatrice, thank you for calling about your daughter, and thank you to her school counselor for passing our number along. One of our clinicians will call you back tomorrow for a free 15 minute intake call, where you can talk through what she has been going through and the consent steps for someone under 18. If things feel unsafe before then, please call or text 988 or go to the nearest emergency room."}),
    conv("gt_16", "web_form", "Ingrid Torres", "ingrid.torres@example.com",
         "Not sure which group: burnout",
         [msg("inbound", 350, "I am not sure what I need. I am a nurse and completely burned out, crying in the car after shifts. Not really depression I think, just done. I work 12 hour shifts three days a week so my days off vary. Self pay is fine.")],
         fields={"concern": v("other", 0.7, "completely burned out"),
                 "group_preference": v("adult", 0.8, "I am a nurse"),
                 "insurance": v("self pay", 0.9, "Self pay is fine"),
                 "availability": v(["varies"], 0.8, "days off vary"),
                 "referral_source": UNKNOWN,
                 "is_for_minor": v(False, 0.85, "I am a nurse"),
                 "urgency": v("normal", 0.8, "")},
         drafts={"reply": "Hi Ingrid, thank you for reaching out, and it makes sense that you are not sure what you need yet. Working that out is exactly what the intake call is for: a free 15 minute call with one of our clinicians. Since your days off vary, send me a few dates that work and I will find a time."}),
]

TEMPLATE = {
    "key": "group_therapy",
    "name": "Group therapy practice",
    "tagline": "Inquiries from Psychology Today, the web form, Instagram, texts and voicemail",
    "example_prompt": "Group therapy practice with nine clinicians. Inquiries come from Psychology Today, our web form, Instagram, texts and voicemail.",
    "signals": [("group therapy", 5), ("therapy practice", 4), ("clinicians", 3),
                ("psychology today", 4), ("therapist", 2), ("counseling", 2),
                ("mental health", 3), ("support group", 3), ("teen group", 3), ("intake", 1)],
    "must_review": ["pricing", "medical_legal"],
    "spec": SPEC,
    "questions": QUESTIONS,
    "personas": ["Maya", "Jonah"],
    "ladders": LADDERS,
    "sample_inputs": SAMPLE_INPUTS,
    "prompt_examples": ["add a field for which group they were in before",
                        "add a view of teens waiting more than 2 days",
                        "flag anyone who mentions a court order"],
    "conversations": C,
}
