"""Home health agency: Willow Bend Home Care (fictional), Chicago's western suburbs."""
from ._common import conv, msg, v, UNKNOWN

SPEC = {
    "business": {
        "name": "Willow Bend Home Care",
        "type": "home_health",
        "summary": "Home health agency serving DuPage County and Chicago's western suburbs with companion, personal, memory and skilled nursing care at home. Free in-home assessment with a nurse.",
        "audience": "leads",
    },
    "connectors": [
        {"key": "web_form", "kind": "web_form", "label": "Request care form", "auto_connect": True},
        {"key": "care_com", "kind": "care_com", "label": "Care.com inquiries", "auto_connect": True},
        {"key": "voicemail", "kind": "voicemail", "label": "Phone and voicemail", "auto_connect": True},
        {"key": "email", "kind": "email", "label": "care@willowbendhomecare.example.com", "auto_connect": True},
        {"key": "fax", "kind": "fax", "label": "Facility referrals", "auto_connect": False},
        {"key": "sms", "kind": "sms", "label": "Office text line", "auto_connect": True},
    ],
    "fields": [
        {"key": "care_for", "label": "Care for", "type": "enum",
         "options": ["parent", "spouse", "self", "other"],
         "hint": "Who the care is for, from the writer's point of view", "show_in_list": True},
        {"key": "care_level", "label": "Care level", "type": "enum",
         "options": ["companion", "personal_care", "memory_care", "skilled_nursing"],
         "hint": "Company and errands is companion; bathing, dressing, meals is personal care; dementia or Alzheimer's is memory care; a nurse, wounds or medications is skilled nursing",
         "show_in_list": True},
        {"key": "hours_per_week", "label": "Hours per week", "type": "number",
         "hint": "Estimate from the schedule they describe; around the clock is 168"},
        {"key": "city", "label": "City", "type": "text",
         "hint": "Where the person receiving care lives"},
        {"key": "payer", "label": "Payer", "type": "enum",
         "options": ["private", "ltc_insurance", "medicaid", "va", "unknown"],
         "hint": "Private pay, a long term care policy, Medicaid or a waiver, VA benefits; unknown if only Medicare or health insurance is mentioned"},
        {"key": "start_within", "label": "Start within", "type": "enum",
         "options": ["this_week", "this_month", "later"],
         "hint": "When they want care to begin, resolved against the date sent", "show_in_list": True},
        {"key": "urgency", "label": "Urgency", "type": "enum",
         "options": ["low", "normal", "high"],
         "hint": "High means a fall, an injury, a discharge in the next day or two, or someone unsafe at home right now"},
    ],
    "stages": [
        {"key": "new", "label": "New", "tone": "brand"},
        {"key": "assessment_scheduled", "label": "Assessment scheduled", "tone": "warn"},
        {"key": "matching", "label": "Matching", "tone": "info"},
        {"key": "active", "label": "Active", "tone": "ok", "terminal": True},
        {"key": "not_a_fit", "label": "Not a fit", "tone": "neutral", "terminal": True},
    ],
    "views": [
        {"key": "inbox", "name": "All open",
         "filter": {"all": [{"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "needs_reply", "name": "Needs reply",
         "filter": {"all": [{"field": "awaiting_reply", "op": "eq", "value": True}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "starting_this_week", "name": "Starting this week",
         "filter": {"all": [{"field": "f.start_within", "op": "eq", "value": "this_week"},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "memory_care", "name": "Memory care",
         "filter": {"all": [{"field": "f.care_level", "op": "eq", "value": "memory_care"},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "medicaid", "name": "Medicaid",
         "filter": {"all": [{"field": "f.payer", "op": "eq", "value": "medicaid"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}},
        {"key": "unassigned", "name": "Unassigned",
         "filter": {"all": [{"field": "assignee", "op": "is_empty"},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}},
    ],
    "rules": [
        {"key": "priority_this_week", "name": "Starting this week goes to the top",
         "text": "Mark anyone who needs care this week as high priority",
         "when": {"all": [{"field": "f.start_within", "op": "eq", "value": "this_week"}]},
         "then": {"type": "set_priority", "value": "high"}},
        {"key": "priority_urgent", "name": "Urgent situations are urgent",
         "text": "Mark high urgency inquiries as urgent",
         "when": {"all": [{"field": "f.urgency", "op": "eq", "value": "high"}]},
         "then": {"type": "set_priority", "value": "urgent"}},
        {"key": "flag_call_today", "name": "Call today",
         "text": "Flag high urgency inquiries so someone calls today",
         "when": {"all": [{"field": "f.urgency", "op": "eq", "value": "high"}]},
         "then": {"type": "flag", "label": "Call today", "tone": "danger"}},
        {"key": "flag_medicaid", "name": "Medicaid eligibility",
         "text": "Flag Medicaid inquiries so program eligibility gets checked",
         "when": {"all": [{"field": "f.payer", "op": "eq", "value": "medicaid"}]},
         "then": {"type": "flag", "label": "Check program eligibility", "tone": "info"}},
    ],
    "approval_policy": {"routine": "review", "pricing": "review",
                        "medical_legal": "review", "distress": "review"},
    "tone": {"voice": "warm", "length": "short", "signoff": "Rosa at Willow Bend Home Care",
             "presets": [
                 {"label": "Answer their question", "instruction": "Answer the question they just asked, gently"},
                 {"label": "Offer an assessment", "instruction": "Offer a free in-home assessment with a nurse and ask which days work"},
                 {"label": "Ask about care needs", "instruction": "Ask who the care is for, what kind of help they need, and when they want to start"},
                 {"label": "Check in", "instruction": "Check in kindly and ask whether they would still like to talk"}]},
    "agent": {"name": "Rosa", "persona": "Care coordinator at a home health agency",
              "intro": "I read every family's message, pull out what matters, and draft a gentle first reply for you to approve."},
    "playbook": "- The first step is always a free in-home assessment with one of our nurses.\n- Never quote hourly rates in writing; rates are discussed at the assessment.\n- Every caregiver is background checked, trained and insured, and families meet their caregiver before care starts.\n- Never say whether Medicare or Medicaid will cover care; that is decided by the program.",
    "guardrails": [
        {"key": "no_rates_or_coverage", "text": "Never quote rates in writing or say what Medicare, Medicaid or an insurer will cover.",
         "enforce": "never_promise"},
        {"key": "safety_now", "text": "A fall, injury or unsafe situation today goes to the on-call nurse now, not a drafted reply.",
         "enforce": "escalate"},
    ],
}

QUESTIONS = [
    {"id": "sources", "kind": "tiles", "multi": True,
     "prompt": "Where do families and referrals come in?",
     "why": "Each one becomes a connector and a way to filter.",
     "options": ["web_form", "care_com", "voicemail", "email", "fax", "sms"],
     "default": ["web_form", "care_com", "voicemail", "email", "sms"], "patch": "set_connectors"},
    {"id": "business_name", "kind": "text", "prompt": "What is the agency called?",
     "why": "It goes on every reply.", "default": "Willow Bend Home Care", "patch": "set_business_name"},
    {"id": "extract_fields", "kind": "chips", "multi": True,
     "prompt": "What should I pull out of every new inquiry?",
     "why": "Each one becomes a column you can sort and filter by.",
     "options": [["care_for", "Who the care is for"], ["care_level", "Kind of care"],
                 ["hours_per_week", "Hours per week"], ["city", "City"],
                 ["payer", "How they will pay"], ["start_within", "When they want to start"],
                 ["urgency", "How urgent"]],
     "default": ["care_for", "care_level", "hours_per_week", "city", "payer", "start_within",
                 "urgency"], "patch": "pick_fields"},
    {"id": "slices", "kind": "chips", "multi": True,
     "prompt": "Which views do you want on the front of the inbox?",
     "why": "Views are saved filters. You can add more later by typing.",
     "options": [["starting_this_week", "Starting this week"], ["memory_care", "Memory care"],
                 ["medicaid", "Medicaid"], ["unassigned", "Unassigned"]],
     "default": ["starting_this_week", "memory_care"], "patch": "pick_views"},
    {"id": "approval", "kind": "chips", "multi": False,
     "prompt": "What may I send without you looking first?",
     "why": "Anything about rates, coverage or a family in distress always waits for you.",
     "options": [["routine", "Acknowledgements and scheduling"], ["none", "Nothing, I review every reply"]],
     "default": "none", "patch": "set_approval"},
    {"id": "tone", "kind": "chips", "multi": False, "prompt": "How should replies sound?",
     "why": "Sets the voice for every draft.",
     "options": [["warm", "Warm"], ["plain", "Plain"], ["formal", "Formal"]],
     "default": "warm", "patch": "set_tone"},
]

LADDERS = {
    "reply": [
        (("fell", "fall", "hurt", "injured", "unsafe", "emergency", "right now", "today"),
         "I am so sorry, and thank you for reaching out. If anyone is hurt or unsafe right now, please call 911. Our on-call nurse will call you as soon as possible to talk through what is needed today."),
        (("how much", "rate", "rates", "cost", "price", "per hour", "hourly", "afford", "charge"),
         "Thank you for reaching out. Rates depend on the kind of care and the schedule, so we go over them at the free in-home assessment, where one of our nurses also gets to know your family. What days work for a visit?"),
        (("medicare", "medicaid", "insurance", "cover", "covered", "va benefits", "aid and attendance", "waiver"),
         "Thank you for asking. Whether a program covers care is decided by the program itself, so I cannot promise that, but the free in-home assessment gives you a clear picture of what care would look like, and we can walk through the paperwork together. What days work for a visit?"),
        (("dementia", "alzheimer", "memory", "wandering", "confused", "sundown"),
         "Thank you for reaching out, and I know how much it takes to care for someone with memory loss. Our caregivers are trained in memory care, and the first step is a free in-home assessment with one of our nurses. What days work for a visit?"),
        (("overnight", "nights", "24 hour", "live-in", "live in", "around the clock"),
         "Thank you for reaching out. We do arrange overnight and around the clock care, and the schedule is built around your family at the free in-home assessment. What days work for a nurse to visit?"),
        (("background", "screened", "checked", "trust", "safe", "meet the caregiver"),
         "Thank you for asking. Every caregiver is background checked, trained and insured before they meet a family, and you meet your caregiver before care starts. The first step is a free in-home assessment with one of our nurses. What days work for a visit?"),
    ],
    "fallback": "Thank you for reaching out to Willow Bend Home Care, {who}. I would love to learn more about what your family needs. The first step is a free in-home assessment with one of our nurses. What days work for a visit?",
    "check_in": "Hi {who}, checking in to see whether you would still like to set up a free in-home assessment. Reply here any time and I will find a day that works for your family.",
    "booking": "Hi {who}, here is the link to book your free in-home assessment. Pick any time that suits your family, and reply here if none of them work.",
    "thanks": "Thank you, {who}. We will be in touch soon, and you can reply here with any questions.",
    "decline": "Thank you for reaching out, {who}. Unfortunately this is not care we are able to provide, but your county's Area Agency on Aging can point you to agencies that can.",
    "ask_missing": "Thanks {who}. So I can find the right caregiver, could you tell me who the care is for, what kind of help they need, and roughly how many hours a week?",
}

SAMPLE_INPUTS = [
    {"label": "Sample Care.com inquiry", "source": "care_com",
     "text": "From: Care.com <inquiries@care.example.com>\nSubject: New senior care inquiry\n\nName: Elena Moreau\nCare needed: Senior care\nMessage: My father is 88 and lives alone in Westmont. He is getting forgetful and left the stove on twice last month. We are looking for someone weekday mornings, maybe 4 hours a day, to help with breakfast, his pills and keeping an eye on him. We would pay privately. Hoping to start in the next couple of weeks."},
    {"label": "Sample voicemail transcript", "source": "voicemail",
     "text": "Voicemail transcript, 7:48 pm: Hi, this is Marcus Delgado, I am calling about my wife. She had a stroke in June and she is home now but she needs help getting in and out of the shower and with her meals. We are in Lombard. Her doctor mentioned a home health nurse might be covered by Medicare, I am not sure. Please call me back at 630 555 0158."},
]

C = [
    conv("hh_01", "web_form", "Maya Lindqvist", "maya.lindqvist@example.com",
         "Mom home from rehab Friday, needs help with bathing and meals",
         [msg("inbound", 160, "My mother comes home from rehab on Friday after a hip replacement. She lives alone in Naperville and will need help with bathing, getting dressed and meals, probably 4 hours a day on weekdays. We would pay privately. Can someone start Friday?")],
         priority="high",
         fields={"care_for": v("parent", 0.97, "My mother"),
                 "care_level": v("personal_care", 0.9, "help with bathing, getting dressed and meals"),
                 "hours_per_week": v(20, 0.8, "4 hours a day on weekdays"),
                 "city": v("Naperville", 0.95, "lives alone in Naperville"),
                 "payer": v("private", 0.95, "pay privately"),
                 "start_within": v("this_week", 0.9, "comes home from rehab on Friday"),
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Maya, thank you for reaching out, and I hope your mother's recovery is going well. Help with bathing, dressing and meals on weekdays is care we arrange often. The first step is a free in-home assessment with one of our nurses, and with Friday coming up I would like to set that up as soon as possible. What day and time work for you and your mother?"}),
    conv("hh_02", "care_com", "Omar Haddad", "care_com:omar.haddad",
         "Care.com: overnight care for my wife with Alzheimer's",
         [msg("inbound", 340, "Hi, I am looking for overnight care for my wife. She has Alzheimer's and has started getting up and wandering at night, and I am not sleeping. We are in Wheaton. I am thinking 3 nights a week to start. We have a long term care policy through her old employer. Sometime in September would be fine.")],
         fields={"care_for": v("spouse", 0.97, "my wife"),
                 "care_level": v("memory_care", 0.95, "She has Alzheimer's"),
                 "hours_per_week": v(30, 0.4, "3 nights a week"),
                 "city": v("Wheaton", 0.95, "We are in Wheaton"),
                 "payer": v("ltc_insurance", 0.9, "long term care policy"),
                 "start_within": v("later", 0.7, "Sometime in September"),
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Omar, thank you for reaching out, and I hear how tiring the nights have been. We do arrange overnight care, and our caregivers are trained in memory care, so your wife would have someone with her while you rest. The first step is a free in-home assessment with one of our nurses, and we can look at the long term care policy together at the visit. What days work for you?"},
         tricky="spouse asking about overnight memory care"),
    conv("hh_03", "sms", "Ingrid Sato", "+1 (630) 555-0119",
         "Text: mother fell this morning, needs someone today",
         [msg("inbound", 18, "Hi this is Ingrid Sato, I take care of my mother at home in Elmhurst and she fell in the bathroom this morning. She says she is ok but I cant lift her on my own and I have to be at work. I need someone here today, can you help??")],
         priority="urgent",
         fields={"care_for": v("parent", 0.97, "my mother"),
                 "care_level": v("personal_care", 0.5, "cant lift her on my own"),
                 "hours_per_week": UNKNOWN,
                 "city": v("Elmhurst", 0.95, "at home in Elmhurst"),
                 "payer": UNKNOWN,
                 "start_within": v("this_week", 0.95, "I need someone here today"),
                 "urgency": v("high", 0.95, "she fell in the bathroom this morning")},
         drafts={"reply": "Hi Ingrid, I am so sorry, and thank you for reaching out. If your mother is hurt or you cannot get her up safely, please call 911 now. Our on-call nurse will call you right away to talk through what is needed today."},
         tricky="a fall at home today: escalate to the on-call nurse, distress stays in review"),
    conv("hh_04", "email", "Felix Varga", "felix.varga@example.com",
         "Is Dad eligible for Medicare home health?",
         [msg("inbound", 470, "Hello, my father is 82 and was just discharged from Lakeside Regional after pneumonia. His doctor said he should have a nurse come by to check on him and manage his medications for a few weeks. He is in Arlington Heights. Is Dad eligible for Medicare home health, and do you take it? I would like to get this going this month if possible.")],
         fields={"care_for": v("parent", 0.97, "my father"),
                 "care_level": v("skilled_nursing", 0.9, "have a nurse come by to check on him and manage his medications"),
                 "hours_per_week": UNKNOWN,
                 "city": v("Arlington Heights", 0.95, "Arlington Heights"),
                 "payer": v("unknown", 0.6, "Is Dad eligible for Medicare home health"),
                 "start_within": v("this_month", 0.85, "this month if possible"),
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Felix, thank you for reaching out, and I hope your father is feeling better after the hospital. Whether Medicare covers home health is decided by the program based on his doctor's orders, so I cannot promise that here, but the first step either way is a free in-home assessment with one of our nurses, and we can walk through the paperwork together. What days work for a visit?"},
         tricky="coverage question: medical_legal, stays in review"),
    conv("hh_05", "care_com", "Claire Moreau", "care_com:claire.moreau",
         "Care.com: companion for my mom a few afternoons a week",
         [msg("inbound", 780, "My mom is 78 and doing fine physically but she is lonely since my dad passed and I worry about her being alone all day. Looking for someone to visit a few afternoons a week, maybe 3 hours each, to chat, take her to the store, that kind of thing. She is in Glen Ellyn. No rush, sometime in the next month or so. We would pay out of pocket.")],
         fields={"care_for": v("parent", 0.97, "My mom"),
                 "care_level": v("companion", 0.9, "to chat, take her to the store"),
                 "hours_per_week": v(9, 0.5, "a few afternoons a week, maybe 3 hours each"),
                 "city": v("Glen Ellyn", 0.95, "Glen Ellyn"),
                 "payer": v("private", 0.9, "pay out of pocket"),
                 "start_within": v("later", 0.8, "sometime in the next month or so"),
                 "urgency": v("low", 0.85, "No rush")},
         drafts={"reply": "Hi Claire, thank you for reaching out, and I am sorry about your dad. A few afternoons a week of company and errands is exactly the kind of care we arrange, and we take care to match a caregiver your mom will enjoy spending time with. The first step is a free in-home assessment with one of our nurses. What days work for a visit?"}),
    conv("hh_06", "web_form", "Rohan Patel", "rohan.patel@example.com",
         "On Medicaid, need help mornings after a stroke",
         [msg("inbound", 610, "I had a stroke in May and I am home now but my left side is weak. I need help with showering, getting dressed and cooking, probably a couple hours every morning. I live by myself in Aurora. I am on Medicaid and my caseworker said to ask about the waiver program. I would like to start as soon as possible this month.")],
         fields={"care_for": v("self", 0.9, "I live by myself"),
                 "care_level": v("personal_care", 0.9, "help with showering, getting dressed and cooking"),
                 "hours_per_week": v(14, 0.5, "a couple hours every morning"),
                 "city": v("Aurora", 0.95, "Aurora"),
                 "payer": v("medicaid", 0.95, "I am on Medicaid"),
                 "start_within": v("this_month", 0.6, "as soon as possible this month"),
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Rohan, thank you for reaching out, and I am glad you are home. Help with mornings is something we arrange often. Whether the waiver program covers care is decided by the program, so I cannot promise that here, but the first step either way is a free in-home assessment with one of our nurses, and we can go over the paperwork together. What days work for a visit?"},
         tricky="Medicaid: the eligibility flag fires, coverage stays in review"),
    conv("hh_07", "fax", "Nadia Abara", "fax:+1 (847) 555-0140",
         "Fax: discharge referral, Ms. Okafor, home Thursday",
         [msg("inbound", 95, "REFERRAL FOR HOME CARE SERVICES\nFrom: Nadia Abara, RN, Discharge Planning, Lakeside Regional Medical Center\nPatient: Beatrice Okafor, 84\nDischarge: Thursday 8/27 to home, daughter is primary contact (Teresa Okafor, 630 555 0151)\nAddress: Downers Grove\nNeeds: personal care assistance, 6 hrs/day, 7 days/wk; wound check by RN twice weekly\nPayer: VA Aid and Attendance, late spouse was a veteran\nPlease confirm receipt and contact the daughter today.")],
         priority="urgent",
         fields={"care_for": v("other", 0.5, "Discharge Planning"),
                 "care_level": v("skilled_nursing", 0.7, "wound check by RN twice weekly"),
                 "hours_per_week": v(42, 0.9, "6 hrs/day, 7 days/wk"),
                 "city": v("Downers Grove", 0.95, "Downers Grove"),
                 "payer": v("va", 0.9, "VA Aid and Attendance"),
                 "start_within": v("this_week", 0.95, "Discharge: Thursday 8/27"),
                 "urgency": v("high", 0.9, "contact the daughter today")},
         drafts={"reply": "Hi Nadia, thank you for the referral, received. I will call Teresa today to set up a free in-home assessment with one of our nurses as close to Thursday's discharge as we can manage, and I will confirm back to you once it is on the calendar."},
         tricky="facility discharge planner fax"),
    conv("hh_08", "sms", "Leo Rinaldi", "+1 (331) 555-0126",
         "How much per hour for a companion?",
         [msg("inbound", 125, "Hi, how much do you charge per hour for a companion for my dad in Lombard? Just a few hours a week, no medical stuff. Not in a hurry.")],
         fields={"care_for": v("parent", 0.97, "my dad"),
                 "care_level": v("companion", 0.9, "a companion"),
                 "hours_per_week": UNKNOWN,
                 "city": v("Lombard", 0.95, "Lombard"),
                 "payer": UNKNOWN,
                 "start_within": v("later", 0.7, "Not in a hurry"),
                 "urgency": v("low", 0.85, "Not in a hurry")},
         drafts={"reply": "Hi Leo, thank you for reaching out. Rates depend on the kind of care and the schedule, so we go over them at the free in-home assessment, where one of our nurses also gets to know your dad. What days work for a visit?"},
         tricky="pricing: never quote rates in writing, stays in review"),
    conv("hh_09", "voicemail", "Wren Quinn", "+1 (630) 555-0166",
         "Voicemail: husband home Saturday after heart surgery",
         [msg("inbound", 1500, "Voicemail transcript, 5:40 pm: Hi, this is Wren Quinn, my husband Theo is coming home from Lakeside Regional on Saturday after heart surgery. The hospital said he will need a nurse to check on him and help with his medications and the wound. We are in Naperville. We have his health insurance but I do not know what it covers, we can pay ourselves if we need to. Please call me back at 630 555 0166."),
          msg("outbound", 1400, "Hi Wren, thank you for calling, and I hope Theo's surgery went well. The first step is a free in-home assessment with one of our nurses, and with Saturday coming up I would like to schedule that right away. Would Thursday morning or afternoon work?", author="Rosa"),
          msg("inbound", 1200, "Thursday at 2 is good. Thank you."),
          msg("outbound", 1100, "Perfect, Wren. Our nurse Daniel will be at your home Thursday at 2. A confirmation is on its way.", author="Rosa"),
          msg("note", 1090, "Assessment Thursday 2pm with Daniel. Ask for the discharge summary and medication list.", author="Rosa"),
          msg("inbound", 200, "Do I need to have anything ready for Thursday?")],
         stage="assessment_scheduled", assignee="Rosa", priority="high",
         fields={"care_for": v("spouse", 0.97, "my husband"),
                 "care_level": v("skilled_nursing", 0.9, "need a nurse to check on him and help with his medications and the wound"),
                 "hours_per_week": UNKNOWN,
                 "city": v("Naperville", 0.95, "We are in Naperville"),
                 "payer": v("private", 0.5, "we can pay ourselves if we need to"),
                 "start_within": v("this_week", 0.9, "coming home from Lakeside Regional on Saturday"),
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Wren, just the discharge papers and his medication list if you have them, and any questions you want to ask. Daniel will take it from there. See you Thursday at 2."}),
    conv("hh_10", "email", "Sofia Delgado", "sofia.delgado@example.com",
         "Referral from Dr. Ivers, memory care for my mother",
         [msg("inbound", 4300, "Hello, Dr. Ivers at Prairie Neurology suggested we contact you. My mother has moderate dementia and my father cannot manage on his own anymore. They live in Wheaton. We are thinking weekday mornings and afternoons, around 30 hours a week, starting before the end of the month. She has a long term care policy through her old school district."),
          msg("outbound", 4200, "Hi Sofia, thank you for reaching out, and thank you to Dr. Ivers. Our caregivers are trained in memory care, and the first step is a free in-home assessment with one of our nurses so we can meet your parents and plan the week. What days work for a visit?", author="Daniel"),
          msg("inbound", 4000, "Any morning this week works, my father is always home."),
          msg("outbound", 3900, "Monday at 10am then. I will bring the long term care claim forms so we can look at them together.", author="Daniel"),
          msg("note", 1400, "Assessment done Monday. Mother is pleasant, some sundowning after 3pm. Father wants a caregiver who is patient and speaks slowly. Matching: Priya or Elena.", author="Daniel")],
         stage="matching", assignee="Daniel", unread=False,
         fields={"care_for": v("parent", 0.97, "My mother"),
                 "care_level": v("memory_care", 0.95, "moderate dementia"),
                 "hours_per_week": v(30, 0.9, "around 30 hours a week"),
                 "city": v("Wheaton", 0.95, "They live in Wheaton"),
                 "payer": v("ltc_insurance", 0.9, "long term care policy"),
                 "start_within": v("this_month", 0.85, "before the end of the month"),
                 "urgency": v("normal", 0.6, "")}),
    conv("hh_11", "care_com", "Diego Castillo", "care_com:diego.castillo",
         "Care.com: around the clock care for both my parents",
         [msg("inbound", 9000, "Looking for a live-in caregiver for both my parents in Hinsdale. Dad has Parkinson's and Mom has early dementia. They need someone there around the clock. We can pay privately. Hoping to start in September."),
          msg("outbound", 8900, "Hi Diego, thank you for reaching out. Around the clock care for both parents is something we can plan around your family, and the first step is a free in-home assessment with one of our nurses. What days work for a visit?", author="Rosa"),
          msg("inbound", 8600, "Thanks Rosa. Can I get back to you next week? We are also touring a couple of assisted living places."),
          msg("outbound", 8500, "Of course, Diego. Take the time you need, and reply here whenever you are ready.", author="Rosa"),
          msg("inbound", 2000, "We have decided on assisted living for both of them. Thank you for being so quick to respond."),
          msg("outbound", 1900, "Thank you for letting me know, Diego, and I wish your parents a smooth move. If anything changes, we are here.", author="Rosa")],
         stage="not_a_fit", status="resolved", unread=False, assignee="Rosa",
         fields={"care_for": v("parent", 0.97, "both my parents"),
                 "care_level": v("memory_care", 0.6, "Mom has early dementia"),
                 "hours_per_week": v(168, 0.6, "around the clock"),
                 "city": v("Hinsdale", 0.95, "Hinsdale"),
                 "payer": v("private", 0.9, "pay privately"),
                 "start_within": v("later", 0.8, "Hoping to start in September"),
                 "urgency": v("normal", 0.6, "")}),
    conv("hh_12", "web_form", "Harper Ivers", "harper.ivers@example.com",
         "Personal care for my mother, VA Aid and Attendance",
         [msg("inbound", 20000, "My mother's late husband was a veteran and I was told she may qualify for VA Aid and Attendance. She needs help bathing and with meals, about 20 hours a week. She lives in Lisle. We would like to start this month."),
          msg("outbound", 19900, "Hi Harper, thank you for reaching out. Whether VA Aid and Attendance covers care is decided by the VA, so I cannot promise that, but we can walk through the paperwork together at the free in-home assessment. What days work for a nurse to visit?", author="Daniel"),
          msg("inbound", 19600, "Thursday morning works."),
          msg("outbound", 19500, "Thursday at 9am it is. A confirmation is on its way.", author="Daniel"),
          msg("note", 12000, "Assessment done. Matched with Lena, 4 hrs Mon to Fri mornings. VA paperwork submitted, family paying privately until it is decided.", author="Daniel"),
          msg("inbound", 3000, "Lena has been wonderful with my mother. Thank you both."),
          msg("outbound", 2900, "That is lovely to hear, Harper. Thank you for telling me, and reply here any time.", author="Daniel")],
         stage="active", status="resolved", unread=False, assignee="Daniel",
         fields={"care_for": v("parent", 0.97, "My mother"),
                 "care_level": v("personal_care", 0.9, "help bathing and with meals"),
                 "hours_per_week": v(20, 0.9, "about 20 hours a week"),
                 "city": v("Lisle", 0.95, "Lisle"),
                 "payer": v("va", 0.9, "VA Aid and Attendance"),
                 "start_within": v("this_month", 0.85, "start this month"),
                 "urgency": v("normal", 0.6, "")}),
    conv("hh_13", "sms", "Yusuf Osei", "+1 (708) 555-0181",
         "Text: mom's caregiver quit, need someone this week",
         [msg("inbound", 75, "Hi, my mom's caregiver from another agency quit with no notice. She is in Villa Park, needs someone weekdays 9 to 1 for meals, med reminders and light housekeeping. Need someone starting this week if at all possible. We pay privately")],
         priority="high",
         fields={"care_for": v("parent", 0.97, "my mom"),
                 "care_level": v("personal_care", 0.85, "meals, med reminders and light housekeeping"),
                 "hours_per_week": v(20, 0.85, "weekdays 9 to 1"),
                 "city": v("Villa Park", 0.95, "Villa Park"),
                 "payer": v("private", 0.95, "We pay privately"),
                 "start_within": v("this_week", 0.9, "starting this week"),
                 "urgency": v("normal", 0.6, "")},
         drafts={"reply": "Hi Yusuf, thank you for reaching out, and I am sorry you were left without notice. Weekday mornings for meals, medication reminders and light housekeeping is something we arrange often. The first step is a free in-home assessment with one of our nurses, and given the week I would like to set that up right away. What day and time work for you and your mom?"}),
    conv("hh_14", "voicemail", "Amara Abara", "+1 (630) 555-0172",
         "Voicemail: dad with COPD, nurse visits a couple of times a week",
         [msg("inbound", 1500, "Voicemail transcript, 11:05 am: Hi, my name is Amara Abara, calling about my father. He has COPD and is on oxygen, and his pulmonologist wants a nurse to come by a couple of times a week to check his oxygen and his meds. We are in Oak Brook. He has a long term care policy, I think it covers home nursing but I am not sure. We would like to start in September. My number is 630 555 0172."),
          msg("outbound", 1400, "Hi Amara, thank you for calling, and thank you for looking after your father. Nurse visits a couple of times a week to check his oxygen and medications is care we arrange, and the first step is a free in-home assessment with one of our nurses. Would Friday morning work for you and your father?", author="Daniel"),
          msg("inbound", 1100, "Friday at 10 is good. He will be home all day."),
          msg("outbound", 1000, "Friday at 10am it is, Amara. A confirmation is on its way, and please have his long term care policy handy so we can look at it together.", author="Daniel"),
          msg("note", 990, "Assessment Friday 10am. Ask for the pulmonologist's orders and the policy number.", author="Daniel")],
         stage="assessment_scheduled", assignee="Daniel", unread=False,
         fields={"care_for": v("parent", 0.97, "my father"),
                 "care_level": v("skilled_nursing", 0.9, "a nurse to come by a couple of times a week"),
                 "hours_per_week": UNKNOWN,
                 "city": v("Oak Brook", 0.95, "Oak Brook"),
                 "payer": v("ltc_insurance", 0.9, "long term care policy"),
                 "start_within": v("later", 0.6, "start in September"),
                 "urgency": v("normal", 0.6, "")}),
    conv("hh_15", "email", "Victor Nakamura", "victor.nakamura@example.org",
         "Are your caregivers background checked?",
         [msg("inbound", 520, "Hi, I am looking at a few agencies for my mother in Glen Ellyn. She needs help a few hours a day with bathing and meals, maybe 15 hours a week. Before I go any further: are your caregivers background checked, and do we get to meet the person before they start? No rush, we are planning for October. We would pay out of pocket.")],
         fields={"care_for": v("parent", 0.97, "my mother"),
                 "care_level": v("personal_care", 0.9, "help a few hours a day with bathing and meals"),
                 "hours_per_week": v(15, 0.85, "maybe 15 hours a week"),
                 "city": v("Glen Ellyn", 0.95, "Glen Ellyn"),
                 "payer": v("private", 0.9, "pay out of pocket"),
                 "start_within": v("later", 0.9, "planning for October"),
                 "urgency": v("low", 0.85, "No rush")},
         drafts={"reply": "Hi Victor, thank you for asking, and it is a good question. Every caregiver is background checked, trained and insured before they meet a family, and yes, you meet your caregiver before care starts. The first step, whenever you are ready, is a free in-home assessment with one of our nurses. What days work for a visit?"}),
    conv("hh_16", "care_com", "Noah Kim", "care_com:noah.kim",
         "Care.com: help for myself after back surgery",
         [msg("inbound", 7000, "I am having back surgery on September 10 and will need help for a couple of weeks after: showering, meals, driving to PT. I live alone in Rockford. Maybe 20 hours a week. I will pay privately."),
          msg("outbound", 6900, "Hi Noah, thank you for reaching out. Unfortunately Rockford is outside the area we serve, so this is not care we are able to provide, but your county's Area Agency on Aging can point you to agencies near you. I hope the surgery goes smoothly.", author="Rosa")],
         stage="not_a_fit", status="resolved", unread=False, assignee="Rosa",
         fields={"care_for": v("self", 0.9, "I live alone"),
                 "care_level": v("personal_care", 0.85, "showering, meals, driving to PT"),
                 "hours_per_week": v(20, 0.8, "Maybe 20 hours a week"),
                 "city": v("Rockford", 0.95, "Rockford"),
                 "payer": v("private", 0.9, "pay privately"),
                 "start_within": v("later", 0.85, "September 10"),
                 "urgency": v("normal", 0.6, "")},
         tricky="outside the service area"),
    conv("hh_17", "web_form", "Tom Ferreira", "tom.ferreira@example.com",
         "Companion for Dad, weekday afternoons",
         [msg("inbound", 30000, "My dad is 85, in Downers Grove, still sharp but not safe to drive anymore. Looking for someone weekday afternoons, 1 to 5, for company, errands and lunch. He is a proud guy so it needs to be the right person. Private pay. Would like to start in a couple of weeks."),
          msg("outbound", 29900, "Hi Tom, thank you for reaching out. Company, errands and lunch on weekday afternoons is something we arrange often, and we take care to match a caregiver your dad will actually enjoy having around. The first step is a free in-home assessment with one of our nurses. What days work for a visit?", author="Rosa"),
          msg("inbound", 29500, "Next Tuesday morning, he is best in the mornings."),
          msg("outbound", 29400, "Tuesday at 10am. A confirmation is on its way.", author="Rosa"),
          msg("note", 21000, "Assessment done. Dad likes baseball and the newspaper. Matched with Marcus, starts Monday the 17th, Mon to Fri 1 to 5.", author="Rosa"),
          msg("inbound", 5000, "Marcus and Dad are getting along great. Thanks for taking the time to get it right."),
          msg("outbound", 4900, "That makes my day, Tom. Thank you for telling me, and reply here any time.", author="Rosa")],
         stage="active", status="resolved", unread=False, assignee="Rosa",
         fields={"care_for": v("parent", 0.97, "My dad"),
                 "care_level": v("companion", 0.9, "for company, errands and lunch"),
                 "hours_per_week": v(20, 0.9, "weekday afternoons, 1 to 5"),
                 "city": v("Downers Grove", 0.95, "Downers Grove"),
                 "payer": v("private", 0.95, "Private pay"),
                 "start_within": v("this_month", 0.8, "start in a couple of weeks"),
                 "urgency": v("normal", 0.6, "")}),
]

TEMPLATE = {
    "key": "home_health",
    "name": "Home health agency",
    "tagline": "Family inquiries from the web form, Care.com, phone, email and texts, plus facility referrals",
    "example_prompt": "Home health agency. Families reach us by phone, email, Care.com and a web form; facilities send referrals by fax.",
    "signals": [("home health agency", 6), ("home care agency", 6), ("families reach", 3), ("aging", 2), ("home health", 5), ("home care", 5), ("caregiver", 3), ("care.com", 4),
                ("in-home", 3), ("in home", 2), ("elderly", 2), ("senior", 2),
                ("dementia", 2), ("memory care", 3)],
    "must_review": ["pricing", "medical_legal"],
    "spec": SPEC,
    "questions": QUESTIONS,
    "personas": ["Rosa", "Daniel"],
    "ladders": LADDERS,
    "sample_inputs": SAMPLE_INPUTS,
    "prompt_examples": ["add a field for whether there is a hospital bed at home",
                        "add a view of families starting this week who pay privately",
                        "flag anyone mentioning hospice"],
    "conversations": C,
}
