"""Legal aid nonprofit: Prairie Justice Legal Aid (fictional), downstate Illinois."""
from ._common import conv, msg, v, UNKNOWN

SPEC = {
    "business": {
        "name": "Prairie Justice Legal Aid",
        "type": "legal_aid",
        "summary": "Nonprofit legal aid office taking eviction, benefits, family, consumer debt and employment matters for low-income people across seven counties. Services are free.",
        "audience": "clients",
    },
    "connectors": [
        {"key": "voicemail", "kind": "voicemail", "label": "Hotline transcripts", "auto_connect": True},
        {"key": "web_form", "kind": "web_form", "label": "Online intake form", "auto_connect": True},
        {"key": "email", "kind": "email", "label": "intake@prairiejustice.example.org", "auto_connect": True},
        {"key": "sms", "kind": "sms", "label": "Intake text line", "auto_connect": True},
        {"key": "referral", "kind": "referral", "label": "Partner referrals", "auto_connect": False},
    ],
    "fields": [
        {"key": "county", "label": "County", "type": "text",
         "hint": "County they live in, without the word County", "show_in_list": True},
        {"key": "issue", "label": "Issue", "type": "enum",
         "options": ["eviction", "benefits", "family", "consumer_debt", "employment", "other"],
         "hint": "Eviction and lockouts; benefits like SNAP, Medicaid, unemployment, TANF; family includes custody and divorce; consumer debt includes collectors and repossession; employment includes unpaid wages and firing",
         "show_in_list": True},
        {"key": "household_size", "label": "Household size", "type": "number",
         "hint": "People living in the home including the person writing"},
        {"key": "monthly_income", "label": "Monthly income", "type": "number",
         "hint": "Household income per month in dollars; 0 if they say they have none"},
        {"key": "language", "label": "Language", "type": "enum",
         "options": ["english", "spanish", "polish", "other"],
         "hint": "The language they wrote in or asked for"},
        {"key": "court_date", "label": "Court date", "type": "date",
         "hint": "Hearing or court date if there is one; resolve relative dates against today",
         "show_in_list": True},
        {"key": "urgency", "label": "Urgency", "type": "enum",
         "options": ["low", "normal", "high"],
         "hint": "High for a hearing or deadline within two weeks, a lockout, or children at risk"},
    ],
    "stages": [
        {"key": "new", "label": "New", "tone": "brand"},
        {"key": "screening", "label": "Screening", "tone": "info"},
        {"key": "accepted", "label": "Accepted", "tone": "ok"},
        {"key": "referred_out", "label": "Referred out", "tone": "neutral", "terminal": True},
        {"key": "closed", "label": "Closed", "tone": "neutral", "terminal": True},
    ],
    "views": [
        {"key": "inbox", "name": "All open",
         "filter": {"all": [{"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "needs_reply", "name": "Needs reply",
         "filter": {"all": [{"field": "awaiting_reply", "op": "eq", "value": True}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "court_soon", "name": "Court within 7 days",
         "filter": {"all": [{"field": "f.court_date", "op": "within_days", "value": 7},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "f.court_date", "dir": "asc"}, "pinned": True},
        {"key": "evictions", "name": "Evictions",
         "filter": {"all": [{"field": "f.issue", "op": "eq", "value": "eviction"},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "spanish", "name": "Spanish",
         "filter": {"all": [{"field": "f.language", "op": "eq", "value": "spanish"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}},
        {"key": "unassigned", "name": "Unassigned",
         "filter": {"all": [{"field": "assignee", "op": "is_empty"},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}},
    ],
    "rules": [
        {"key": "court_urgent", "name": "Court within a week is urgent",
         "text": "Mark anyone with a court date within 7 days as urgent",
         "when": {"all": [{"field": "f.court_date", "op": "within_days", "value": 7}]},
         "then": {"type": "set_priority", "value": "urgent"}},
        {"key": "court_flag", "name": "Court soon",
         "text": "Flag anyone with a court date within 7 days",
         "when": {"all": [{"field": "f.court_date", "op": "within_days", "value": 7}]},
         "then": {"type": "flag", "label": "Court soon", "tone": "danger"}},
        {"key": "spanish_flag", "name": "Spanish speaker",
         "text": "Flag anyone who writes in or asks for Spanish",
         "when": {"all": [{"field": "f.language", "op": "eq", "value": "spanish"}]},
         "then": {"type": "flag", "label": "Spanish", "tone": "info"}},
        {"key": "income_check", "name": "Income may be over the limit",
         "text": "Flag anyone reporting monthly income over 4000",
         "when": {"all": [{"field": "f.monthly_income", "op": "gt", "value": 4000}]},
         "then": {"type": "flag", "label": "Check income eligibility", "tone": "warn"}},
    ],
    "approval_policy": {"routine": "review", "pricing": "review",
                        "medical_legal": "review", "distress": "review"},
    "tone": {"voice": "plain", "length": "short", "signoff": "Elena at Prairie Justice Legal Aid",
             "presets": [
                 {"label": "Acknowledge", "instruction": "Acknowledge what they wrote, say services are free and that someone will call"},
                 {"label": "Go to court", "instruction": "Tell them to go to their hearing no matter what and bring every paper, and that intake will call"},
                 {"label": "Ask for basics", "instruction": "Ask for county, what the problem is about, household size, income and any court date"},
                 {"label": "Refer out", "instruction": "Explain kindly that this is not a matter we take and point to the county bar referral line"}]},
    "agent": {"name": "Elena", "persona": "Intake specialist",
              "intro": "I read every call transcript, form and message, pull out county, issue, income and any court date, and draft a plain reply for staff to approve."},
    "playbook": "- Our services are free; there is never a charge.\n- Eligibility depends on income and county. An attorney or paralegal decides, never intake.\n- If a hearing is within 7 days, tell the person to go to court even if we have not confirmed we can help.\n- Never give legal advice in writing.\n- Interpreters are available for Spanish and Polish.\n- Intake calls back within two business days, same day when a court date is within 7 days.",
    "guardrails": [
        {"key": "no_immigration", "text": "Immigration status is discussed by an attorney in a confidential conversation, never in writing.",
         "enforce": "refuse_field",
         "patterns": ["immigration status", "citizenship", "undocumented", "visa status"],
         "reason": "immigration status",
         "refusal": "I cannot add that. Immigration status is something an attorney asks about in a confidential conversation, never in writing. I can add fields like county, issue, court date or household size."},
        {"key": "no_advice", "text": "Never state whether someone qualifies or what will happen in their case.",
         "enforce": "never_promise"},
    ],
}

QUESTIONS = [
    {"id": "sources", "kind": "tiles", "multi": True,
     "prompt": "How do people reach you?",
     "why": "Each one becomes a connector and a way to filter.",
     "options": ["voicemail", "web_form", "email", "sms", "referral"],
     "default": ["voicemail", "web_form", "email", "sms"], "patch": "set_connectors"},
    {"id": "business_name", "kind": "text", "prompt": "What is the organization called?",
     "why": "It goes on every reply.", "default": "Prairie Justice Legal Aid", "patch": "set_business_name"},
    {"id": "extract_fields", "kind": "chips", "multi": True,
     "prompt": "What should I pull out of every new intake?",
     "why": "Each one becomes a column you can sort and filter by.",
     "options": [["county", "County"], ["issue", "Type of issue"],
                 ["household_size", "Household size"], ["monthly_income", "Monthly income"],
                 ["language", "Language"], ["court_date", "Court date"], ["urgency", "Urgency"]],
     "default": ["county", "issue", "household_size", "monthly_income", "language", "court_date"],
     "patch": "pick_fields"},
    {"id": "slices", "kind": "chips", "multi": True,
     "prompt": "Which views do you want on the front of the inbox?",
     "why": "Views are saved filters. You can add more later by typing.",
     "options": [["court_soon", "Court within 7 days"], ["evictions", "Evictions"],
                 ["spanish", "Spanish"], ["unassigned", "Unassigned"]],
     "default": ["court_soon", "evictions"], "patch": "pick_views"},
    {"id": "approval", "kind": "chips", "multi": False,
     "prompt": "What may I send without staff looking first?",
     "why": "Anything that touches the merits of a case or eligibility always waits for a person.",
     "options": [["none", "Nothing, staff reviews every reply"], ["routine", "Acknowledgements and scheduling"]],
     "default": "none", "patch": "set_approval"},
    {"id": "tone", "kind": "chips", "multi": False, "prompt": "How should replies sound?",
     "why": "Sets the voice for every draft.",
     "options": [["plain", "Plain"], ["warm", "Warm"], ["formal", "Formal"]],
     "default": "plain", "patch": "set_tone"},
]

LADDERS = {
    "reply": [
        (("hearing", "court date", "summons", "courthouse", "tomorrow", "next week"),
         "Thank you for reaching out. Please go to your hearing no matter what, even if you have not heard back from us yet, and bring every paper you were given. An attorney or paralegal will review your situation and someone will call you as soon as possible. Our services are free."),
        (("evict", "landlord", "locked out", "lockout", "notice to quit", "changed the locks"),
         "Thank you for telling us about this, and I am sorry. Please keep every notice and message from your landlord. An attorney or paralegal will review it and someone will call you. Our services are free."),
        (("qualify", "eligible", "income limit", "make too much", "do we qualify"),
         "Thank you for asking. Whether we can take a case depends on income and county, and that decision is made by an attorney or paralegal after a screening call, so I cannot answer it in writing. Someone will call you to go over it. Our services are free."),
        (("cost", "how much", "fee", "charge", "afford", "pay you"),
         "Our services are free. There is never a charge for anything we do. An attorney or paralegal will review your situation and someone will call you."),
        (("immigration", "citizenship", "undocumented", "visa", "papers"),
         "Thank you for trusting us with this. An attorney will talk with you about that privately on a call, so there is nothing you need to put in writing. Someone will call you to set that up. Our services are free."),
        (("benefits", "snap", "medicaid", "unemployment", "tanf", "denied", "appeal"),
         "Thank you for reaching out, and I am sorry about the denial. Please keep the letter and note the date on it, because appeal deadlines matter. An attorney or paralegal will review it and someone will call you. Our services are free."),
    ],
    "fallback": "Thank you for contacting Prairie Justice Legal Aid, {who}. Our services are free. An attorney or paralegal will review what you sent and someone will call you within two business days.",
    "check_in": "Hi {who}, this is Elena at Prairie Justice Legal Aid checking in. Do you still need help with the matter you contacted us about? Reply here any time.",
    "booking": "Hi {who}, here is a link to pick a time for your screening call with a paralegal. Choose any time that works, and reply here if none of them do.",
    "thanks": "Thank you, {who}. Someone will be in touch soon, and you can reply here with any questions.",
    "decline": "Thank you for contacting us, {who}. This is not a matter we are able to take on, but the county bar's lawyer referral line can connect you with someone who handles it, and some offer reduced fees.",
    "ask_missing": "Thank you, {who}. To route this to the right person, could you tell me which county you live in, what the problem is about, and whether there is a court date?",
}

SAMPLE_INPUTS = [
    {"label": "Sample forwarded email", "source": "email",
     "text": "From: Rohan Quinn <rohan.quinn@example.com>\nSubject: Eviction notice, need help\n\nName: Rohan Quinn\nCounty: Champaign\nMessage: My landlord taped a 5 day notice to my door on Monday saying I owe two months. I have a hearing date on the paper for September 3. I live with my wife and our two kids and we make about 2,300 a month between us. Can you help?"},
    {"label": "Sample hotline transcript", "source": "voicemail",
     "text": "Hotline transcript, 4:15 pm: Hi, this is Wren Okonkwo in Peoria County. My unemployment got denied and the letter says I have until September 10 to appeal. I live alone and have no income right now. Please call me back at 309 555 0143."},
]

C = [
    conv("la_01", "voicemail", "Teresa Okafor", "+1 (217) 555-0134",
         "Hotline: eviction hearing tomorrow",
         [msg("inbound", 35, "Hotline transcript, 8:05 pm: Hi, my name is Teresa Okafor, I got papers from my landlord and the court date is tomorrow morning at 9 at the Champaign County courthouse. I am behind two months of rent. It is me and my three kids. I make about 1,900 a month at the nursing home. Please call me back, 217 555 0134.")],
         priority="urgent",
         fields={"county": v("Champaign", 0.95, "Champaign County"),
                 "issue": v("eviction", 0.95, "papers from my landlord"),
                 "household_size": v(4, 0.9, "me and my three kids"),
                 "monthly_income": v(1900, 0.9, "1,900 a month"),
                 "language": v("english", 0.9, ""),
                 "court_date": v("2026-08-27", 0.95, "tomorrow morning"),
                 "urgency": v("high", 0.97, "court date is tomorrow")},
         drafts={"reply": "Hi Teresa, this is Elena at Prairie Justice Legal Aid. Please go to your hearing tomorrow morning at 9 no matter what, and bring the papers your landlord gave you. Someone from our intake team will call you within the hour to go over your situation. Our services are free."},
         tricky="hearing tomorrow: urgent, Court soon flag, draft says go to court and intake calls within the hour"),
    conv("la_02", "email", "Miguel Torres", "miguel.torres@example.com",
         "SNAP cut off and my immigration status",
         [msg("inbound", 260, "Hello, my SNAP benefits were cut off last month and I got a notice saying I have to repay $1,400. I am worried about how my immigration status affects this. I live in Sangamon County with my wife and two kids and I make about 2,600 a month from two jobs. No court date, just the notice.")],
         fields={"county": v("Sangamon", 0.95, "Sangamon County"),
                 "issue": v("benefits", 0.95, "SNAP benefits"),
                 "household_size": v(4, 0.9, "my wife and two kids"),
                 "monthly_income": v(2600, 0.9, "2,600 a month"),
                 "language": v("english", 0.9, ""),
                 "court_date": UNKNOWN,
                 "urgency": v("normal", 0.7, "just the notice")},
         drafts={"reply": "Hi Miguel, thank you for writing, and I am sorry about the notice. An attorney here will talk with you about your question privately on a call, so there is nothing you need to put in writing about it. To get started, could you tell me the date printed on the repayment notice? Our services are free."},
         tricky="immigration status: medical_legal, draft moves it to a private call and puts nothing about status in writing"),
    conv("la_03", "sms", "Ana Ferreira", "+1 (309) 555-0158",
         "Texto: desalojo, audiencia el lunes",
         [msg("inbound", 120, "Hola, mi arrendador me dio papeles de desalojo y tengo audiencia el lunes 31 de agosto en Peoria. Somos 5 en casa. Gano como 2,200 al mes. Necesito ayuda por favor.")],
         priority="urgent",
         fields={"county": v("Peoria", 0.85, "Peoria"),
                 "issue": v("eviction", 0.95, "desalojo"),
                 "household_size": v(5, 0.9, "Somos 5 en casa"),
                 "monthly_income": v(2200, 0.9, "2,200 al mes"),
                 "language": v("spanish", 0.97, "Necesito ayuda"),
                 "court_date": v("2026-08-31", 0.95, "lunes 31 de agosto"),
                 "urgency": v("high", 0.95, "audiencia el lunes")},
         drafts={"reply": "Hola Ana, le escribe Elena de Prairie Justice Legal Aid. Por favor vaya a su audiencia el lunes 31 de agosto aunque todavía no le hayamos confirmado, y lleve todos los papeles. Alguien de nuestro equipo la llamará hoy en español. Nuestros servicios son gratuitos."},
         tricky="written in Spanish: flag fires, draft is in Spanish"),
    conv("la_04", "web_form", "Devon Marsh", "devon.marsh@example.com",
         "Unpaid wages at a warehouse, McLean",
         [msg("inbound", 800, "My employer in McLean County has not paid me for my last three weeks at the warehouse and now says I was a contractor. I am single, no kids. When I was working I made about 2,800 a month. No court date, I just want to know my options.")],
         fields={"county": v("McLean", 0.95, "McLean County"),
                 "issue": v("employment", 0.95, "has not paid me"),
                 "household_size": v(1, 0.9, "single, no kids"),
                 "monthly_income": v(2800, 0.85, "2,800 a month"),
                 "language": v("english", 0.9, ""),
                 "court_date": UNKNOWN,
                 "urgency": v("normal", 0.7, "No court date")},
         drafts={"reply": "Hi Devon, thank you for reaching out, and I am sorry about the unpaid wages. Our services are free, and an attorney or paralegal will review what you sent and decide whether we can take it on. Could you tell me the name of the employer and the dates of the three weeks you were not paid? Someone will call you within two business days."}),
    conv("la_05", "voicemail", "Beatrice Lang", "+1 (217) 555-0156",
         "Hotline: served custody papers, hearing Sept 15",
         [msg("inbound", 4400, "Hotline transcript, 12:20 pm: This is Beatrice Lang in Macon County. My ex filed for custody of our daughter and I got served on Friday. There is a hearing on September 15th. It is just me and her at home and I bring home about 1,700 a month. Call me at 217 555 0156."),
          msg("outbound", 4300, "Hi Beatrice, this is Elena at Prairie Justice Legal Aid. Thank you for calling. I have opened a file and a paralegal will call you tomorrow to go over the custody papers and your hearing on September 15th. Our services are free.", author="Elena"),
          msg("note", 4280, "Screening call set for tomorrow 10am with Marcus. Served Friday 8/21.", author="Elena")],
         stage="screening", assignee="Elena", unread=False,
         fields={"county": v("Macon", 0.95, "Macon County"),
                 "issue": v("family", 0.95, "filed for custody"),
                 "household_size": v(2, 0.9, "just me and her"),
                 "monthly_income": v(1700, 0.9, "1,700 a month"),
                 "language": v("english", 0.9, ""),
                 "court_date": v("2026-09-15", 0.95, "September 15th"),
                 "urgency": v("normal", 0.7, "September 15th")}),
    conv("la_06", "email", "Jordan Kim", "jordan.kim@example.com",
         "Debt collector lawsuit, do we qualify",
         [msg("inbound", 1100, "Hi, I was served with a lawsuit by a debt collector over an old credit card, about $6,000. The court date is October 2nd in Tazewell County. My household is me and my husband, and together we bring in about 5,200 a month. Do we qualify for help?")],
         fields={"county": v("Tazewell", 0.95, "Tazewell County"),
                 "issue": v("consumer_debt", 0.95, "debt collector"),
                 "household_size": v(2, 0.9, "me and my husband"),
                 "monthly_income": v(5200, 0.9, "5,200 a month"),
                 "language": v("english", 0.9, ""),
                 "court_date": v("2026-10-02", 0.95, "October 2nd"),
                 "urgency": v("normal", 0.7, "October 2nd")},
         drafts={"reply": "Hi Jordan, thank you for writing. Whether we can take a case depends on income and county, and that decision is made by an attorney or paralegal after a screening call, so I cannot answer it here. I have opened a file and someone will call you within two business days. Our services are free."},
         tricky="income over 4000: the eligibility flag fires, draft does not say whether they qualify"),
    conv("la_07", "sms", "Sam Patel", "+1 (217) 555-0191",
         "Text: unemployment denied, 30 days to appeal",
         [msg("inbound", 55, "hi i got denied unemployment and the letter says i have 30 days to appeal. i'm in vermilion county, live alone, no income right now. what do i do")],
         priority="high",
         fields={"county": v("Vermilion", 0.95, "vermilion county"),
                 "issue": v("benefits", 0.95, "denied unemployment"),
                 "household_size": v(1, 0.9, "live alone"),
                 "monthly_income": v(0, 0.85, "no income right now"),
                 "language": v("english", 0.9, ""),
                 "court_date": UNKNOWN,
                 "urgency": v("high", 0.8, "30 days to appeal")},
         drafts={"reply": "Hi Sam, thank you for texting, and I am sorry about the denial. Please keep the letter and note the date on it, because the appeal deadline matters. An attorney or paralegal will review this, and someone will call you within two business days. Our services are free."}),
    conv("la_08", "referral", "Ruth Adler", "+1 (309) 555-0171",
         "Referral from Riverbend Health: eviction, Peoria",
         [msg("inbound", 700, "Partner referral from Riverbend Health (social worker: Dana Whitfield). Client: Ruth Adler, Peoria County. Landlord filed eviction, hearing September 9. Household of 3 (client and two grandchildren). Income about 1,500 a month from Social Security. Client prefers phone, speaks English. Phone 309 555 0171.")],
         priority="high",
         fields={"county": v("Peoria", 0.95, "Peoria County"),
                 "issue": v("eviction", 0.95, "filed eviction"),
                 "household_size": v(3, 0.95, "Household of 3"),
                 "monthly_income": v(1500, 0.9, "1,500 a month"),
                 "language": v("english", 0.95, "speaks English"),
                 "court_date": v("2026-09-09", 0.95, "September 9"),
                 "urgency": v("high", 0.85, "hearing September 9")},
         drafts={"reply": "Hi Ruth, this is Elena at Prairie Justice Legal Aid. Dana at Riverbend Health passed your information to us. Please plan to go to your hearing on September 9 no matter what, and someone from our intake team will call you today to go over the eviction papers. Our services are free."},
         tricky="partner referral logged by hand"),
    conv("la_09", "web_form", "Hannah Cole", "hannah.cole@example.com",
         "Landlord changed the locks, Champaign",
         [msg("inbound", 9000, "My landlord changed the locks on Sunday while I was at work. No court papers, nothing. I am in Champaign County, it is me and my son, I make about 2,100 a month cleaning offices. I have been sleeping at my sister's."),
          msg("outbound", 8900, "Hi Hannah, this is Marcus at Prairie Justice Legal Aid. I am sorry, that sounds frightening. I have opened a file and an attorney will call you this afternoon. Please keep any texts or notes from your landlord. Our services are free.", author="Marcus"),
          msg("inbound", 8600, "Thank you. Any time after 2 is fine."),
          msg("outbound", 8500, "Got it, the call will be after 2. Talk soon.", author="Marcus"),
          msg("note", 8480, "Attorney Reyes accepted the case. Lockout, no filing.", author="Marcus")],
         stage="accepted", assignee="Marcus", unread=False,
         fields={"county": v("Champaign", 0.95, "Champaign County"),
                 "issue": v("eviction", 0.9, "changed the locks"),
                 "household_size": v(2, 0.9, "me and my son"),
                 "monthly_income": v(2100, 0.9, "2,100 a month"),
                 "language": v("english", 0.9, ""),
                 "court_date": UNKNOWN,
                 "urgency": v("high", 0.9, "changed the locks")}),
    conv("la_10", "voicemail", "Nadia Varga", "+1 (815) 555-0126",
         "Hotline: Polish speaker, Medicaid ended",
         [msg("inbound", 400, "Hotline transcript, 9:50 am: Caller name Nadia Varga, speaks Polish, limited English, asked for an interpreter. Says her Medicaid was ended and she has a letter. Lives in Kankakee County with her husband. Could not confirm income. No court date. Call back 815 555 0126.")],
         fields={"county": v("Kankakee", 0.95, "Kankakee County"),
                 "issue": v("benefits", 0.9, "Medicaid was ended"),
                 "household_size": v(2, 0.8, "with her husband"),
                 "monthly_income": UNKNOWN,
                 "language": v("polish", 0.95, "speaks Polish"),
                 "court_date": UNKNOWN,
                 "urgency": v("normal", 0.7, "No court date")},
         drafts={"reply": "Hi Nadia, this is Elena at Prairie Justice Legal Aid. Thank you for calling. We will call you back with a Polish interpreter on the line to go over the Medicaid letter, so please keep the letter handy. Our services are free."}),
    conv("la_11", "sms", "Chris Doyle", "+1 (217) 555-0144",
         "Text: will and power of attorney for my mom",
         [msg("inbound", 15000, "Hi, I need help with a will and power of attorney for my mom. We are in Sangamon County. Is that something you do?"),
          msg("outbound", 14900, "Hi Chris, thank you for texting. Estate planning is not something we handle, but the Sangamon County Bar's lawyer referral line can connect you with someone who does, and some offer reduced fees. I am sorry we cannot help directly.", author="Elena"),
          msg("inbound", 14700, "Ok thanks for letting me know."),
          msg("outbound", 14650, "You are welcome, Chris. Take care.", author="Elena")],
         stage="referred_out", status="resolved", unread=False, assignee="Elena",
         fields={"county": v("Sangamon", 0.95, "Sangamon County"),
                 "issue": v("other", 0.9, "will and power of attorney"),
                 "household_size": UNKNOWN,
                 "monthly_income": UNKNOWN,
                 "language": v("english", 0.9, ""),
                 "court_date": UNKNOWN,
                 "urgency": v("low", 0.8, "Is that something you do")}),
    conv("la_12", "web_form", "Priya Natarajan", "priya.n@example.com",
         "Ex has not returned the kids, custody order",
         [msg("inbound", 60, "My ex has not returned our two kids since his weekend ended on Sunday and is not answering. We have a custody order from Sangamon County. I am a nurse and make about 4,600 a month, household is me and the two kids. Is there anything I can do today?")],
         priority="high",
         fields={"county": v("Sangamon", 0.95, "Sangamon County"),
                 "issue": v("family", 0.95, "custody order"),
                 "household_size": v(3, 0.9, "me and the two kids"),
                 "monthly_income": v(4600, 0.9, "4,600 a month"),
                 "language": v("english", 0.9, ""),
                 "court_date": UNKNOWN,
                 "urgency": v("high", 0.9, "anything I can do today")},
         drafts={"reply": "Hi Priya, thank you for writing, and I understand how frightening this is. I cannot give advice in writing, but an attorney will call you today to talk it through. If you believe the children are in danger right now, please call 911. Our services are free."},
         tricky="distress and income over 4000: review, eligibility flag fires"),
    conv("la_13", "email", "Kwame Osei", "kwame.osei@example.com",
         "Eviction hearing August 5, Peoria",
         [msg("inbound", 40000, "Hello, I got an eviction notice in Peoria County, hearing was set for August 5. I live alone and make about 1,600 a month."),
          msg("outbound", 39900, "Hi Kwame, this is Marcus at Prairie Justice Legal Aid. Please go to your hearing on August 5 no matter what. I have opened a file and an attorney will call you today. Our services are free.", author="Marcus"),
          msg("inbound", 30000, "Update: the landlord and I worked out a payment plan and he dropped the case. Thank you for the help."),
          msg("outbound", 29900, "That is great news, Kwame. I will close the file, and you can reach out again any time.", author="Marcus"),
          msg("note", 29880, "Case dismissed, payment plan with landlord. Closed.", author="Marcus")],
         stage="closed", status="resolved", unread=False, assignee="Marcus",
         fields={"county": v("Peoria", 0.95, "Peoria County"),
                 "issue": v("eviction", 0.95, "eviction notice"),
                 "household_size": v(1, 0.9, "live alone"),
                 "monthly_income": v(1600, 0.9, "1,600 a month"),
                 "language": v("english", 0.9, ""),
                 "court_date": v("2026-08-05", 0.95, "August 5"),
                 "urgency": v("low", 0.8, "dropped the case")}),
    conv("la_14", "voicemail", "Lena Brennan", "+1 (309) 555-0182",
         "Hotline: car repossessed, Tazewell",
         [msg("inbound", 1500, "Hotline transcript, 6:30 pm: Hi, this is Lena Brennan, my car was repossessed last night and now the lender says I owe 3,400 more. I am in Tazewell County. I have two kids, my husband left. I work part time, maybe 1,300 a month. No court date that I know of. 309 555 0182."),
          msg("outbound", 1400, "Hi Lena, this is Marcus at Prairie Justice Legal Aid. Thank you for calling, and I am sorry about the car. Please keep any letters from the lender. I have opened a file and a paralegal will call you tomorrow morning. Our services are free.", author="Marcus"),
          msg("note", 1380, "Screening call tomorrow 9:30. Repossession, deficiency claim.", author="Marcus")],
         stage="screening", assignee="Marcus", unread=False,
         fields={"county": v("Tazewell", 0.95, "Tazewell County"),
                 "issue": v("consumer_debt", 0.95, "car was repossessed"),
                 "household_size": v(3, 0.7, "I have two kids"),
                 "monthly_income": v(1300, 0.8, "1,300 a month"),
                 "language": v("english", 0.9, ""),
                 "court_date": UNKNOWN,
                 "urgency": v("normal", 0.7, "No court date that I know of")}),
    conv("la_15", "referral", "Ingrid Varga", "+1 (815) 555-0119",
         "Referral from Cornerstone Shelter: TANF appeal, Spanish",
         [msg("inbound", 950, "Partner referral from Cornerstone Family Shelter (case manager: Leo Sato). Client: Ingrid Varga. Prefers Spanish. Kankakee County. TANF application denied, appeal deadline September 4. Household of 4. No income at this time. Best reached by text at 815 555 0119.")],
         priority="high",
         fields={"county": v("Kankakee", 0.95, "Kankakee County"),
                 "issue": v("benefits", 0.95, "TANF application denied"),
                 "household_size": v(4, 0.95, "Household of 4"),
                 "monthly_income": v(0, 0.9, "No income at this time"),
                 "language": v("spanish", 0.95, "Prefers Spanish"),
                 "court_date": UNKNOWN,
                 "urgency": v("high", 0.85, "appeal deadline September 4")},
         drafts={"reply": "Hola Ingrid, le escribe Elena de Prairie Justice Legal Aid. Leo de Cornerstone Family Shelter nos pasó su información. Alguien de nuestro equipo la llamará en español dentro de dos días hábiles para hablar de la apelación de TANF. Nuestros servicios son gratuitos."},
         tricky="partner referral in Spanish: flag fires, draft in Spanish"),
    conv("la_16", "web_form", "Noah Ivers", "noah.ivers@example.com",
         "Eviction hearing next Monday, Macon",
         [msg("inbound", 300, "I got a summons for an eviction hearing next Monday at the Macon County courthouse. I am behind one month because my hours got cut. Household is me, my partner and our baby. Right now we make about 2,400 a month between us.")],
         priority="urgent",
         fields={"county": v("Macon", 0.95, "Macon County"),
                 "issue": v("eviction", 0.97, "eviction hearing"),
                 "household_size": v(3, 0.9, "me, my partner and our baby"),
                 "monthly_income": v(2400, 0.9, "2,400 a month"),
                 "language": v("english", 0.9, ""),
                 "court_date": v("2026-08-31", 0.9, "next Monday"),
                 "urgency": v("high", 0.95, "next Monday")},
         drafts={"reply": "Hi Noah, thank you for reaching out. Please go to your hearing next Monday no matter what, and bring the summons and anything from your landlord. Someone from our intake team will call you today to go over the details. Our services are free."},
         tricky="hearing within 7 days: urgent, Court soon flag"),
    conv("la_17", "sms", "Grace Abara", "+1 (217) 555-0163",
         "Text: fired after reporting a safety problem",
         [msg("inbound", 25000, "Hi, my boss fired me the day after I reported a safety problem at the plant in Vermilion County. Just me at home, I was making 3,100 a month."),
          msg("outbound", 24900, "Hi Grace, this is Elena at Prairie Justice Legal Aid. Thank you for texting, and I am sorry. I have opened a file and a paralegal will call you within two business days. Our services are free.", author="Elena"),
          msg("inbound", 20000, "Thanks, I actually got a lawyer through my union so I'm all set."),
          msg("outbound", 19900, "Glad to hear it, Grace. I will close the file, and you can reach out again any time.", author="Elena"),
          msg("note", 19880, "Represented by union counsel. Closed.", author="Elena")],
         stage="closed", status="resolved", unread=False, assignee="Elena",
         fields={"county": v("Vermilion", 0.95, "Vermilion County"),
                 "issue": v("employment", 0.95, "fired me the day after I reported"),
                 "household_size": v(1, 0.9, "Just me at home"),
                 "monthly_income": v(3100, 0.85, "3,100 a month"),
                 "language": v("english", 0.9, ""),
                 "court_date": UNKNOWN,
                 "urgency": v("low", 0.8, "all set")}),
]

TEMPLATE = {
    "key": "legal_aid",
    "name": "Legal aid nonprofit",
    "tagline": "Hotline transcripts, the intake form, email, texts and partner referrals, triaged by issue and urgency",
    "example_prompt": "Legal aid nonprofit. People reach us by phone, email, a web intake form, texts and partner referrals; we triage by issue and urgency.",
    "signals": [("legal aid", 5), ("pro bono", 3), ("eviction", 3), ("hotline", 3),
                ("nonprofit", 2), ("intake", 2), ("tenant", 2), ("court date", 2),
                ("partner referral", 2), ("benefits", 1)],
    "must_review": ["medical_legal"],
    "spec": SPEC,
    "questions": QUESTIONS,
    "personas": ["Elena", "Marcus"],
    "ladders": LADDERS,
    "sample_inputs": SAMPLE_INPUTS,
    "prompt_examples": ["add a field for the landlord's name",
                        "add a view of benefits cases with a deadline this month",
                        "flag anyone who mentions domestic violence"],
    "conversations": C,
}
