"""Nurse staffing agency: Northline Nurse Staffing (fictional), Midwest contracts."""
from ._common import conv, msg, v, UNKNOWN

SPEC = {
    "business": {
        "name": "Northline Nurse Staffing",
        "type": "nurse_staffing",
        "summary": "Nurse staffing agency placing RNs and LPNs in hospital and clinic contracts and per diem shifts across the Midwest. Candidates apply, facilities request staff.",
        "audience": "candidates",
    },
    "connectors": [
        {"key": "indeed", "kind": "indeed", "label": "Indeed applications", "auto_connect": True},
        {"key": "email", "kind": "email", "label": "recruiting@northlinenurses.example.com", "auto_connect": True},
        {"key": "web_form", "kind": "web_form", "label": "Apply form", "auto_connect": True},
        {"key": "sms", "kind": "sms", "label": "Recruiting text line", "auto_connect": True},
        {"key": "referral", "kind": "referral", "label": "Nurse referrals", "auto_connect": False},
        {"key": "facebook_leads", "kind": "facebook_leads", "label": "Facebook Lead Ads", "auto_connect": False},
    ],
    "fields": [
        {"key": "specialty", "label": "Specialty", "type": "enum",
         "options": ["icu", "er", "med_surg", "l_and_d", "peds", "or", "other"],
         "hint": "The unit they work on or the unit a facility is asking for; LPN and long term care are other",
         "show_in_list": True},
        {"key": "license_state", "label": "License state", "type": "text",
         "hint": "Two letter state where the RN or LPN license is held; for a facility, the state of the facility",
         "show_in_list": True},
        {"key": "compact_license", "label": "Compact license", "type": "bool",
         "hint": "Whether they hold a multi-state compact (NLC) license"},
        {"key": "years_experience", "label": "Years of experience", "type": "number",
         "hint": "Years of bedside nursing experience; a new grad is 0"},
        {"key": "available_date", "label": "Available date", "type": "date",
         "hint": "First day they can start, or the start date a facility needs; resolve relative dates against when it was sent",
         "show_in_list": True},
        {"key": "certifications", "label": "Certifications", "type": "list",
         "hint": "Certifications they hold or a facility requires, like BLS, ACLS, PALS, CCRN, TNCC, NRP"},
        {"key": "shift_preference", "label": "Shift preference", "type": "enum",
         "options": ["days", "nights", "either"],
         "hint": "Days, nights or either; for a facility, the shift they need filled"},
    ],
    "stages": [
        {"key": "new", "label": "New", "tone": "brand"},
        {"key": "screening", "label": "Screening", "tone": "info"},
        {"key": "credentialing", "label": "Credentialing", "tone": "warn"},
        {"key": "placed", "label": "Placed", "tone": "ok", "terminal": True},
        {"key": "not_a_fit", "label": "Not a fit", "tone": "neutral", "terminal": True},
    ],
    "views": [
        {"key": "inbox", "name": "All open",
         "filter": {"all": [{"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "needs_reply", "name": "Needs reply",
         "filter": {"all": [{"field": "awaiting_reply", "op": "eq", "value": True}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "icu_30", "name": "ICU available in 30 days",
         "filter": {"all": [{"field": "f.specialty", "op": "eq", "value": "icu"},
                            {"field": "f.available_date", "op": "within_days", "value": 30},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "f.available_date", "dir": "asc"}, "pinned": True},
        {"key": "compact", "name": "Compact license",
         "filter": {"all": [{"field": "f.compact_license", "op": "eq", "value": True},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "in_credentialing", "name": "In credentialing",
         "filter": {"all": [{"field": "stage", "op": "eq", "value": "credentialing"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}},
        {"key": "unassigned", "name": "Unassigned",
         "filter": {"all": [{"field": "assignee", "op": "is_empty"},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}},
    ],
    "rules": [
        {"key": "flag_compact", "name": "Compact license",
         "text": "Flag anyone with a multi-state compact license",
         "when": {"all": [{"field": "f.compact_license", "op": "eq", "value": True}]},
         "then": {"type": "flag", "label": "Multi-state", "tone": "ok"}},
        {"key": "flag_new_grad", "name": "New grads",
         "text": "Flag candidates with less than a year of experience",
         "when": {"all": [{"field": "f.years_experience", "op": "lt", "value": 1}]},
         "then": {"type": "flag", "label": "New grad", "tone": "info"}},
        {"key": "priority_soon", "name": "Available within two weeks",
         "text": "Mark anyone available in the next 14 days as high priority",
         "when": {"all": [{"field": "f.available_date", "op": "within_days", "value": 14}]},
         "then": {"type": "set_priority", "value": "high"}},
        {"key": "flag_hot_icu", "name": "ICU available soon",
         "text": "Flag ICU nurses available within 30 days as hot",
         "when": {"all": [{"field": "f.specialty", "op": "eq", "value": "icu"},
                          {"field": "f.available_date", "op": "within_days", "value": 30}]},
         "then": {"type": "flag", "label": "Hot", "tone": "warn"}},
    ],
    "approval_policy": {"routine": "auto_send", "pricing": "review",
                        "medical_legal": "review", "distress": "review"},
    "tone": {"voice": "warm", "length": "short", "signoff": "Kwame at Northline Nurse Staffing",
             "presets": [
                 {"label": "Answer their question", "instruction": "Answer the question they just asked"},
                 {"label": "Offer a screening call", "instruction": "Offer a 15 minute screening call with a recruiter and ask which times work"},
                 {"label": "Ask for the basics", "instruction": "Ask for specialty, license state, years of experience and the date they can start"},
                 {"label": "Check in", "instruction": "Check in and ask whether they are still looking"}]},
    "agent": {"name": "Kwame", "persona": "Recruiting coordinator at a nurse staffing agency",
              "intro": "I read every application and facility request, pull out what matters, and draft the first reply for you to approve."},
    "playbook": "- Pay rates are discussed on the screening call, never in writing.\n- Every candidate does a 15 minute screening call with a recruiter first.\n- Credentialing takes 5 to 10 business days once documents are in.\n- Never promise a job, a placement or a start date.",
    "guardrails": [
        {"key": "eeoc", "text": "Never screen on age, disability, national origin, citizenship, visa status, religion or marital status.",
         "enforce": "refuse_field",
         "patterns": ["age", "date of birth", "disability", "national origin", "nationality",
                      "citizenship", "visa", "where are you from", "religion", "marital"],
         "reason": "age, disability, national origin, citizenship or similar protected characteristics under employment law",
         "refusal": "I cannot add that. Employment law does not allow screening on age, disability, national origin, citizenship or similar characteristics. I can add fields that apply to every candidate the same way, like license state, specialty, years of experience or available date."},
        {"key": "no_promises", "text": "Never promise a job, a placement or a pay rate in writing.",
         "enforce": "never_promise"},
    ],
}

QUESTIONS = [
    {"id": "sources", "kind": "tiles", "multi": True,
     "prompt": "Where do candidates and facility requests come in?",
     "why": "Each one becomes a connector and a way to filter.",
     "options": ["indeed", "email", "web_form", "sms", "referral", "facebook_leads"],
     "default": ["indeed", "email", "web_form", "sms"], "patch": "set_connectors"},
    {"id": "business_name", "kind": "text", "prompt": "What is the agency called?",
     "why": "It goes on every reply.", "default": "Northline Nurse Staffing", "patch": "set_business_name"},
    {"id": "extract_fields", "kind": "chips", "multi": True,
     "prompt": "What should I pull out of every application?",
     "why": "Each one becomes a column you can sort and filter by.",
     "options": [["specialty", "Specialty"], ["license_state", "License state"],
                 ["compact_license", "Compact license"], ["years_experience", "Years of experience"],
                 ["available_date", "Available date"], ["certifications", "Certifications"],
                 ["shift_preference", "Shift preference"]],
     "default": ["specialty", "license_state", "compact_license", "years_experience",
                 "available_date", "shift_preference"], "patch": "pick_fields"},
    {"id": "slices", "kind": "chips", "multi": True,
     "prompt": "Which views do you want on the front of the inbox?",
     "why": "Views are saved filters. You can add more later by typing.",
     "options": [["icu_30", "ICU available in 30 days"], ["compact", "Compact license"],
                 ["in_credentialing", "In credentialing"], ["unassigned", "Unassigned"]],
     "default": ["icu_30", "compact"], "patch": "pick_views"},
    {"id": "approval", "kind": "chips", "multi": False,
     "prompt": "What may I send without you looking first?",
     "why": "Anything about pay rates always waits for you.",
     "options": [["routine", "Acknowledgements and scheduling"], ["none", "Nothing, I review every reply"]],
     "default": "routine", "patch": "set_approval"},
    {"id": "tone", "kind": "chips", "multi": False, "prompt": "How should replies sound?",
     "why": "Sets the voice for every draft.",
     "options": [["warm", "Warm"], ["plain", "Plain"], ["upbeat", "Upbeat"]],
     "default": "warm", "patch": "set_tone"},
]

LADDERS = {
    "reply": [
        (("pay", "rate", "hourly", "salary", "how much", "per hour", "stipend", "bonus"),
         "Thanks for asking. Pay depends on the facility, the shift and the contract, so we go over it on the screening call rather than in writing. It is a quick 15 minute call; what days and times work for you?"),
        (("visa", "sponsor", "work authorization", "work permit", "green card"),
         "Thanks for reaching out. Work authorization is confirmed during credentialing with our HR team, so I cannot answer that part here, but the first step for every candidate is a 15 minute screening call with a recruiter. What days and times work for you?"),
        (("compact", "multi-state", "multistate", "other states", "travel"),
         "Thanks for reaching out. A compact license opens up a lot more options, and a recruiter will go over which facilities are a match on a 15 minute screening call. What days and times work for you?"),
        (("new grad", "graduated", "graduating", "nclex", "first job", "no experience"),
         "Congratulations, and thanks for reaching out. We do work with new graduates, and the best next step is a 15 minute screening call so a recruiter can talk through where you would fit. What days and times work for you?"),
        (("credential", "credentialing", "documents", "paperwork", "background check", "how long"),
         "Thanks for checking. Credentialing usually takes 5 to 10 business days once your documents are in, and we will let you know as soon as anything is missing. Reply here any time with questions."),
        (("need nurses", "need staff", "we need", "our unit", "shifts to fill", "requesting", "nurse manager"),
         "Thank you for reaching out. I have passed your request to our staffing team, and someone will call you to go over the unit, the shifts and start dates. What is the best number and time to reach you?"),
    ],
    "fallback": "Thanks for reaching out to Northline Nurse Staffing, {who}. The first step for every candidate is a 15 minute screening call with a recruiter. What days and times work for you?",
    "check_in": "Hi {who}, checking in to see whether you would still like to set up a 15 minute screening call. Reply here any time and I will find a slot that works.",
    "booking": "Hi {who}, here is the link to book your 15 minute screening call. Pick any time that suits you, and reply here if none of them work.",
    "thanks": "Thank you, {who}. We will be in touch soon, and you can reply here with any questions.",
    "decline": "Thank you for reaching out, {who}. We do not have a match for your background right now, but we keep every application on file and will reach out if that changes.",
    "ask_missing": "Thanks {who}. So I can get you to the right recruiter, could you tell me your specialty, which state your license is in, how many years of experience you have, and when you could start?",
}

SAMPLE_INPUTS = [
    {"label": "Sample Indeed application", "source": "indeed",
     "text": "From: Indeed <apply@indeed.example.com>\nSubject: New candidate for Registered Nurse, ICU, Chicago\n\nName: Ana Brennan\nLocation: Springfield, IL\nMessage: Hi, I am an ICU RN with 5 years at a level 1 trauma center. Illinois license, compact. CCRN, ACLS, BLS. My current contract ends September 25 and I could start the following Monday. Nights preferred. Looking for 13 weeks in the Chicago area."},
    {"label": "Sample facility voicemail", "source": "email",
     "text": "Voicemail transcript, 4:32 pm: Hi, this is Rohan Varga, I am the nurse manager for the ER at Cedar Glen Regional in Bloomington. We are down two RNs on nights and need coverage starting the first week of October, 13 week contracts, TNCC and ACLS required. Please call me back at 309 555 0143 or email rvarga at cedarglen dot example dot org."},
]

C = [
    conv("ns_01", "indeed", "Priya Natarajan", "indeed:priya.natarajan",
         "Indeed: ICU RN, compact, available in three weeks",
         [msg("inbound", 150, "Hi, I am an ICU RN with 6 years of experience, currently in Illinois with a compact license. My contract ends September 15 so I could start in three weeks. I have BLS, ACLS and CCRN. I prefer nights but I am open. Looking for a 13 week contract in the Chicago area.")],
         fields={"specialty": v("icu", 0.97, "ICU RN"),
                 "license_state": v("IL", 0.9, "currently in Illinois"),
                 "compact_license": v(True, 0.95, "compact license"),
                 "years_experience": v(6, 0.95, "6 years of experience"),
                 "available_date": v("2026-09-16", 0.8, "start in three weeks"),
                 "certifications": v(["BLS", "ACLS", "CCRN"], 0.95, "BLS, ACLS and CCRN"),
                 "shift_preference": v("nights", 0.7, "prefer nights but I am open")},
         drafts={"reply": "Hi Priya, thanks for applying, and 6 years in the ICU with CCRN and a compact license is a strong background. The first step is a 15 minute screening call with a recruiter, who can go over your options in the Chicago area around your mid September start. What days and times work for you?"},
         tricky="the demo add_view case: ICU, available within 30 days"),
    conv("ns_02", "email", "Marcus Bell", "marcus.bell@example.com",
         "Will you sponsor my visa?",
         [msg("inbound", 300, "Hello, I am a registered nurse with 8 years in med surg and I am from the Philippines. I am currently in the US on a visa that ends next year. Will you sponsor my visa? I have my Illinois license and BLS. I can start right away, days or nights.")],
         priority="high",
         fields={"specialty": v("med_surg", 0.95, "med surg"),
                 "license_state": v("IL", 0.95, "Illinois license"),
                 "compact_license": UNKNOWN,
                 "years_experience": v(8, 0.95, "8 years"),
                 "available_date": v("2026-08-26", 0.7, "start right away"),
                 "certifications": v(["BLS"], 0.9, "BLS"),
                 "shift_preference": v("either", 0.9, "days or nights")},
         drafts={"reply": "Hi Marcus, thank you for reaching out, and 8 years in med surg is a strong background. Work authorization is confirmed during credentialing with our HR team, so I cannot answer the sponsorship question here, but the first step for every candidate is a 15 minute screening call with a recruiter. What days and times work for you?"},
         tricky="national origin is not a field; the sponsorship reply routes to review"),
    conv("ns_03", "web_form", "Grace Doyle", "grace.doyle@example.com",
         "New grad, passed NCLEX last week",
         [msg("inbound", 600, "Hi! I just graduated in May and passed my NCLEX last week, so my Indiana license should post any day. No experience yet beyond clinicals, I did my capstone on a med surg floor. I have BLS. I can start as soon as the license posts, I would love days but I will take anything.")],
         fields={"specialty": v("med_surg", 0.6, "capstone on a med surg floor"),
                 "license_state": v("IN", 0.9, "Indiana license"),
                 "compact_license": UNKNOWN,
                 "years_experience": v(0, 0.95, "No experience yet beyond clinicals"),
                 "available_date": v("2026-09-01", 0.5, "as soon as the license posts"),
                 "certifications": v(["BLS"], 0.9, "I have BLS"),
                 "shift_preference": v("days", 0.7, "I would love days but I will take anything")},
         drafts={"reply": "Hi Grace, congratulations on passing the NCLEX, and thanks for reaching out. We do work with new graduates, and the best next step is a 15 minute screening call so a recruiter can talk through where you would fit once your license posts. What days and times work for you?"},
         tricky="new grad: years_experience 0 fires the New grad flag"),
    conv("ns_04", "email", "Hannah Cole", "hannah.cole@riverbend.example.org",
         "Need 3 night shift RNs for our ICU starting October 5",
         [msg("inbound", 420, "Hi Kwame, this is Hannah Cole, nurse manager of the ICU at Riverbend Community Hospital in Joliet. We need 3 night shift RNs on 13 week contracts starting October 5. ICU experience required, ACLS required. Can you send over what you have? Best to call me at 815 555 0148 after 2pm.")],
         fields={"specialty": v("icu", 0.95, "ICU at Riverbend"),
                 "license_state": v("IL", 0.6, "Joliet"),
                 "compact_license": UNKNOWN,
                 "years_experience": UNKNOWN,
                 "available_date": v("2026-10-05", 0.9, "starting October 5"),
                 "certifications": v(["ACLS"], 0.9, "ACLS required"),
                 "shift_preference": v("nights", 0.95, "night shift RNs")},
         drafts={"reply": "Hi Hannah, thank you for reaching out, and thank you for the detail on the unit. I have passed your request for 3 night shift ICU RNs starting October 5 to our staffing team, and someone will call you after 2pm to go over the contracts. Is today or tomorrow better?"},
         tricky="facility request treated as a lead: specialty and shift extracted"),
    conv("ns_05", "sms", "Devon Marsh", "+1 (309) 555-0154",
         "What is the pay for ER contracts?",
         [msg("inbound", 90, "Hey, saw your ER contract posting in Peoria. What is the pay per hour and is there a housing stipend? I have 4 yrs ER, IL license, TNCC and ACLS. Could start in 2 weeks.")],
         priority="high",
         fields={"specialty": v("er", 0.95, "ER contract"),
                 "license_state": v("IL", 0.95, "IL license"),
                 "compact_license": UNKNOWN,
                 "years_experience": v(4, 0.95, "4 yrs ER"),
                 "available_date": v("2026-09-09", 0.8, "start in 2 weeks"),
                 "certifications": v(["TNCC", "ACLS"], 0.95, "TNCC and ACLS"),
                 "shift_preference": UNKNOWN},
         drafts={"reply": "Hi Devon, thanks for reaching out, and 4 years in the ER with TNCC is a strong background. Pay and stipends depend on the facility and the contract, so we go over them on the screening call rather than in writing. It is a quick 15 minute call; what days and times work for you?"},
         tricky="pay question: stays in review"),
    conv("ns_06", "indeed", "Sam Okonkwo", "indeed:sam.okonkwo",
         "Indeed: L&D RN with compact license, available September 14",
         [msg("inbound", 1400, "Applying for the L&D position. I have 9 years labor and delivery, currently in Missouri with a compact license, NRP and BLS, and I am also fetal monitoring certified. Available September 14. Days preferred."),
          msg("outbound", 1300, "Hi Sam, thanks for applying, and 9 years in labor and delivery with a compact license is a strong background. The first step is a 15 minute screening call with a recruiter. What days and times work for you?", author="Kwame"),
          msg("inbound", 1100, "Thursday between 10 and 2 works."),
          msg("outbound", 1000, "Great, Sam. Lisa will call you Thursday at 11am. A confirmation is on its way.", author="Kwame"),
          msg("note", 990, "Screening Thu 11am with Lisa. Compact, MO. Ask about the fetal monitoring cert and St. Louis versus Chicago.", author="Kwame")],
         stage="screening", assignee="Lisa", unread=False,
         fields={"specialty": v("l_and_d", 0.97, "labor and delivery"),
                 "license_state": v("MO", 0.9, "Missouri"),
                 "compact_license": v(True, 0.95, "compact license"),
                 "years_experience": v(9, 0.95, "9 years"),
                 "available_date": v("2026-09-14", 0.95, "Available September 14"),
                 "certifications": v(["NRP", "BLS", "fetal monitoring"], 0.9, "NRP and BLS"),
                 "shift_preference": v("days", 0.9, "Days preferred")}),
    conv("ns_07", "web_form", "Ruth Adler", "ruth.adler@example.com",
         "Peds RN moving to Madison in October",
         [msg("inbound", 700, "I am a pediatric nurse with 12 years, mostly PICU. My family is moving to Madison in October so I am looking for something starting around October 15. My license is Illinois, not compact, I am applying for Wisconsin now. PALS, BLS. I need days.")],
         fields={"specialty": v("peds", 0.95, "pediatric nurse"),
                 "license_state": v("IL", 0.9, "My license is Illinois"),
                 "compact_license": v(False, 0.95, "not compact"),
                 "years_experience": v(12, 0.95, "12 years"),
                 "available_date": v("2026-10-15", 0.85, "around October 15"),
                 "certifications": v(["PALS", "BLS"], 0.95, "PALS, BLS"),
                 "shift_preference": v("days", 0.9, "I need days")},
         drafts={"reply": "Hi Ruth, thanks for reaching out, and 12 years in pediatrics with PICU time is a strong background. A recruiter can talk through the Madison area and the Wisconsin license timing on a 15 minute screening call. What days and times work for you?"}),
    conv("ns_08", "sms", "Miguel Torres", "+1 (815) 555-0162",
         "Text: OR RN, is credentialing done yet?",
         [msg("inbound", 12000, "Hi, this is Miguel Torres, OR RN, 7 years, Illinois license. Saw the OR contract in Rockford. I have BLS and CNOR. Can start Sept 8. Either shift."),
          msg("outbound", 11900, "Hi Miguel, thanks for reaching out, and 7 years in the OR with CNOR is a strong background. The first step is a 15 minute screening call with a recruiter. What days and times work?", author="Kwame"),
          msg("inbound", 11700, "Tomorrow 3pm"),
          msg("outbound", 11600, "Tomorrow at 3pm it is. Lisa will call you.", author="Kwame"),
          msg("note", 10000, "Screened. Solid, wants Rockford. Sent the credentialing packet; waiting on license verification and immunization records.", author="Lisa"),
          msg("inbound", 60, "Hey did my credentialing go through yet? Sent everything Friday")],
         stage="credentialing", assignee="Lisa", priority="high",
         fields={"specialty": v("or", 0.97, "OR RN"),
                 "license_state": v("IL", 0.95, "Illinois license"),
                 "compact_license": UNKNOWN,
                 "years_experience": v(7, 0.95, "7 years"),
                 "available_date": v("2026-09-08", 0.95, "Can start Sept 8"),
                 "certifications": v(["BLS", "CNOR"], 0.95, "BLS and CNOR"),
                 "shift_preference": v("either", 0.9, "Either shift")},
         drafts={"reply": "Hi Miguel, thanks for checking. Credentialing usually takes 5 to 10 business days once documents are in, and since yours arrived Friday it is still inside that window. Lisa will let you know the moment anything is missing or it clears."}),
    conv("ns_09", "indeed", "Aisha Lindqvist", "indeed:aisha.lindqvist",
         "Indeed: med surg RN, Indiana compact, nights",
         [msg("inbound", 30000, "Applying for the med surg contract in Merrillville. 5 years med surg, Indiana compact license, BLS. Available August 24, nights."),
          msg("outbound", 29900, "Hi Aisha, thanks for applying. The first step is a 15 minute screening call with a recruiter. What days and times work for you?", author="Lisa"),
          msg("inbound", 29700, "Thursday morning any time"),
          msg("outbound", 29600, "Thursday at 9am. I will call you then.", author="Lisa"),
          msg("note", 28000, "Screened, great fit for Merrillville nights. Credentialing packet sent.", author="Lisa"),
          msg("note", 18000, "Credentialing clear. Offer accepted, starts Aug 24, 13 weeks nights.", author="Lisa"),
          msg("inbound", 800, "First two shifts done, the unit is great. Thank you Lisa!"),
          msg("outbound", 700, "So glad to hear it, Aisha. Reply here any time if you need anything during the contract.", author="Lisa")],
         stage="placed", status="resolved", unread=False, assignee="Lisa",
         fields={"specialty": v("med_surg", 0.97, "med surg contract"),
                 "license_state": v("IN", 0.95, "Indiana compact license"),
                 "compact_license": v(True, 0.95, "compact license"),
                 "years_experience": v(5, 0.95, "5 years med surg"),
                 "available_date": v("2026-08-24", 0.95, "Available August 24"),
                 "certifications": v(["BLS"], 0.9, "BLS"),
                 "shift_preference": v("nights", 0.95, "nights")}),
    conv("ns_10", "email", "Beatrice Haddad", "b.haddad@prairieview.example.org",
         "Facility: 2 per diem med surg RNs, weekend days",
         [msg("inbound", 180, "Hello, I am the staffing coordinator at Prairie View Medical Center in Champaign. We are short on our med surg unit and need 2 RNs for weekend day shifts, per diem, through the end of the year, starting as soon as possible. BLS required. Please email me back or call 217 555 0129.")],
         priority="high",
         fields={"specialty": v("med_surg", 0.95, "med surg unit"),
                 "license_state": v("IL", 0.6, "Champaign"),
                 "compact_license": UNKNOWN,
                 "years_experience": UNKNOWN,
                 "available_date": v("2026-08-26", 0.5, "as soon as possible"),
                 "certifications": v(["BLS"], 0.9, "BLS required"),
                 "shift_preference": v("days", 0.9, "weekend day shifts")},
         drafts={"reply": "Hi Beatrice, thank you for reaching out. I have passed your request for 2 per diem med surg RNs on weekend days to our staffing team, and someone will call you today to go over the unit and start dates. Is there a time this afternoon that works best?"},
         tricky="facility request: per diem, treated as a lead"),
    conv("ns_11", "web_form", "Jordan Sato", "jordan.sato@example.com",
         "Remote telehealth triage from Texas?",
         [msg("inbound", 6000, "Hi, I am an RN in Texas, 3 years in a call center doing telephone triage. Looking for a fully remote telehealth position, I cannot relocate. BLS current. Available now, days only."),
          msg("outbound", 5900, "Hi Jordan, thanks for reaching out. We place nurses in bedside contracts at hospitals and clinics in the Midwest and do not have remote telehealth roles, so we do not have a match for your background right now. We keep every application on file and will reach out if that changes.", author="Kwame")],
         stage="not_a_fit", status="resolved", unread=False, assignee="Kwame",
         fields={"specialty": v("other", 0.9, "telephone triage"),
                 "license_state": v("TX", 0.95, "RN in Texas"),
                 "compact_license": UNKNOWN,
                 "years_experience": v(3, 0.95, "3 years"),
                 "available_date": v("2026-08-22", 0.7, "Available now"),
                 "certifications": v(["BLS"], 0.9, "BLS current"),
                 "shift_preference": v("days", 0.9, "days only")},
         tricky="remote only: not a fit"),
    conv("ns_12", "sms", "Lena Reyes", "+1 (563) 555-0117",
         "Text: ICU RN, compact, nights, available Sept 1",
         [msg("inbound", 35, "hi im an icu rn 10 yrs, compact license out of iowa, ccrn acls bls. available sept 1, nights only. anything in the quad cities or chicago?")],
         priority="high",
         fields={"specialty": v("icu", 0.97, "icu rn"),
                 "license_state": v("IA", 0.9, "out of iowa"),
                 "compact_license": v(True, 0.95, "compact license"),
                 "years_experience": v(10, 0.95, "10 yrs"),
                 "available_date": v("2026-09-01", 0.95, "available sept 1"),
                 "certifications": v(["CCRN", "ACLS", "BLS"], 0.9, "ccrn acls bls"),
                 "shift_preference": v("nights", 0.95, "nights only")},
         drafts={"reply": "Hi Lena, thanks for reaching out, and 10 years in the ICU with CCRN and a compact license is a strong background. A recruiter can go over the Quad Cities and Chicago on a 15 minute screening call. What days and times work for you?"},
         tricky="compact license: the Multi-state and Hot flags both fire"),
    conv("ns_13", "indeed", "Chris Abara", "indeed:chris.abara",
         "Indeed: LPN, 2 years long term care, Wisconsin",
         [msg("inbound", 900, "Applying through Indeed. I am an LPN with 2 years in long term care in Wisconsin, license is Wisconsin only. BLS. Looking for something closer to Milwaukee, could start mid September, either shift is fine.")],
         fields={"specialty": v("other", 0.9, "LPN with 2 years in long term care"),
                 "license_state": v("WI", 0.95, "license is Wisconsin only"),
                 "compact_license": v(False, 0.7, "Wisconsin only"),
                 "years_experience": v(2, 0.95, "2 years"),
                 "available_date": v("2026-09-15", 0.6, "mid September"),
                 "certifications": v(["BLS"], 0.9, "BLS"),
                 "shift_preference": v("either", 0.9, "either shift is fine")},
         drafts={"reply": "Hi Chris, thanks for applying, and thank you for the detail on your license. A recruiter can go over what is near Milwaukee for an LPN with long term care experience on a 15 minute screening call. What days and times work for you?"}),
    conv("ns_14", "facebook_leads", "Nadia Quinn", "fb:nadia.quinn",
         "Facebook lead: ICU RN, first time traveling",
         [msg("inbound", 1000, "Lead form: Nadia Quinn. Specialty: ICU. Years: 3. State: Michigan (compact). Certs: BLS, ACLS. Available: early October. Shift: nights. Note: interested in 8 week contracts, first time traveling.")],
         fields={"specialty": v("icu", 0.97, "Specialty: ICU"),
                 "license_state": v("MI", 0.95, "Michigan"),
                 "compact_license": v(True, 0.9, "Michigan (compact)"),
                 "years_experience": v(3, 0.95, "Years: 3"),
                 "available_date": v("2026-10-05", 0.5, "early October"),
                 "certifications": v(["BLS", "ACLS"], 0.95, "BLS, ACLS"),
                 "shift_preference": v("nights", 0.95, "Shift: nights")},
         drafts={"reply": "Hi Nadia, thanks for reaching out, and welcome to the idea of traveling. A recruiter can walk you through how a first contract works on a 15 minute screening call. What days and times work for you?"}),
    conv("ns_15", "referral", "Victor Ivers", "+1 (219) 555-0137",
         "Referral from Aisha Lindqvist: ER RN, nights",
         [msg("inbound", 4400, "Referral logged by Lisa: Aisha Lindqvist referred her former coworker Victor Ivers, ER RN, 6 years, Indiana license, not sure about compact. ACLS, TNCC, BLS. Wants nights, could start October 1. His number is 219 555 0137."),
          msg("outbound", 4300, "Hi Victor, this is Lisa at Northline Nurse Staffing. Aisha Lindqvist passed along your name and said you might be looking for an ER contract. The first step is a 15 minute screening call; what days and times work for you?", author="Lisa"),
          msg("inbound", 3500, "Hi Lisa, yes Aisha told me about you. Friday morning works."),
          msg("outbound", 3400, "Friday at 10am. I will call you then, Victor.", author="Lisa"),
          msg("note", 3380, "Screening Fri 10am. Confirm compact status and TNCC expiry.", author="Lisa")],
         stage="screening", assignee="Lisa", unread=False,
         fields={"specialty": v("er", 0.95, "ER RN"),
                 "license_state": v("IN", 0.9, "Indiana license"),
                 "compact_license": UNKNOWN,
                 "years_experience": v(6, 0.9, "6 years"),
                 "available_date": v("2026-10-01", 0.9, "start October 1"),
                 "certifications": v(["ACLS", "TNCC", "BLS"], 0.9, "ACLS, TNCC, BLS"),
                 "shift_preference": v("nights", 0.9, "Wants nights")}),
    conv("ns_16", "email", "Elena Sousa", "elena.sousa@example.com",
         "ICU RN with compact, what do you need for credentialing?",
         [msg("inbound", 8700, "Hi, I spoke with Lisa last week about the ICU contract at Riverbend. 11 years ICU, compact license out of Kansas, CCRN, ACLS, BLS. I can start September 21 and I want nights. She said the next step is credentialing, what do you need from me?"),
          msg("outbound", 8600, "Hi Elena, great to hear from you. The credentialing packet is on its way to your email: license verification, two references, immunization records and your certifications. It usually takes 5 to 10 business days once everything is in.", author="Lisa"),
          msg("inbound", 5000, "Sent everything last night. Let me know if anything is missing."),
          msg("outbound", 4900, "Got it all, Elena, thank you. Nothing missing so far. I will update you as soon as it clears.", author="Lisa"),
          msg("note", 4880, "Packet complete Aug 23. Waiting on Kansas verification and one reference.", author="Lisa")],
         stage="credentialing", assignee="Lisa", unread=False,
         fields={"specialty": v("icu", 0.97, "ICU contract"),
                 "license_state": v("KS", 0.9, "out of Kansas"),
                 "compact_license": v(True, 0.95, "compact license"),
                 "years_experience": v(11, 0.95, "11 years ICU"),
                 "available_date": v("2026-09-21", 0.95, "start September 21"),
                 "certifications": v(["CCRN", "ACLS", "BLS"], 0.95, "CCRN, ACLS, BLS"),
                 "shift_preference": v("nights", 0.95, "I want nights")}),
    conv("ns_17", "indeed", "Theo Brennan", "indeed:theo.brennan",
         "Indeed: ER RN, days, Peoria contract",
         [msg("inbound", 40000, "Applying for the ER contract in Peoria. 8 years ER, Illinois license, TNCC, ACLS, BLS, PALS. Available August 17. Days."),
          msg("outbound", 39900, "Hi Theo, thanks for applying. The first step is a 15 minute screening call with a recruiter. What days and times work for you?", author="Kwame"),
          msg("inbound", 39700, "Tomorrow afternoon"),
          msg("outbound", 39600, "Tomorrow at 2pm. Lisa will call you.", author="Kwame"),
          msg("note", 38000, "Screened, strong. Credentialing packet sent.", author="Lisa"),
          msg("note", 25000, "Credentialing clear. Offer accepted, Peoria ER days, starts Aug 17, 13 weeks.", author="Lisa")],
         stage="placed", status="resolved", unread=False, assignee="Lisa",
         fields={"specialty": v("er", 0.97, "ER contract"),
                 "license_state": v("IL", 0.95, "Illinois license"),
                 "compact_license": UNKNOWN,
                 "years_experience": v(8, 0.95, "8 years ER"),
                 "available_date": v("2026-08-17", 0.95, "Available August 17"),
                 "certifications": v(["TNCC", "ACLS", "BLS", "PALS"], 0.95, "TNCC, ACLS, BLS, PALS"),
                 "shift_preference": v("days", 0.9, "Days.")}),
]

TEMPLATE = {
    "key": "nurse_staffing",
    "name": "Nurse staffing agency",
    "tagline": "Candidates from Indeed, email, the apply form and texts; facility requests by email and phone",
    "example_prompt": "Nurse staffing agency. Candidates apply on Indeed, by email and through our web form; facilities request staff by email and phone.",
    "signals": [("nurse staffing", 5), ("staffing", 3), ("nurse", 2), ("indeed", 3),
                ("candidates", 2), ("travel nurse", 4), ("per diem", 3), ("credentialing", 3),
                ("recruit", 2), ("facilities", 1)],
    "must_review": ["pricing"],
    "spec": SPEC,
    "questions": QUESTIONS,
    "personas": ["Kwame", "Lisa"],
    "ladders": LADDERS,
    "sample_inputs": SAMPLE_INPUTS,
    "prompt_examples": ["add a field for whether they will travel",
                        "add a view of ICU nurses available in the next 30 days",
                        "flag anyone whose license is expiring"],
    "conversations": C,
}
