"""Personal injury law firm: Harbor Point Injury Law (fictional), Chicago."""
from ._common import conv, msg, v, UNKNOWN

SPEC = {
    "business": {
        "name": "Harbor Point Injury Law",
        "type": "pi_law_firm",
        "summary": "Personal injury firm taking car accident, slip and fall, and workplace injury cases in Illinois and Indiana. Free consults, contingency fee.",
        "audience": "leads",
    },
    "connectors": [
        {"key": "web_form", "kind": "web_form", "label": "Free consult form", "auto_connect": True},
        {"key": "avvo", "kind": "avvo", "label": "Avvo messages", "auto_connect": True},
        {"key": "gmail", "kind": "gmail", "label": "intake@harborpointlaw.example.com", "auto_connect": True},
        {"key": "sms", "kind": "sms", "label": "Office text line", "auto_connect": True},
        {"key": "google_lsa", "kind": "google_lsa", "label": "Google Local Services", "auto_connect": True},
        {"key": "voicemail", "kind": "voicemail", "label": "After hours voicemail", "auto_connect": False},
        {"key": "facebook_leads", "kind": "facebook_leads", "label": "Facebook Lead Ads", "auto_connect": False},
    ],
    "fields": [
        {"key": "incident_type", "label": "Incident type", "type": "enum",
         "options": ["car_accident", "slip_and_fall", "workplace", "medical", "dog_bite", "other"],
         "hint": "How the person was hurt", "show_in_list": True},
        {"key": "incident_date", "label": "Incident date", "type": "date",
         "hint": "When the injury happened; resolve relative dates against the message date", "show_in_list": True},
        {"key": "has_attorney", "label": "Already has a lawyer", "type": "bool",
         "hint": "Whether they mention another attorney or firm representing them", "show_in_list": True},
        {"key": "injury_severity", "label": "Injury severity", "type": "enum",
         "options": ["minor", "moderate", "serious", "catastrophic"],
         "hint": "ER visit, surgery, hospitalization, fractures imply serious or worse"},
        {"key": "treated", "label": "Got medical treatment", "type": "bool",
         "hint": "Any mention of ER, urgent care, doctor, physical therapy"},
        {"key": "insurance_contact", "label": "Insurer already calling", "type": "bool",
         "hint": "Adjuster calls, settlement offers, recorded statement requests"},
        {"key": "state", "label": "State of incident", "type": "text",
         "hint": "US state abbreviation if mentioned"},
    ],
    "stages": [
        {"key": "new", "label": "New", "tone": "brand"},
        {"key": "contacted", "label": "Contacted", "tone": "info"},
        {"key": "consult_scheduled", "label": "Consult scheduled", "tone": "warn"},
        {"key": "signed", "label": "Signed", "tone": "ok", "terminal": True},
        {"key": "declined", "label": "Declined", "tone": "neutral", "terminal": True},
        {"key": "referred_out", "label": "Referred out", "tone": "neutral", "terminal": True},
    ],
    "views": [
        {"key": "inbox", "name": "All open",
         "filter": {"all": [{"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "needs_reply", "name": "Needs reply",
         "filter": {"all": [{"field": "awaiting_reply", "op": "eq", "value": True}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "serious_no_attorney", "name": "Serious, no lawyer",
         "filter": {"all": [{"field": "f.has_attorney", "op": "neq", "value": True},
                            {"field": "f.injury_severity", "op": "in", "value": ["serious", "catastrophic"]},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "insurer_pressure", "name": "Insurer calling",
         "filter": {"all": [{"field": "f.insurance_contact", "op": "eq", "value": True},
                            {"field": "stage", "op": "in", "value": ["new", "contacted"]}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "sol_watch", "name": "Older than 18 months",
         "filter": {"all": [{"field": "f.incident_date", "op": "older_than_days", "value": 540}]},
         "sort": {"by": "f.incident_date", "dir": "asc"}},
        {"key": "unassigned", "name": "Unassigned",
         "filter": {"all": [{"field": "assignee", "op": "is_empty"},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}},
    ],
    "rules": [
        {"key": "flag_serious", "name": "Serious injuries go to the top",
         "text": "Mark serious or catastrophic injuries as urgent",
         "when": {"all": [{"field": "f.injury_severity", "op": "in", "value": ["serious", "catastrophic"]}]},
         "then": {"type": "set_priority", "value": "urgent"}},
        {"key": "flag_insurer", "name": "Insurer already calling",
         "text": "Flag anyone the insurer has already contacted",
         "when": {"all": [{"field": "f.insurance_contact", "op": "eq", "value": True}]},
         "then": {"type": "flag", "label": "No recorded statement", "tone": "warn"}},
        {"key": "flag_represented", "name": "Already represented",
         "text": "Flag anyone who already has a lawyer",
         "when": {"all": [{"field": "f.has_attorney", "op": "eq", "value": True}]},
         "then": {"type": "flag", "label": "Already represented", "tone": "info"}},
        {"key": "reject_out_of_state", "name": "Outside our states",
         "text": "Auto reject incidents outside IL and IN",
         "when": {"all": [{"field": "f.state", "op": "not_empty"},
                          {"field": "f.state", "op": "not_in", "value": ["IL", "IN"]}]},
         "then": {"type": "auto_reject", "stage": "declined"}},
    ],
    "approval_policy": {"routine": "auto_send", "pricing": "review",
                        "medical_legal": "review", "distress": "review"},
    "tone": {"voice": "warm", "length": "short", "signoff": "Dana at Harbor Point Injury Law",
             "presets": [
                 {"label": "Answer their question", "instruction": "Answer the question they just asked"},
                 {"label": "Offer a consult", "instruction": "Offer a free consult call and ask which times work"},
                 {"label": "Ask what happened", "instruction": "Ask when and where the injury happened and whether they got treatment"},
                 {"label": "Check in", "instruction": "Check in and ask whether they are still interested"}]},
    "agent": {"name": "Dana", "persona": "Intake coordinator at a personal injury firm",
              "intro": "I read every new lead, pull out what matters, and draft the first reply for you to approve."},
    "playbook": "- Free consultation, no fee unless we win.\n- We take cases in Illinois and Indiana only.\n- Never estimate what a case is worth in writing.\n- Tell people not to give recorded statements to insurers until they have talked to an attorney.",
    "guardrails": [
        {"key": "no_legal_advice", "text": "Never state whether someone has a case or what it is worth.",
         "enforce": "never_promise"},
        {"key": "no_recorded_statement", "text": "Advise leads not to give recorded statements to insurers until they speak to an attorney.",
         "enforce": "escalate"},
        {"key": "no_immigration", "text": "Immigration status is asked on the call, never in writing.",
         "enforce": "refuse_field", "patterns": ["immigration", "citizenship", "visa status"],
         "reason": "immigration status",
         "refusal": "I cannot add that. Immigration status is something the attorney asks about on the call, never in writing. I can add fields like the other party's insurer or whether a police report was filed."},
    ],
}

QUESTIONS = [
    {"id": "sources", "kind": "tiles", "multi": True,
     "prompt": "Where do new leads come in?",
     "why": "Each one becomes a connector and a way to filter.",
     "options": ["web_form", "avvo", "gmail", "sms", "google_lsa", "voicemail", "facebook_leads"],
     "default": ["web_form", "avvo", "gmail", "sms", "google_lsa"], "patch": "set_connectors"},
    {"id": "business_name", "kind": "text", "prompt": "What is the firm called?",
     "why": "It goes on every reply.", "default": "Harbor Point Injury Law", "patch": "set_business_name"},
    {"id": "extract_fields", "kind": "chips", "multi": True,
     "prompt": "What should I pull out of every new inquiry?",
     "why": "Each one becomes a column you can sort and filter by.",
     "options": [["incident_type", "Type of injury"], ["incident_date", "When it happened"],
                 ["has_attorney", "Already has a lawyer"], ["injury_severity", "How serious"],
                 ["treated", "Got treatment"], ["insurance_contact", "Insurer calling"],
                 ["state", "State it happened in"]],
     "default": ["incident_type", "incident_date", "has_attorney", "injury_severity",
                 "insurance_contact", "state"], "patch": "pick_fields"},
    {"id": "slices", "kind": "chips", "multi": True,
     "prompt": "Which views do you want on the front of the inbox?",
     "why": "Views are saved filters. You can add more later by typing.",
     "options": [["serious_no_attorney", "Serious, no lawyer"], ["insurer_pressure", "Insurer calling"],
                 ["sol_watch", "Older than 18 months"], ["unassigned", "Unassigned"]],
     "default": ["serious_no_attorney", "insurer_pressure"], "patch": "pick_views"},
    {"id": "approval", "kind": "chips", "multi": False,
     "prompt": "What may I send without you looking first?",
     "why": "Anything about fees, case value, or legal advice always waits for you.",
     "options": [["routine", "Acknowledgements and scheduling"], ["none", "Nothing, I review every reply"]],
     "default": "routine", "patch": "set_approval"},
    {"id": "tone", "kind": "chips", "multi": False, "prompt": "How should replies sound?",
     "why": "Sets the voice for every draft.",
     "options": [["warm", "Warm"], ["plain", "Plain"], ["formal", "Formal"]],
     "default": "warm", "patch": "set_tone"},
]

LADDERS = {
    "reply": [
        (("statute", "limitation", "too late", "deadline", "how long do i have"),
         "Thanks for reaching out, and I understand the time concern. Deadlines depend on the details, so the fastest way to get a clear answer is a free consult with one of our attorneys. What days and times work for you?"),
        (("recorded statement", "adjuster", "insurance called", "insurer", "settlement offer", "they offered"),
         "Thanks for telling me the insurer has been in touch. Please hold off on giving any recorded statement or accepting an offer until you have talked with an attorney. We offer a free consult; what days and times work for you?"),
        (("how much", "worth", "what can i get", "compensation", "fee", "cost", "percentage", "contingency"),
         "Good question. The consult is free and there is no fee unless we win. What a case is worth depends on the details, which is exactly what the attorney will walk through with you. What days and times work for a call?"),
        (("already have a lawyer", "my attorney", "switch lawyers", "another firm", "represented"),
         "Thanks for reaching out. If you are already working with an attorney, an attorney here can talk through your options with you on a short call. What days and times work?"),
        (("hospital", "surgery", "er ", "emergency room", "fracture", "broke", "concussion"),
         "I am sorry to hear how badly you were hurt. Thank you for reaching out. Please keep every record from your treatment. The next step is a free consult with an attorney; what days and times work for you?"),
    ],
    "fallback": "Thanks for reaching out to Harbor Point Injury Law, {who}. I am sorry to hear about your injury. The next step is a free consult with one of our attorneys, and there is no fee unless we win. What days and times work for you?",
    "check_in": "Hi {who}, checking in to see whether you would still like to set up a free consult about your injury. Reply here any time and I will find a time that works.",
    "booking": "Hi {who}, here is the link to book your free consult. Pick any time that suits you, and reply here if none of them work.",
    "thanks": "Thank you, {who}. We will be in touch soon, and you can reply here with any questions.",
    "decline": "Thank you for reaching out, {who}. Unfortunately this is not a matter we can take on, but your local bar association's referral service can connect you with an attorney who handles cases like yours.",
    "ask_missing": "Thanks {who}. To point you to the right attorney, could you tell me when and where it happened, and whether you have seen a doctor?",
}

SAMPLE_INPUTS = [
    {"label": "Sample Avvo message", "source": "avvo",
     "text": "From: Avvo <messages@avvo.example.com>\nSubject: New message from a potential client\n\nName: Renee Castillo\nPractice area: Personal injury\nMessage: I slipped on an unmarked wet floor at a grocery store in Naperville on the 14th and hurt my knee. I went to urgent care the same day. The store manager took my info but nobody has called. Do I have a case?"},
    {"label": "Sample voicemail transcript", "source": "voicemail",
     "text": "Voicemail transcript, 8:12 pm: Hi, my name is Walter Osei, I got rear-ended on the Dan Ryan two days ago, my neck and back are killing me, I have not seen a doctor yet. The other driver's insurance keeps calling me. Please call me back at 312 555 0161."},
]

C = [
    conv("pi_01", "avvo", "Teresa Okafor", "avvo:teresa.okafor",
         "Rear-ended on I-90, neck pain",
         [msg("inbound", 180, "I was rear-ended on I-90 near Elgin last Thursday. My neck has been hurting since and I went to urgent care the next day. I have not talked to anyone yet, the other driver's insurance left a voicemail. Do I need a lawyer for this?")],
         fields={"incident_type": v("car_accident", 0.96, "rear-ended on I-90"),
                 "incident_date": v("2026-08-20", 0.7, "last Thursday"),
                 "has_attorney": v(False, 0.85, "have not talked to anyone yet"),
                 "injury_severity": v("moderate", 0.6, "neck has been hurting"),
                 "treated": v(True, 0.9, "went to urgent care"),
                 "insurance_contact": v(True, 0.85, "the other driver's insurance left a voicemail"),
                 "state": v("IL", 0.8, "I-90 near Elgin")},
         extra_fields={"police_report": UNKNOWN},
         drafts={"reply": "Hi Teresa, thanks for reaching out, and I am sorry about the crash. Please hold off on calling the other driver's insurer back until you have talked with an attorney. We offer a free consult and there is no fee unless we win. What days and times work for you?"}),
    conv("pi_02", "web_form", "Marcus Bell", "marcus.bell@example.com",
         "Fell at work, employer says file workers comp",
         [msg("inbound", 420, "I fell off a ladder at a warehouse job in Gary, IN about two weeks ago and broke my wrist. Had surgery on it. My employer says just file workers comp but a coworker said I might have more than that. No lawyer yet.")],
         fields={"incident_type": v("workplace", 0.95, "fell off a ladder at a warehouse job"),
                 "incident_date": v("2026-08-12", 0.6, "about two weeks ago"),
                 "has_attorney": v(False, 0.9, "No lawyer yet"),
                 "injury_severity": v("serious", 0.9, "broke my wrist. Had surgery"),
                 "treated": v(True, 0.95, "Had surgery on it"),
                 "insurance_contact": UNKNOWN,
                 "state": v("IN", 0.9, "Gary, IN")},
         drafts={"reply": "Hi Marcus, I am sorry to hear about the fall and the surgery. Thank you for reaching out. Please keep every record from your treatment. Workplace injuries can involve more than a workers comp claim, and an attorney here can walk through that with you on a free consult. What days and times work for you?"}),
    conv("pi_03", "sms", "Dana Whitfield", "+1 (773) 555-0114",
         "Dog bite, adjuster wants a statement",
         [msg("inbound", 2900, "Hi, a neighbor's dog bit my daughter on the arm last month, she needed stitches. Their homeowners insurance adjuster wants a recorded statement from me. Should I do it?"),
          msg("outbound", 2800, "Hi Dana, thanks for reaching out, and I am sorry your daughter was hurt. Please hold off on giving any recorded statement until you have talked with an attorney. We offer a free consult; what days and times work for you?", author="Dana"),
          msg("inbound", 90, "Thanks. Tomorrow after 3 works for me.")],
         stage="contacted", assignee="Dana",
         fields={"incident_type": v("dog_bite", 0.97, "a neighbor's dog bit my daughter"),
                 "incident_date": v("2026-07-20", 0.5, "last month"),
                 "has_attorney": v(False, 0.7, ""),
                 "injury_severity": v("moderate", 0.8, "she needed stitches"),
                 "treated": v(True, 0.9, "needed stitches"),
                 "insurance_contact": v(True, 0.95, "adjuster wants a recorded statement"),
                 "state": UNKNOWN},
         drafts={"reply": "Perfect, Dana. I will set up the consult for tomorrow after 3 and send a confirmation with the attorney's name. Reply here if anything changes."}),
    conv("pi_04", "gmail", "Priya Natarajan", "priya.n@example.com",
         "Slip and fall at a restaurant, do I have a case",
         [msg("inbound", 1500, "Hello, I slipped on a wet floor with no sign at a restaurant in Schaumburg on August 2nd and hurt my back. I saw my doctor and I am doing physical therapy. Nobody from the restaurant has followed up. Do I have a case?")],
         fields={"incident_type": v("slip_and_fall", 0.96, "slipped on a wet floor with no sign"),
                 "incident_date": v("2026-08-02", 0.95, "August 2nd"),
                 "has_attorney": v(False, 0.6, ""),
                 "injury_severity": v("moderate", 0.7, "doing physical therapy"),
                 "treated": v(True, 0.95, "saw my doctor and I am doing physical therapy"),
                 "insurance_contact": v(False, 0.6, "Nobody from the restaurant has followed up"),
                 "state": v("IL", 0.85, "Schaumburg")},
         drafts={"reply": "Hi Priya, thanks for reaching out, and I am sorry about your back. Whether there is a case depends on the details, which is exactly what an attorney here will walk through with you on a free consult. Please keep your treatment records and any photos. What days and times work for you?"}),
    conv("pi_05", "google_lsa", "Chris Doyle", "+1 (630) 555-0177",
         "Google call: motorcycle accident, in the hospital",
         [msg("inbound", 45, "Call summary: Caller's brother was in a motorcycle accident on Route 59 on Sunday, currently in the hospital at Edward with a broken leg and a concussion. The other driver ran a red light. Family wants to talk to a lawyer this week.")],
         priority="urgent",
         fields={"incident_type": v("car_accident", 0.9, "motorcycle accident on Route 59"),
                 "incident_date": v("2026-08-23", 0.8, "on Sunday"),
                 "has_attorney": v(False, 0.7, "wants to talk to a lawyer this week"),
                 "injury_severity": v("serious", 0.95, "broken leg and a concussion"),
                 "treated": v(True, 0.95, "in the hospital at Edward"),
                 "insurance_contact": UNKNOWN,
                 "state": v("IL", 0.8, "Route 59")},
         drafts={"reply": "Hi Chris, I am so sorry to hear about your brother. Thank you for reaching out on his behalf. An attorney can meet with the family this week, including at the hospital if that is easier. What day and time work, and what is the best number to reach you?"}),
    conv("pi_06", "web_form", "Lena Sousa", "lena.sousa@example.com",
         "Car accident in Milwaukee, was it my fault",
         [msg("inbound", 600, "I was in a car accident in Milwaukee, WI three weeks ago. The police report says the other driver was at fault. I have whiplash and have been seeing a chiropractor. I do not have a lawyer.")],
         fields={"incident_type": v("car_accident", 0.97, "car accident in Milwaukee"),
                 "incident_date": v("2026-08-05", 0.6, "three weeks ago"),
                 "has_attorney": v(False, 0.95, "I do not have a lawyer"),
                 "injury_severity": v("moderate", 0.7, "whiplash"),
                 "treated": v(True, 0.9, "seeing a chiropractor"),
                 "insurance_contact": UNKNOWN,
                 "state": v("WI", 0.95, "Milwaukee, WI")},
         extra_fields={"police_report": v(True, 0.95, "The police report says")},
         drafts={"reply": "Thank you for reaching out, Lena. Unfortunately we only take cases in Illinois and Indiana, so this is not one we can help with directly. The Wisconsin State Bar's lawyer referral service can connect you with an attorney who handles cases like yours."},
         tricky="out of state: the auto reject rule fires"),
    conv("pi_07", "avvo", "Jordan Kim", "avvo:jordan.kim",
         "Already have a lawyer, want a second opinion",
         [msg("inbound", 3000, "I already have a lawyer for my car accident case but he never calls me back. Can I switch to your firm? Accident was in January in Joliet.")],
         fields={"incident_type": v("car_accident", 0.9, "my car accident case"),
                 "incident_date": v("2026-01-15", 0.5, "in January"),
                 "has_attorney": v(True, 0.97, "I already have a lawyer"),
                 "injury_severity": UNKNOWN,
                 "treated": UNKNOWN,
                 "insurance_contact": UNKNOWN,
                 "state": v("IL", 0.85, "Joliet")},
         drafts={"reply": "Thanks for reaching out, Jordan. If you are already working with an attorney, an attorney here can talk through your options with you on a short call, including what switching would involve. What days and times work?"},
         tricky="represented lead, medical_legal category"),
    conv("pi_08", "sms", "Ana Ferreira", "+1 (312) 555-0142",
         "How much is your fee",
         [msg("inbound", 130, "How much do you charge? I hurt my shoulder in a fender bender in Oak Park last week")],
         fields={"incident_type": v("car_accident", 0.9, "fender bender in Oak Park"),
                 "incident_date": v("2026-08-19", 0.6, "last week"),
                 "has_attorney": UNKNOWN,
                 "injury_severity": v("minor", 0.6, "hurt my shoulder in a fender bender"),
                 "treated": UNKNOWN,
                 "insurance_contact": UNKNOWN,
                 "state": v("IL", 0.85, "Oak Park")},
         drafts={"reply": "Hi Ana, good question. The consult is free and there is no fee unless we win. What a case is worth depends on the details, which is exactly what the attorney will walk through with you. What days and times work for a call?"},
         tricky="pricing question: review before sending"),
    conv("pi_09", "gmail", "Beatrice Lang", "b.lang@example.org",
         "Referral from Dr. Alvarez, workplace back injury",
         [msg("inbound", 4300, "Hello, Dr. Alvarez at Lakeview Family Medicine suggested I contact you. I injured my back lifting at a distribution center in Hammond, IN in June. I have been off work since and my employer's insurer stopped paying. I have not hired anyone."),
          msg("outbound", 4200, "Hi Beatrice, thank you for reaching out, and thank you to Dr. Alvarez. I am sorry about your back. An attorney here can walk through the workplace injury and the insurer's decision with you on a free consult. What days and times work for you?", author="Marcus"),
          msg("inbound", 4000, "Any weekday morning is fine."),
          msg("outbound", 3900, "You are booked for Thursday at 10am with Marcus Reyes. A confirmation is on its way.", author="Marcus"),
          msg("note", 3880, "Conflict check clear. Employer is Northline Distribution.", author="Marcus")],
         stage="consult_scheduled", assignee="Marcus", unread=False,
         fields={"incident_type": v("workplace", 0.95, "injured my back lifting at a distribution center"),
                 "incident_date": v("2026-06-15", 0.5, "in June"),
                 "has_attorney": v(False, 0.95, "I have not hired anyone"),
                 "injury_severity": v("serious", 0.7, "off work since"),
                 "treated": v(True, 0.6, "Dr. Alvarez"),
                 "insurance_contact": v(True, 0.85, "employer's insurer stopped paying"),
                 "state": v("IN", 0.95, "Hammond, IN")}),
    conv("pi_10", "web_form", "Sam Patel", "sam.patel@example.com",
         "Bike hit by car door, minor scrapes",
         [msg("inbound", 5200, "A parked driver opened their door into my bike lane on Milwaukee Ave last month. Scrapes and a bruised hip, nothing broken. Just wondering if it is worth pursuing."),
          msg("outbound", 5100, "Hi Sam, thanks for reaching out, and I am glad it was not worse. Whether it is worth pursuing depends on the details, and an attorney can tell you honestly on a free consult. What days and times work?", author="Dana"),
          msg("inbound", 4800, "I think I will let it go, thanks anyway.")],
         stage="declined", status="resolved", unread=False, assignee="Dana",
         fields={"incident_type": v("car_accident", 0.8, "opened their door into my bike lane"),
                 "incident_date": v("2026-07-20", 0.5, "last month"),
                 "has_attorney": v(False, 0.6, ""),
                 "injury_severity": v("minor", 0.9, "Scrapes and a bruised hip, nothing broken"),
                 "treated": v(False, 0.5, ""),
                 "insurance_contact": UNKNOWN,
                 "state": v("IL", 0.8, "Milwaukee Ave")}),
    conv("pi_11", "avvo", "Ruth Adler", "avvo:ruth.adler",
         "Medical mistake during surgery",
         [msg("inbound", 700, "My husband had a routine gallbladder surgery in Evanston in March and the surgeon nicked something, he needed two more surgeries and was in the ICU. We think this was a mistake. We have not talked to any lawyer.")],
         priority="urgent",
         fields={"incident_type": v("medical", 0.95, "the surgeon nicked something"),
                 "incident_date": v("2026-03-15", 0.5, "in March"),
                 "has_attorney": v(False, 0.95, "have not talked to any lawyer"),
                 "injury_severity": v("catastrophic", 0.9, "two more surgeries and was in the ICU"),
                 "treated": v(True, 0.95, "two more surgeries"),
                 "insurance_contact": UNKNOWN,
                 "state": v("IL", 0.85, "Evanston")},
         drafts={"reply": "Hi Ruth, I am so sorry about what your husband has been through. Thank you for reaching out. Please keep every record and discharge summary. An attorney who handles medical cases can meet with you both on a free consult. What days and times work for you?"}),
    conv("pi_12", "sms", "Miguel Torres", "+1 (708) 555-0133",
         "Statute of limitations question",
         [msg("inbound", 25, "My accident was in September 2024 in Cicero. Someone told me I only have two years, is it too late??")],
         priority="high",
         fields={"incident_type": v("other", 0.5, "My accident"),
                 "incident_date": v("2024-09-15", 0.6, "September 2024"),
                 "has_attorney": UNKNOWN,
                 "injury_severity": UNKNOWN,
                 "treated": UNKNOWN,
                 "insurance_contact": UNKNOWN,
                 "state": v("IL", 0.85, "Cicero")},
         drafts={"reply": "Hi Miguel, thanks for reaching out, and I understand the time concern. Deadlines depend on the details, so the fastest way to get a clear answer is a free consult with one of our attorneys, and given the date I would set it up this week. What days and times work for you?"},
         tricky="deadline pressure: urgent, legal content stays in review"),
    conv("pi_13", "google_lsa", "Hannah Cole", "+1 (847) 555-0128",
         "Google call: rideshare passenger injured",
         [msg("inbound", 9000, "Call summary: Caller was a rideshare passenger in a crash on Lake Shore Drive in July. Sprained wrist, treated at urgent care. Rideshare company's insurer contacted her. No attorney."),
          msg("outbound", 8900, "Hi Hannah, thanks for calling us. Please hold off on giving the rideshare insurer any recorded statement until you have talked with an attorney. We offer a free consult; what days and times work for you?", author="Dana"),
          msg("inbound", 8700, "Friday afternoon works"),
          msg("outbound", 8600, "You are booked for Friday at 2pm. A confirmation is on its way.", author="Dana"),
          msg("inbound", 2000, "We signed the agreement on Friday, thank you!")],
         stage="signed", status="resolved", unread=False, assignee="Dana",
         fields={"incident_type": v("car_accident", 0.9, "rideshare passenger in a crash"),
                 "incident_date": v("2026-07-10", 0.5, "in July"),
                 "has_attorney": v(False, 0.9, "No attorney"),
                 "injury_severity": v("minor", 0.8, "Sprained wrist"),
                 "treated": v(True, 0.9, "treated at urgent care"),
                 "insurance_contact": v(True, 0.9, "Rideshare company's insurer contacted her"),
                 "state": v("IL", 0.9, "Lake Shore Drive")}),
    conv("pi_14", "gmail", "Devon Marsh", "devon.marsh@example.com",
         "Kid hurt on a playground at daycare",
         [msg("inbound", 260, "My son broke his arm on a broken piece of playground equipment at his daycare in Aurora last Tuesday. The daycare has not given us any incident report. He had a cast put on at the ER. We do not have a lawyer.")],
         priority="urgent",
         fields={"incident_type": v("other", 0.8, "broken piece of playground equipment"),
                 "incident_date": v("2026-08-18", 0.7, "last Tuesday"),
                 "has_attorney": v(False, 0.95, "We do not have a lawyer"),
                 "injury_severity": v("serious", 0.85, "broke his arm"),
                 "treated": v(True, 0.95, "cast put on at the ER"),
                 "insurance_contact": v(False, 0.6, "has not given us any incident report"),
                 "state": v("IL", 0.85, "Aurora")},
         drafts={"reply": "Hi Devon, I am sorry to hear about your son's arm. Thank you for reaching out. Please keep the ER records and ask the daycare in writing for the incident report. An attorney here can walk through this with you on a free consult. What days and times work for you?"}),
    conv("pi_15", "web_form", "Aisha Okonkwo", "aisha.o@example.com",
         "Slip on ice outside apartment building",
         [msg("inbound", 14000, "I slipped on ice that was never salted outside my apartment building in Rogers Park back in February and fractured my ankle. I had surgery. My landlord's insurance offered me $4,000 and wants me to sign."),
          msg("outbound", 13900, "Hi Aisha, thank you for reaching out, and I am sorry about your ankle. Please do not sign anything or accept the offer until you have talked with an attorney. We offer a free consult; what days and times work for you?", author="Marcus"),
          msg("inbound", 13700, "Monday morning?"),
          msg("outbound", 13600, "Monday at 9am works. A confirmation is on its way.", author="Marcus")],
         stage="consult_scheduled", assignee="Marcus", unread=False,
         fields={"incident_type": v("slip_and_fall", 0.95, "slipped on ice"),
                 "incident_date": v("2026-02-10", 0.5, "back in February"),
                 "has_attorney": v(False, 0.7, ""),
                 "injury_severity": v("serious", 0.9, "fractured my ankle. I had surgery"),
                 "treated": v(True, 0.95, "I had surgery"),
                 "insurance_contact": v(True, 0.95, "landlord's insurance offered me $4,000"),
                 "state": v("IL", 0.85, "Rogers Park")}),
    conv("pi_16", "sms", "Unknown", "+1 (224) 555-0190",
         "Text: got hit, need help",
         [msg("inbound", 12, "got hit by a truck on 294 this morning im ok but my car is totaled and my back hurts. do you guys do this")],
         priority="high",
         fields={"incident_type": v("car_accident", 0.95, "got hit by a truck on 294"),
                 "incident_date": v("2026-08-26", 0.9, "this morning"),
                 "has_attorney": UNKNOWN,
                 "injury_severity": v("moderate", 0.5, "my back hurts"),
                 "treated": v(False, 0.6, "im ok"),
                 "insurance_contact": UNKNOWN,
                 "state": v("IL", 0.7, "294")},
         drafts={"reply": "Hi, yes we do, and I am glad you are okay. Thanks for reaching out. Even if you feel fine, it is worth getting checked by a doctor today. The next step is a free consult with an attorney, and there is no fee unless we win. What days and times work for you, and what name should I use?"}),
]

TEMPLATE = {
    "key": "pi_law_firm",
    "name": "Personal injury law firm",
    "tagline": "Free consult leads from Avvo, the site form, texts, email and Google",
    "example_prompt": "Personal injury law firm. Leads come from our website form, Avvo, Google calls, texts, and voicemail.",
    "signals": [("injury", 3), ("accident", 3), ("law firm", 3), ("attorney", 2),
                ("lawyer", 2), ("slip and fall", 3), ("personal injury", 5), ("avvo", 4),
                ("consult", 1), ("case", 1)],
    "must_review": ["medical_legal", "pricing"],
    "spec": SPEC,
    "questions": QUESTIONS,
    "personas": ["Dana", "Marcus"],
    "ladders": LADDERS,
    "sample_inputs": SAMPLE_INPUTS,
    "prompt_examples": ["add a field for whether a police report was filed",
                        "add a view of slip and falls from this month",
                        "flag anyone mentioning a court date"],
    "conversations": C,
}
