"""Property management leasing: Marlow Property Group (fictional), Chicago."""
from ._common import conv, msg, v, UNKNOWN

SPEC = {
    "business": {
        "name": "Marlow Property Group",
        "type": "property_leasing",
        "summary": "Property management company with about 300 units across a few buildings in Chicago. Leasing leads, tours, applications and the occasional tenant text.",
        "audience": "leads",
    },
    "connectors": [
        {"key": "zillow", "kind": "zillow", "label": "Zillow rental leads", "auto_connect": True},
        {"key": "web_form", "kind": "web_form", "label": "Website inquiry form", "auto_connect": True},
        {"key": "sms", "kind": "sms", "label": "Leasing text line", "auto_connect": True},
        {"key": "voicemail", "kind": "voicemail", "label": "Leasing office voicemail", "auto_connect": True},
        {"key": "email", "kind": "email", "label": "leasing@marlowpg.example.com", "auto_connect": True},
        {"key": "facebook_leads", "kind": "facebook_leads", "label": "Facebook Lead Ads", "auto_connect": False},
    ],
    "fields": [
        {"key": "listing", "label": "Listing", "type": "text",
         "hint": "The unit or building they asked about", "show_in_list": True},
        {"key": "bedrooms", "label": "Bedrooms", "type": "number",
         "hint": "Number of bedrooms they want; a studio is 0"},
        {"key": "move_in_date", "label": "Move-in date", "type": "date",
         "hint": "When they want to move in; resolve relative dates against the message date", "show_in_list": True},
        {"key": "budget", "label": "Monthly budget", "type": "number",
         "hint": "The most they say they can pay per month"},
        {"key": "pets", "label": "Pets", "type": "enum",
         "options": ["none", "dog", "cat", "other"],
         "hint": "Any pet they mention; other covers rabbits, birds, reptiles and the rest"},
        {"key": "occupants", "label": "Occupants", "type": "number",
         "hint": "How many people will live there"},
        {"key": "tour_requested", "label": "Wants a tour", "type": "bool",
         "hint": "Whether they ask to see, visit or tour a unit", "show_in_list": True},
        {"key": "urgency", "label": "Urgency", "type": "enum",
         "options": ["low", "normal", "high"],
         "hint": "High only for maintenance emergencies like no heat, a gas smell or flooding"},
    ],
    "stages": [
        {"key": "new", "label": "New", "tone": "brand"},
        {"key": "tour_scheduled", "label": "Tour scheduled", "tone": "warn"},
        {"key": "applied", "label": "Applied", "tone": "info"},
        {"key": "leased", "label": "Leased", "tone": "ok", "terminal": True},
        {"key": "not_a_fit", "label": "Not a fit", "tone": "neutral", "terminal": True},
    ],
    "views": [
        {"key": "inbox", "name": "All open",
         "filter": {"all": [{"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "needs_reply", "name": "Needs reply",
         "filter": {"all": [{"field": "awaiting_reply", "op": "eq", "value": True}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "tours", "name": "Tours booked",
         "filter": {"all": [{"field": "stage", "op": "eq", "value": "tour_scheduled"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "moving_soon", "name": "Moving within 2 weeks",
         "filter": {"all": [{"field": "f.move_in_date", "op": "within_days", "value": 14},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "f.move_in_date", "dir": "asc"}, "pinned": True},
        {"key": "pet_questions", "name": "Pet questions",
         "filter": {"all": [{"field": "f.pets", "op": "in", "value": ["dog", "cat", "other"]}]},
         "sort": {"by": "last_message_at", "dir": "desc"}},
        {"key": "ghosted", "name": "Ghosted after tour",
         "filter": {"all": [{"field": "stage", "op": "eq", "value": "tour_scheduled"},
                            {"field": "last_message_at", "op": "older_than_days", "value": 3}]},
         "sort": {"by": "last_message_at", "dir": "asc"}},
    ],
    "rules": [
        {"key": "moving_soon_high", "name": "Moving within two weeks",
         "text": "Mark anyone moving within 14 days as high priority",
         "when": {"all": [{"field": "f.move_in_date", "op": "within_days", "value": 14}]},
         "then": {"type": "set_priority", "value": "high"}},
        {"key": "emergency_urgent", "name": "Emergencies go to the top",
         "text": "Mark maintenance emergencies as urgent",
         "when": {"all": [{"field": "f.urgency", "op": "eq", "value": "high"}]},
         "then": {"type": "set_priority", "value": "urgent"}},
        {"key": "flag_maintenance", "name": "Maintenance emergency",
         "text": "Flag maintenance emergencies",
         "when": {"all": [{"field": "f.urgency", "op": "eq", "value": "high"}]},
         "then": {"type": "flag", "label": "Maintenance", "tone": "danger"}},
        {"key": "flag_pets", "name": "Pet policy check",
         "text": "Flag anyone with a dog or cat so the building's pet policy gets checked",
         "when": {"all": [{"field": "f.pets", "op": "in", "value": ["dog", "cat"]}]},
         "then": {"type": "flag", "label": "Pet policy", "tone": "info"}},
    ],
    "approval_policy": {"routine": "auto_send", "pricing": "review",
                        "medical_legal": "review", "distress": "review"},
    "tone": {"voice": "warm", "length": "short", "signoff": "Sam at Marlow Property Group",
             "presets": [
                 {"label": "Answer their question", "instruction": "Answer the question they just asked"},
                 {"label": "Offer a tour", "instruction": "Offer a tour Monday to Saturday and ask which days work"},
                 {"label": "Ask about move-in", "instruction": "Ask when they want to move in and how many bedrooms they need"},
                 {"label": "Check in", "instruction": "Check in and ask whether they are still interested"}]},
    "agent": {"name": "Sam", "persona": "Leasing coordinator at a property management company",
              "intro": "I read every new lead, pull out the listing, move-in date and pets, and draft the first reply for you to approve."},
    "playbook": "- Every applicant is screened with the same written criteria.\n- Tours run Monday to Saturday, 9am to 6pm.\n- Never say whether an applicant will or will not be approved.\n- Maintenance emergencies (no heat, gas smell, flooding) go to the emergency line: (312) 555-0100.",
    "guardrails": [
        {"key": "fair_housing", "text": "Never collect or sort by familial status, race, religion, national origin, disability, sex or similar characteristics.",
         "enforce": "refuse_field",
         "patterns": ["familial", "family status", "children", "kids", "family friendly", "pregnan",
                      "race", "religion", "national origin", "nationality", "disability", "marital",
                      "sex", "gender", "sexual orientation", "source of income"],
         "reason": "familial status",
         "refusal": "I cannot add that. Fair housing law does not allow screening on familial status, which covers whether someone has children or is pregnant, or on race, religion, national origin, disability or similar characteristics. I can add fields that apply to every applicant the same way, like desired move-in date, number of occupants, or pets."},
        {"key": "no_approval_promise", "text": "Never say whether an applicant will be approved, and never suggest a unit is unsuitable for a person.",
         "enforce": "never_promise"},
    ],
}

QUESTIONS = [
    {"id": "sources", "kind": "tiles", "multi": True,
     "prompt": "Where do leasing leads come in?",
     "why": "Each one becomes a connector and a way to filter.",
     "options": ["zillow", "web_form", "sms", "voicemail", "email", "facebook_leads"],
     "default": ["zillow", "web_form", "sms", "voicemail", "email"], "patch": "set_connectors"},
    {"id": "business_name", "kind": "text", "prompt": "What is the company called?",
     "why": "It goes on every reply.", "default": "Marlow Property Group", "patch": "set_business_name"},
    {"id": "extract_fields", "kind": "chips", "multi": True,
     "prompt": "What should I pull out of every new inquiry?",
     "why": "Each one becomes a column you can sort and filter by.",
     "options": [["listing", "Which listing"], ["bedrooms", "Bedrooms"],
                 ["move_in_date", "Move-in date"], ["budget", "Monthly budget"],
                 ["pets", "Pets"], ["occupants", "Occupants"],
                 ["tour_requested", "Wants a tour"], ["urgency", "Urgency"]],
     "default": ["listing", "bedrooms", "move_in_date", "pets", "tour_requested", "urgency"],
     "patch": "pick_fields"},
    {"id": "slices", "kind": "chips", "multi": True,
     "prompt": "Which views do you want on the front of the inbox?",
     "why": "Views are saved filters. You can add more later by typing.",
     "options": [["tours", "Tours booked"], ["moving_soon", "Moving within 2 weeks"],
                 ["pet_questions", "Pet questions"], ["ghosted", "Ghosted after tour"]],
     "default": ["tours", "moving_soon"], "patch": "pick_views"},
    {"id": "approval", "kind": "chips", "multi": False,
     "prompt": "What may I send without you looking first?",
     "why": "Anything about rent, deposits, or whether someone will be approved always waits for you.",
     "options": [["routine", "Availability and tour scheduling"], ["none", "Nothing, I review every reply"]],
     "default": "routine", "patch": "set_approval"},
    {"id": "tone", "kind": "chips", "multi": False, "prompt": "How should replies sound?",
     "why": "Sets the voice for every draft.",
     "options": [["warm", "Warm"], ["plain", "Plain"], ["formal", "Formal"]],
     "default": "warm", "patch": "set_tone"},
]

LADDERS = {
    "reply": [
        (("no heat", "gas", "smell", "flood", "leak", "water everywhere", "emergency", "no power"),
         "I am sorry, that needs attention right now. Please call the emergency line at (312) 555-0100 so the on-call tech can reach you directly. I have paged maintenance, and you can reply here if you cannot get through."),
        (("tour", "see it", "showing", "visit", "come by", "look at", "walk through"),
         "Thanks for reaching out. I would be glad to show you the unit; tours run Monday to Saturday, so tell me which days and times suit you and I will confirm a time."),
        (("dog", "cat", "pet", "rabbit", "animal"),
         "Thanks for asking. Pet policies differ by building, so I will confirm what applies to the listing you asked about and get back to you today. Would you like to set up a tour in the meantime?"),
        (("approved", "approve", "qualify", "credit", "income", "background", "application"),
         "Thanks for reaching out. Every applicant is screened with the same written criteria, so I cannot say ahead of time how an application will come out, but I am happy to send you the application link and answer questions about the process. Would you like to see the unit first?"),
        (("rent", "price", "how much", "deposit", "fee", "negotiable", "special"),
         "Thanks for asking. Rent and deposit questions go to our leasing manager, so I will confirm the current numbers for that unit and get back to you today. In the meantime, would you like to tour it? Tours run Monday to Saturday."),
        (("available", "availability", "still open", "vacant", "opening up"),
         "Thanks for reaching out. I will confirm availability for that listing and your move-in date and let you know today. If it is open, I can set up a tour Monday to Saturday; which days suit you?"),
    ],
    "fallback": "Thanks for reaching out to Marlow Property Group, {who}. I would be glad to help you find the right unit. Tell me which building or listing you are interested in and when you are hoping to move, and I can set up a tour Monday to Saturday.",
    "check_in": "Hi {who}, checking in to see whether you are still looking. If you would like to see the unit again or have questions about the application, reply here any time.",
    "booking": "Hi {who}, here is the link to book a tour. Tours run Monday to Saturday; pick any time that suits you and reply here if none of them work.",
    "thanks": "Thank you, {who}. I will be in touch soon, and you can reply here with any questions.",
    "decline": "Thank you for reaching out, {who}. Unfortunately we do not have anything that matches what you are looking for right now, but reply here any time and I will let you know if that changes.",
    "ask_missing": "Thanks {who}. To point you to the right unit, could you tell me which building or listing you are interested in, when you are hoping to move, and how many bedrooms you need?",
}

SAMPLE_INPUTS = [
    {"label": "Sample Zillow lead email", "source": "zillow",
     "text": "From: Zillow <leads@zillow.example.com>\nSubject: New rental lead for Belden Court #2C, 1420 W Belden Ave\n\nName: Nadia Haddad\nPhone: (773) 555-0188\nEmail: nadia.haddad@example.com\nMove-in: 09/15/2026\nMessage: Hi, I am interested in the 2 bedroom at Belden Court #2C. Is it still available and could I see it this weekend? I have one cat. Thanks!"},
    {"label": "Sample voicemail transcript", "source": "voicemail",
     "text": "Voicemail transcript, 6:05 pm: Hi, this is Victor Moreau, I drove past Rowan Lofts today and saw the sign out front. Do you have any two bedrooms opening up in October? I would like to take a look this week if I can. My number is 773 555 0166. Thanks."},
]

C = [
    conv("pl_01", "zillow", "Beatrice Sousa", "beatrice.sousa@example.com",
         "Zillow: Belden Court #3B, moving September 5",
         [msg("inbound", 150, "From: Zillow <leads@zillow.example.com>\nSubject: New rental lead for Belden Court #3B, 1420 W Belden Ave\n\nName: Beatrice Sousa\nPhone: (773) 555-0121\nEmail: beatrice.sousa@example.com\nMove-in: 09/05/2026\nMessage: Hi, I am interested in the 2 bedroom at Belden Court #3B. My lease ends September 5 so I would need to move in by then. It is just my partner and I, no pets. Can I see it this week?")],
         priority="high",
         fields={"listing": v("Belden Court #3B", 0.95, "Belden Court #3B"),
                 "bedrooms": v(2, 0.95, "2 bedroom"),
                 "move_in_date": v("2026-09-05", 0.95, "September 5"),
                 "budget": UNKNOWN,
                 "pets": v("none", 0.9, "no pets"),
                 "occupants": v(2, 0.85, "my partner and I"),
                 "tour_requested": v(True, 0.9, "Can I see it this week"),
                 "urgency": v("normal", 0.7, "")},
         drafts={"reply": "Hi Beatrice, thanks for reaching out about Belden Court #3B. I can show you the unit this week; tours run Monday to Saturday, so tell me which days and times suit you. A September 5 move-in is soon, so I will also confirm availability for that date and let you know today."},
         tricky="move-in within 14 days: the priority rule fires"),
    conv("pl_02", "web_form", "Kwame Osei", "kwame.osei@example.com",
         "Is Rowan Lofts family friendly?",
         [msg("inbound", 420, "Hi, I am looking at the 3 bedroom at Rowan Lofts. Is the building family friendly, are there lots of kids? Also what is the parking situation. There would be 3 of us moving in around October 1.")],
         fields={"listing": v("Rowan Lofts", 0.95, "Rowan Lofts"),
                 "bedrooms": v(3, 0.95, "3 bedroom"),
                 "move_in_date": v("2026-10-01", 0.85, "October 1"),
                 "budget": UNKNOWN,
                 "pets": UNKNOWN,
                 "occupants": v(3, 0.9, "3 of us"),
                 "tour_requested": UNKNOWN,
                 "urgency": v("normal", 0.7, "")},
         drafts={"reply": "Hi Kwame, thanks for reaching out about the 3 bedroom at Rowan Lofts. I would be glad to show you the unit and go over parking and the building amenities in person; tours run Monday to Saturday. Tell me which days suit you and I will confirm availability for an October 1 move-in."},
         tricky="fair housing: nothing about children is extracted, and the draft answers about the unit, tours and parking only"),
    conv("pl_03", "sms", "Elena Varga", "+1 (312) 555-0164",
         "No heat in 4C at Carver Place",
         [msg("inbound", 8, "no heat in 4C at Carver Place and it's 20 degrees, the thermostat is doing nothing. what do I do")],
         priority="urgent",
         fields={"listing": v("Carver Place 4C", 0.9, "4C at Carver Place"),
                 "bedrooms": UNKNOWN,
                 "move_in_date": UNKNOWN,
                 "budget": UNKNOWN,
                 "pets": UNKNOWN,
                 "occupants": UNKNOWN,
                 "tour_requested": UNKNOWN,
                 "urgency": v("high", 0.97, "no heat")},
         drafts={"reply": "Elena, I am sorry, that needs attention right now. Please call the emergency line at (312) 555-0100 so the on-call tech can reach you directly. I have paged maintenance about the heat in 4C, and you can reply here if you cannot get through."},
         tricky="maintenance emergency: urgent, and the distress category stays in review"),
    conv("pl_04", "zillow", "Diego Delgado", "diego.delgado@example.com",
         "Zillow: two dogs, 1BR at The Larkin",
         [msg("inbound", 610, "From: Zillow <leads@zillow.example.com>\nSubject: New rental lead for The Larkin, 615 S Larkin St\n\nName: Diego Delgado\nPhone: (630) 555-0152\nEmail: diego.delgado@example.com\nMove-in: 10/01/2026\nMessage: Is the 1 bedroom at The Larkin dog friendly? I have two dogs, both under 30 pounds. Looking to move October 1st and I would love to see the place.")],
         fields={"listing": v("The Larkin, 1 bedroom", 0.9, "1 bedroom at The Larkin"),
                 "bedrooms": v(1, 0.95, "1 bedroom"),
                 "move_in_date": v("2026-10-01", 0.9, "October 1st"),
                 "budget": UNKNOWN,
                 "pets": v("dog", 0.97, "two dogs"),
                 "occupants": UNKNOWN,
                 "tour_requested": v(True, 0.85, "would love to see the place"),
                 "urgency": v("normal", 0.7, "")},
         drafts={"reply": "Hi Diego, thanks for asking about the 1 bedroom at The Larkin. Pet policies differ by building, so I will confirm what applies to two dogs at The Larkin and get back to you today. In the meantime I would be glad to show you the unit; tours run Monday to Saturday, so tell me which days suit you."},
         tricky="pet policy flag; the draft does not promise the dogs are allowed"),
    conv("pl_05", "sms", "Harper Quinn", "+1 (773) 555-0183",
         "Studio at Rowan Lofts, toured Friday",
         [msg("inbound", 10000, "Hi this is Harper, I saw the studio at Rowan Lofts on your site. Could I see it Friday afternoon? Hoping to move mid September."),
          msg("outbound", 9900, "Hi Harper, Friday works. Does 4pm suit you? I will meet you in the lobby at Rowan Lofts.", author="Sam"),
          msg("inbound", 7300, "4 works, see you then"),
          msg("note", 7100, "Toured the studio Friday at 4. Liked the light, asked for the application link, sent it. No word since.", author="Sam")],
         stage="tour_scheduled", assignee="Sam", unread=False,
         fields={"listing": v("Rowan Lofts studio", 0.9, "studio at Rowan Lofts"),
                 "bedrooms": v(0, 0.8, "studio"),
                 "move_in_date": v("2026-09-15", 0.5, "mid September"),
                 "budget": UNKNOWN,
                 "pets": UNKNOWN,
                 "occupants": UNKNOWN,
                 "tour_requested": v(True, 0.95, "Could I see it Friday afternoon"),
                 "urgency": v("normal", 0.7, "")},
         drafts={"reply": "Hi Harper, it was good to meet you on Friday. Checking in to see whether you are still thinking about the studio at Rowan Lofts. If you have questions about the application or want to see it again, reply here any time."},
         tricky="went quiet after the tour: shows in Ghosted after tour"),
    conv("pl_06", "email", "Ingrid Lindqvist", "ingrid.lindqvist@example.org",
         "Relocating for work, 2BR by mid October",
         [msg("inbound", 4300, "Hello, I am relocating to Chicago for work and need a 2 bedroom by October 15. My company is covering the move and my budget is up to $2,600 a month. I saw Belden Court and Carver Place on your site. I will be in town next Tuesday and Wednesday and would like to see both."),
          msg("outbound", 4200, "Hi Ingrid, welcome to Chicago ahead of time. I can show you the 2 bedrooms at both Belden Court and Carver Place on Tuesday or Wednesday. Does Tuesday at 11am work, starting at Belden Court?", author="Priya"),
          msg("inbound", 4000, "Tuesday at 11 is perfect."),
          msg("outbound", 3900, "You are set for Tuesday at 11am at Belden Court, and we will walk over to Carver Place after. A confirmation is on its way.", author="Priya"),
          msg("note", 3880, "Two tours Tuesday. Company relocation, budget $2,600.", author="Priya")],
         stage="tour_scheduled", assignee="Priya", unread=False,
         fields={"listing": v("Belden Court and Carver Place", 0.8, "Belden Court and Carver Place"),
                 "bedrooms": v(2, 0.95, "2 bedroom"),
                 "move_in_date": v("2026-10-15", 0.9, "October 15"),
                 "budget": v(2600, 0.95, "up to $2,600"),
                 "pets": UNKNOWN,
                 "occupants": UNKNOWN,
                 "tour_requested": v(True, 0.95, "would like to see both"),
                 "urgency": v("normal", 0.7, "")}),
    conv("pl_07", "web_form", "Felix Moreau", "felix.moreau@example.com",
         "Applied for 2A at Belden Court, will I be approved?",
         [msg("inbound", 2900, "I submitted my application for 2A at Belden Court yesterday and paid the fee. How long does it take, and am I likely to get approved? My credit is decent and I make about three times the rent."),
          msg("outbound", 2800, "Hi Felix, thanks, I see your application for 2A. Every applicant is screened with the same written criteria, so I cannot say ahead of time how it will come out, but I will let you know as soon as yours has been processed.", author="Sam"),
          msg("note", 2790, "Application in for 2A, fee paid. Screening pending.", author="Sam"),
          msg("inbound", 200, "Thanks. Could I come by again to measure for furniture? Any evening this week.")],
         stage="applied", assignee="Sam",
         fields={"listing": v("Belden Court 2A", 0.95, "2A at Belden Court"),
                 "bedrooms": UNKNOWN,
                 "move_in_date": UNKNOWN,
                 "budget": UNKNOWN,
                 "pets": UNKNOWN,
                 "occupants": UNKNOWN,
                 "tour_requested": v(True, 0.8, "come by again to measure"),
                 "urgency": v("normal", 0.7, "")},
         drafts={"reply": "Of course, Felix. Tours run Monday to Saturday, so tell me which evening this week suits you and I will meet you at 2A with a tape measure. I will also let you know as soon as your application has been processed."},
         tricky="asks whether they will be approved: never_promise"),
    conv("pl_08", "voicemail", "Omar Brennan", "+1 (614) 555-0147",
         "Voicemail: moving from Ohio, needs a 1BR by September 1",
         [msg("inbound", 700, "Voicemail transcript, 7:48 pm: Hi, my name is Omar Brennan, I am moving from Columbus for a new job and I need a one bedroom by September 1st. I saw your listing at The Larkin. I can be there Saturday to look at it. My number is 614 555 0147. Thanks.")],
         priority="high",
         fields={"listing": v("The Larkin", 0.9, "The Larkin"),
                 "bedrooms": v(1, 0.9, "one bedroom"),
                 "move_in_date": v("2026-09-01", 0.9, "September 1st"),
                 "budget": UNKNOWN,
                 "pets": UNKNOWN,
                 "occupants": UNKNOWN,
                 "tour_requested": v(True, 0.9, "I can be there Saturday to look at it"),
                 "urgency": v("normal", 0.7, "")},
         drafts={"reply": "Hi Omar, thanks for the message, and congratulations on the new job. I can show you the 1 bedroom at The Larkin on Saturday; tell me what time works and I will confirm. A September 1 move-in is close, so I will check availability for that date and let you know today."}),
    conv("pl_09", "facebook_leads", "Sofia Rinaldi", "fb:sofia.rinaldi",
         "Facebook lead: 1BR under $1,600 with a cat",
         [msg("inbound", 950, "Facebook lead form\nName: Sofia Rinaldi\nEmail: sofia.rinaldi@example.com\nPhone: (312) 555-0173\nWhat are you looking for: 1 bedroom under $1,600, ideally with in-unit laundry\nWhen: November\nAnything else: I have a cat")],
         fields={"listing": UNKNOWN,
                 "bedrooms": v(1, 0.9, "1 bedroom"),
                 "move_in_date": v("2026-11-01", 0.5, "November"),
                 "budget": v(1600, 0.9, "under $1,600"),
                 "pets": v("cat", 0.95, "I have a cat"),
                 "occupants": UNKNOWN,
                 "tour_requested": UNKNOWN,
                 "urgency": v("normal", 0.7, "")},
         drafts={"reply": "Hi Sofia, thanks for reaching out. I will put together the 1 bedrooms we expect to have open for November and confirm which buildings allow cats, then send that over. Would you like to set up a tour once you have the list? Tours run Monday to Saturday."}),
    conv("pl_10", "zillow", "Theo Nakamura", "theo.nakamura@example.com",
         "Zillow: 5C at The Larkin still available?",
         [msg("inbound", 20000, "From: Zillow <leads@zillow.example.com>\nSubject: New rental lead for The Larkin #5C, 615 S Larkin St\n\nName: Theo Nakamura\nPhone: (847) 555-0136\nEmail: theo.nakamura@example.com\nMove-in: 09/01/2026\nMessage: Is 5C at The Larkin still available? I would like to see it this week if so. Just me, no pets, moving September 1."),
          msg("outbound", 19900, "Hi Theo, yes, 5C is still available. Tours run Monday to Saturday; does Thursday at 6pm work?", author="Sam"),
          msg("inbound", 19500, "Thursday at 6 works."),
          msg("outbound", 19400, "You are set for Thursday at 6pm at The Larkin. A confirmation is on its way.", author="Sam"),
          msg("note", 15000, "Toured, applied, approved. Lease signing Monday.", author="Sam"),
          msg("inbound", 13000, "Signed the lease today, thank you Sam!")],
         stage="leased", status="resolved", unread=False, assignee="Sam",
         fields={"listing": v("The Larkin 5C", 0.95, "5C at The Larkin"),
                 "bedrooms": UNKNOWN,
                 "move_in_date": v("2026-09-01", 0.9, "September 1"),
                 "budget": UNKNOWN,
                 "pets": v("none", 0.9, "no pets"),
                 "occupants": v(1, 0.9, "Just me"),
                 "tour_requested": v(True, 0.9, "would like to see it this week"),
                 "urgency": v("normal", 0.7, "")}),
    conv("pl_11", "sms", "Leo Abara", "+1 (708) 555-0192",
         "Six week furnished stay?",
         [msg("inbound", 6000, "Hi, do you have anything furnished for about six weeks starting in September? My condo is being renovated and I need somewhere close to the Loop."),
          msg("outbound", 5900, "Hi Leo, thanks for reaching out. Unfortunately all of our units are unfurnished on 12 month leases, so we are not a fit for a six week stay. A corporate housing or extended stay provider would be the better route, and I hope the renovation goes smoothly.", author="Priya"),
          msg("inbound", 5800, "Understood, thanks for the quick reply.")],
         stage="not_a_fit", status="resolved", unread=False, assignee="Priya",
         fields={"listing": UNKNOWN,
                 "bedrooms": UNKNOWN,
                 "move_in_date": v("2026-09-01", 0.4, "starting in September"),
                 "budget": UNKNOWN,
                 "pets": UNKNOWN,
                 "occupants": UNKNOWN,
                 "tour_requested": UNKNOWN,
                 "urgency": v("normal", 0.7, "")}),
    conv("pl_12", "email", "Wren Ivers", "wren.ivers@example.com",
         "Any 1 bedrooms open for mid September?",
         [msg("inbound", 800, "Hello, I am looking for a 1 bedroom for mid September, somewhere with parking if possible. Which of your buildings have something open? I would like to tour a couple this weekend. Thanks, Wren")],
         fields={"listing": UNKNOWN,
                 "bedrooms": v(1, 0.95, "1 bedroom"),
                 "move_in_date": v("2026-09-15", 0.5, "mid September"),
                 "budget": UNKNOWN,
                 "pets": UNKNOWN,
                 "occupants": UNKNOWN,
                 "tour_requested": v(True, 0.9, "would like to tour a couple this weekend"),
                 "urgency": v("normal", 0.7, "")},
         drafts={"reply": "Hi Wren, thanks for reaching out. I will check which buildings have a 1 bedroom open for mid September and which of those have parking, and send you the list today. Tours run Monday to Saturday, so Saturday works for seeing a couple of them; tell me what time suits you."}),
    conv("pl_13", "voicemail", "Grace Sato", "+1 (847) 555-0129",
         "Voicemail: cat, wants a Saturday tour at Carver Place",
         [msg("inbound", 260, "Voicemail transcript, 12:31 pm: Hi, this is Grace Sato calling about the two bedroom at Carver Place. I have a cat, is that okay there? I would love to come see it Saturday morning if that works. Call or text me back at 847 555 0129, thanks.")],
         fields={"listing": v("Carver Place, 2 bedroom", 0.9, "two bedroom at Carver Place"),
                 "bedrooms": v(2, 0.9, "two bedroom"),
                 "move_in_date": UNKNOWN,
                 "budget": UNKNOWN,
                 "pets": v("cat", 0.95, "I have a cat"),
                 "occupants": UNKNOWN,
                 "tour_requested": v(True, 0.95, "come see it Saturday morning"),
                 "urgency": v("normal", 0.7, "")},
         drafts={"reply": "Hi Grace, thanks for calling about the 2 bedroom at Carver Place. Pet policies differ by building, so I will confirm what applies to cats at Carver Place and let you know. Saturday morning works for a tour; does 10am suit you?"}),
    conv("pl_14", "web_form", "Yusuf Okonkwo", "yusuf.okonkwo@example.com",
         "Second applicant for 3B at Belden Court",
         [msg("inbound", 1500, "Hi, my roommate Ana Ferreira already applied for 3B at Belden Court and I need to submit my part of the application. Where do I do that? We are hoping to move in September 20. No pets for either of us."),
          msg("outbound", 1400, "Hi Yusuf, thanks. I have linked you to Ana's application for 3B and sent the applicant link to this email. Once your part is in, the two applications are screened together with the same written criteria, and I will let you both know as soon as they have been processed.", author="Priya"),
          msg("note", 1390, "Second applicant on 3B, linked to Ana Ferreira's file. Waiting on his submission.", author="Priya")],
         stage="applied", assignee="Priya", unread=False,
         fields={"listing": v("Belden Court 3B", 0.95, "3B at Belden Court"),
                 "bedrooms": UNKNOWN,
                 "move_in_date": v("2026-09-20", 0.9, "September 20"),
                 "budget": UNKNOWN,
                 "pets": v("none", 0.9, "No pets"),
                 "occupants": v(2, 0.85, "my roommate"),
                 "tour_requested": UNKNOWN,
                 "urgency": v("normal", 0.7, "")}),
    conv("pl_15", "sms", "Claire Doyle", "+1 (224) 555-0175",
         "Can I bring my rabbit?",
         [msg("inbound", 340, "hi! i'm interested in the studio at The Larkin. i have a rabbit, she's litter trained and lives in a hutch. is that allowed? also what's the earliest i could move in")],
         fields={"listing": v("The Larkin studio", 0.9, "studio at The Larkin"),
                 "bedrooms": v(0, 0.8, "studio"),
                 "move_in_date": UNKNOWN,
                 "budget": UNKNOWN,
                 "pets": v("other", 0.95, "rabbit"),
                 "occupants": UNKNOWN,
                 "tour_requested": UNKNOWN,
                 "urgency": v("normal", 0.7, "")},
         drafts={"reply": "Hi Claire, thanks for reaching out about the studio at The Larkin. Pet policies differ by building and I want to give you a straight answer on the rabbit, so I will check with the leasing manager and get back to you today. I will also confirm the earliest move-in date for that unit. Would you like to set up a tour in the meantime?"}),
    conv("pl_16", "zillow", "Rohan Patel", "rohan.patel@example.com",
         "Zillow: The Larkin 2BR, is the rent negotiable?",
         [msg("inbound", 1100, "From: Zillow <leads@zillow.example.com>\nSubject: New rental lead for The Larkin #8A, 615 S Larkin St\n\nName: Rohan Patel\nPhone: (331) 555-0116\nEmail: rohan.patel@example.com\nMove-in: 10/01/2026\nMessage: The 2 bedroom at The Larkin is listed at $2,150. Is that negotiable, and what is the deposit? My budget is closer to $2,000. Two of us would live there, no pets.")],
         fields={"listing": v("The Larkin #8A, 2 bedroom", 0.9, "2 bedroom at The Larkin"),
                 "bedrooms": v(2, 0.95, "2 bedroom"),
                 "move_in_date": v("2026-10-01", 0.85, "10/01/2026"),
                 "budget": v(2000, 0.85, "closer to $2,000"),
                 "pets": v("none", 0.9, "no pets"),
                 "occupants": v(2, 0.9, "Two of us"),
                 "tour_requested": UNKNOWN,
                 "urgency": v("normal", 0.7, "")},
         drafts={"reply": "Hi Rohan, thanks for asking about the 2 bedroom at The Larkin. Rent and deposit questions go to our leasing manager, so I will confirm the current numbers for that unit and get back to you today. In the meantime, would you like to tour it? Tours run Monday to Saturday."},
         tricky="pricing question: review before sending"),
    conv("pl_17", "sms", "Maya Reyes", "+1 (630) 555-0198",
         "Found another place, thanks anyway",
         [msg("inbound", 3000, "Hi Sam, thanks for showing me 2B at Carver Place last week. I ended up signing somewhere closer to work so I will pass. Appreciate your help!"),
          msg("outbound", 2950, "Hi Maya, thanks for letting me know, and congratulations on the new place. If anything changes down the road, reply here any time.", author="Sam")],
         stage="not_a_fit", status="resolved", unread=False, assignee="Sam",
         fields={"listing": v("Carver Place 2B", 0.9, "2B at Carver Place"),
                 "bedrooms": UNKNOWN,
                 "move_in_date": UNKNOWN,
                 "budget": UNKNOWN,
                 "pets": UNKNOWN,
                 "occupants": UNKNOWN,
                 "tour_requested": v(False, 0.7, "I will pass"),
                 "urgency": v("normal", 0.7, "")}),
]

TEMPLATE = {
    "key": "property_leasing",
    "name": "Property management",
    "tagline": "Leasing leads from Zillow, the site form, texts, voicemail and email",
    "example_prompt": "Property management company. Leasing leads come from Zillow, our web form, texts, voicemail, email and Facebook.",
    "signals": [("property management", 5), ("leasing", 4), ("zillow", 4), ("apartment", 3),
                ("tenant", 3), ("rental", 3), ("landlord", 3), ("units", 2), ("move-in", 2),
                ("lease", 2)],
    "must_review": [],
    "spec": SPEC,
    "questions": QUESTIONS,
    "personas": ["Sam", "Priya"],
    "ladders": LADDERS,
    "sample_inputs": SAMPLE_INPUTS,
    "prompt_examples": ["add a field for whether they need parking",
                        "add a view of tours this week",
                        "flag anyone asking about breaking a lease"],
    "conversations": C,
}
