"""Specialty referral intake: Lakeview Cardiology Associates (fictional), Chicago."""
from ._common import conv, msg, v, UNKNOWN

SPEC = {
    "business": {
        "name": "Lakeview Cardiology Associates",
        "type": "specialty_referrals",
        "summary": "Adult cardiology practice taking referrals from primary care, hospital and surgical offices for chest pain, arrhythmia, heart failure, hypertension and pre-op clearance.",
        "audience": "referrals",
    },
    "connectors": [
        {"key": "fax", "kind": "fax", "label": "Faxed referrals", "auto_connect": True},
        {"key": "email", "kind": "email", "label": "Referring office email", "auto_connect": True},
        {"key": "webhook", "kind": "webhook", "label": "EHR referral export", "auto_connect": True},
        {"key": "web_form", "kind": "web_form", "label": "Patient referral form", "auto_connect": True},
        {"key": "voicemail", "kind": "voicemail", "label": "Referral line voicemail", "auto_connect": False},
    ],
    "fields": [
        {"key": "referring_practice", "label": "Referring practice", "type": "text",
         "hint": "The office or group sending the referral, not the individual doctor", "show_in_list": True},
        {"key": "reason", "label": "Reason", "type": "enum",
         "options": ["chest_pain", "arrhythmia", "heart_failure", "hypertension", "preop_clearance", "other"],
         "hint": "Why they are being referred; palpitations, AFib and pauses are arrhythmia", "show_in_list": True},
        {"key": "urgency", "label": "Urgency", "type": "enum",
         "options": ["routine", "urgent", "stat"],
         "hint": "Stat if they say stat or within 48 hours; urgent if within one to two weeks", "show_in_list": True},
        {"key": "insurance", "label": "Insurance", "type": "text",
         "hint": "Plan name as written on the referral"},
        {"key": "prior_auth_needed", "label": "Prior auth needed", "type": "bool",
         "hint": "Yes if the referral says an authorization is required or pending; HMO plans usually need one"},
        {"key": "records_attached", "label": "Records attached", "type": "bool",
         "hint": "Yes if notes, ECG, labs or imaging came with the referral; no if they say records will follow"},
        {"key": "patient_initials", "label": "Patient initials", "type": "text",
         "hint": "Initials only, never the full name"},
    ],
    "stages": [
        {"key": "new", "label": "New", "tone": "brand"},
        {"key": "waiting_on_auth", "label": "Waiting on auth", "tone": "warn"},
        {"key": "waiting_on_records", "label": "Waiting on records", "tone": "warn"},
        {"key": "scheduled", "label": "Scheduled", "tone": "info"},
        {"key": "seen", "label": "Seen", "tone": "ok", "terminal": True},
        {"key": "declined", "label": "Declined", "tone": "neutral", "terminal": True},
    ],
    "views": [
        {"key": "inbox", "name": "All open",
         "filter": {"all": [{"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "desc"}, "pinned": True},
        {"key": "needs_reply", "name": "Needs reply",
         "filter": {"all": [{"field": "awaiting_reply", "op": "eq", "value": True}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "urgent_stat", "name": "Urgent and stat",
         "filter": {"all": [{"field": "f.urgency", "op": "in", "value": ["urgent", "stat"]},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "waiting_on_auth", "name": "Waiting on auth",
         "filter": {"all": [{"field": "stage", "op": "eq", "value": "waiting_on_auth"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}, "pinned": True},
        {"key": "waiting_on_records", "name": "Waiting on records",
         "filter": {"all": [{"field": "stage", "op": "eq", "value": "waiting_on_records"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}},
        {"key": "older_3d", "name": "Older than 3 days",
         "filter": {"all": [{"field": "last_message_at", "op": "older_than_days", "value": 3},
                            {"field": "status", "op": "eq", "value": "open"}]},
         "sort": {"by": "last_message_at", "dir": "asc"}},
    ],
    "rules": [
        {"key": "stat_priority", "name": "Stat referrals go to the top",
         "text": "Mark stat referrals as urgent",
         "when": {"all": [{"field": "f.urgency", "op": "eq", "value": "stat"}]},
         "then": {"type": "set_priority", "value": "urgent"}},
        {"key": "stat_flag", "name": "Stat within 48 hours",
         "text": "Flag stat referrals so they are seen within 48 hours",
         "when": {"all": [{"field": "f.urgency", "op": "eq", "value": "stat"}]},
         "then": {"type": "flag", "label": "Stat", "tone": "danger"}},
        {"key": "needs_auth", "name": "Prior auth holds scheduling",
         "text": "Move referrals that need an authorization to Waiting on auth",
         "when": {"all": [{"field": "f.prior_auth_needed", "op": "eq", "value": True}]},
         "then": {"type": "set_stage", "stage": "waiting_on_auth"}},
        {"key": "missing_records", "name": "Missing records",
         "text": "Flag referrals that arrived without notes, ECG or labs",
         "when": {"all": [{"field": "f.records_attached", "op": "eq", "value": False}]},
         "then": {"type": "flag", "label": "Missing records", "tone": "warn"}},
    ],
    "approval_policy": {"routine": "auto_send", "pricing": "review",
                        "medical_legal": "review", "distress": "review"},
    "tone": {"voice": "warm", "length": "short", "signoff": "Priya at Lakeview Cardiology Associates",
             "presets": [
                 {"label": "Acknowledge receipt", "instruction": "Confirm the referral arrived and say what happens next"},
                 {"label": "Ask for what is missing", "instruction": "Ask the referring office for the missing records or authorization number"},
                 {"label": "Offer times", "instruction": "Offer the next open appointment times and ask which works"},
                 {"label": "Check in", "instruction": "Check in on the status of the authorization or records"}]},
    "agent": {"name": "Priya", "persona": "Referral coordinator at a cardiology practice",
              "intro": "I read every referral, pull out what matters, and draft the acknowledgement for you to approve."},
    "playbook": "- Acknowledge every referral the same day it arrives.\n- Stat referrals are seen within 48 hours; urgent within one to two weeks.\n- Patients who write with symptoms are told to call their doctor or 911; we do not triage in writing.\n- Never interpret test results or state a diagnosis in writing; the cardiologist reviews everything at the visit.",
    "guardrails": [
        {"key": "no_interpretation", "text": "Never interpret a test result or state a diagnosis in writing. The cardiologist reviews it at the visit.",
         "enforce": "never_promise"},
        {"key": "symptoms_escalate", "text": "Chest pain right now or shortness of breath goes to 911 guidance and the nurse line.",
         "enforce": "escalate"},
        {"key": "no_ssn", "text": "Social security numbers are never collected through the inbox.",
         "enforce": "refuse_field", "patterns": ["social security", "ssn"],
         "reason": "social security number",
         "refusal": "I cannot add that. Social security numbers never go through the inbox. I can add fields like the referring doctor's name or the date the referral was sent."},
    ],
}

QUESTIONS = [
    {"id": "sources", "kind": "tiles", "multi": True,
     "prompt": "How do referrals reach you?",
     "why": "Each one becomes a connector and a way to filter.",
     "options": ["fax", "email", "webhook", "web_form", "voicemail"],
     "default": ["fax", "email", "webhook", "web_form"], "patch": "set_connectors"},
    {"id": "business_name", "kind": "text", "prompt": "What is the practice called?",
     "why": "It goes on every acknowledgement.", "default": "Lakeview Cardiology Associates", "patch": "set_business_name"},
    {"id": "extract_fields", "kind": "chips", "multi": True,
     "prompt": "What should I pull out of every referral?",
     "why": "Each one becomes a column you can sort and filter by.",
     "options": [["referring_practice", "Referring practice"], ["reason", "Reason"],
                 ["urgency", "Urgency"], ["insurance", "Insurance"],
                 ["prior_auth_needed", "Prior auth needed"], ["records_attached", "Records attached"],
                 ["patient_initials", "Patient initials"]],
     "default": ["referring_practice", "reason", "urgency", "insurance",
                 "prior_auth_needed", "records_attached"], "patch": "pick_fields"},
    {"id": "slices", "kind": "chips", "multi": True,
     "prompt": "Which views do you want on the front of the inbox?",
     "why": "Views are saved filters. You can add more later by typing.",
     "options": [["urgent_stat", "Urgent and stat"], ["waiting_on_auth", "Waiting on auth"],
                 ["waiting_on_records", "Waiting on records"], ["older_3d", "Older than 3 days"]],
     "default": ["urgent_stat", "waiting_on_auth"], "patch": "pick_views"},
    {"id": "approval", "kind": "chips", "multi": False,
     "prompt": "What may I send without you looking first?",
     "why": "Anything about results, symptoms or a diagnosis always waits for you.",
     "options": [["routine", "Acknowledging receipt to the referring office"], ["none", "Nothing, I review every reply"]],
     "default": "routine", "patch": "set_approval"},
    {"id": "tone", "kind": "chips", "multi": False, "prompt": "How should replies sound?",
     "why": "Sets the voice for every draft.",
     "options": [["warm", "Warm"], ["plain", "Plain"], ["formal", "Formal"]],
     "default": "warm", "patch": "set_tone"},
]

LADDERS = {
    "reply": [
        (("stat", "48 hours", "today", "tomorrow", "emergent", "asap"),
         "Thank you, we received the stat referral. Stat referrals are seen within 48 hours, so I am looking at the next two days now and will call you with a time within the hour. Please tell the patient that new or worse symptoms before the visit mean calling 911."),
        (("does this mean", "what does", "my results", "my report", "my echo", "diagnos"),
         "Thank you for writing, and I understand why the report is worrying. I am not able to interpret results in writing; the cardiologist will go through the report with you at your visit and answer exactly that question. If your symptoms get worse before then, please call your doctor, or 911 if it is severe."),
        (("auth", "authorization", "hmo", "prior auth", "pending"),
         "Thank you, we received the referral. To schedule we still need the insurance authorization number, so please send it over as soon as it comes through and I will book the patient the same day it arrives."),
        (("will follow", "to follow", "separate cover", "not attached", "no records", "missing"),
         "Thank you, we received the referral. Before we schedule, could you send the office note and any ECG, echo or labs from the visit? As soon as they arrive I will call the patient with a date."),
        (("pre-op", "preop", "clearance", "surgery", "procedure date"),
         "Thank you, we received the pre-op clearance request. To fit the visit ahead of the procedure, could you confirm the surgery date and send the H&P, medication list and most recent ECG if they are not already attached? I will send appointment options once I have them."),
        (("status", "have not heard", "haven't heard", "waiting", "any update", "follow up"),
         "Thank you for checking in, and sorry for the wait. I am looking up the referral now and will call you today with where it stands and what, if anything, we are still waiting on."),
    ],
    "fallback": "Thank you, {who}, we received the referral at Lakeview Cardiology Associates. I am reviewing it now and will confirm the appointment or let you know what we still need by the end of the day.",
    "check_in": "Hi {who}, checking in on the referral we discussed. Is the authorization or the remaining paperwork on its way? Reply here and I will schedule as soon as it arrives.",
    "booking": "Hi {who}, here are the next open times with the cardiologist. Reply with the one that works and I will confirm it the same day.",
    "thanks": "Thank you, {who}. The visit is set, and you can reply here with any questions before then.",
    "decline": "Thank you for the referral, {who}. This is outside what our practice offers, and I am happy to point you to a group that takes referrals like this one.",
    "ask_missing": "Thanks {who}. To schedule, could you send the patient's insurance, the reason for the referral, and the office note or ECG from the visit?",
}

SAMPLE_INPUTS = [
    {"label": "Sample referring office email", "source": "email",
     "text": "From: Renee Castillo <referrals@northlinefm.example.org>\nSubject: Cardiology referral, patient initials K.W.\n\nName: Renee Castillo, Northline Family Medicine\nMessage: Dr. Alvarez is referring patient initials K.W., 61, for exertional chest pain over the past three weeks, office ECG normal. Urgent, please see within two weeks. Insurance is Beacon Health HMO, we have requested the authorization. Office note and ECG attached."},
    {"label": "Sample fax cover", "source": "fax",
     "text": "FAX COVER. From: Ridgeline Internal Medicine, Dr. Brennan. To: Lakeview Cardiology referrals. Pages: 5. Patient initials G.H. Reason: new onset atrial fibrillation, rate controlled. Routine. Insurance: Medicare, no auth needed. Office note, ECG and labs attached. Questions to Walter at 773 555 0161."},
    {"label": "Sample voicemail transcript", "source": "voicemail",
     "text": "Voicemail transcript, 4:40 pm: Hi, this is Walter Osei calling from Ridgeline Internal Medicine for Dr. Brennan. We faxed a referral over on Monday for a patient with new AFib and have not heard back. Can someone call me at 773 555 0161 and confirm you got it? Thanks."},
]

C = [
    conv("sr_01", "fax", "Beatrice Lang", "fax:+1 (312) 555-0171",
         "Stat: new onset AFib, auth pending",
         [msg("inbound", 40, "FAX COVER. From: Northline Family Medicine, Dr. Alvarez. Attn: Referrals, Lakeview Cardiology. Pages: 4. Re: STAT cardiology referral, patient initials R.T. New onset atrial fibrillation on office ECG today, rate 118, patient stable and asymptomatic at rest, started on an anticoagulant. Insurance: Beacon Health HMO, referral authorization pending, our office will fax the auth number when it comes through. ECG and med list attached. Please call Beatrice at 312 555 0171 with the appointment.")],
         priority="urgent",
         fields={"referring_practice": v("Northline Family Medicine", 0.97, "Northline Family Medicine"),
                 "reason": v("arrhythmia", 0.95, "atrial fibrillation"),
                 "urgency": v("stat", 0.97, "STAT cardiology referral"),
                 "insurance": v("Beacon Health HMO", 0.95, "Beacon Health HMO"),
                 "prior_auth_needed": v(True, 0.95, "referral authorization pending"),
                 "records_attached": v(True, 0.95, "ECG and med list attached"),
                 "patient_initials": v("R.T.", 0.95, "patient initials R.T.")},
         drafts={"reply": "Hi Beatrice, thank you, we received the stat referral for R.T. from Dr. Alvarez with the ECG and med list. Stat referrals are seen within 48 hours, so I am holding a slot now and will call you with the time this afternoon. Since the Beacon HMO authorization is still pending, please fax the auth number as soon as it comes through so the visit is not held up, and let me know if it will take more than a day."},
         tricky="stat with auth pending: urgent priority and waiting on auth both fire"),
    conv("sr_02", "email", "Hannah Cole", "hannah.cole@example.org",
         "Pre-op clearance, surgery next week",
         [msg("inbound", 130, "Hi Priya, Dr. Sato at Westgate Orthopedics is asking for a cardiology pre-op clearance for patient initials M.K., a 67 year old scheduled for a total knee replacement on Wednesday September 2. History of hypertension and a stent in 2021. Insurance is Medicare with a Northwind supplement, no authorization needed. I attached the H&P, med list and last ECG. Can you fit them in this week? Thanks, Hannah")],
         priority="high",
         fields={"referring_practice": v("Westgate Orthopedics", 0.97, "Westgate Orthopedics"),
                 "reason": v("preop_clearance", 0.97, "pre-op clearance"),
                 "urgency": v("urgent", 0.85, "Can you fit them in this week?"),
                 "insurance": v("Medicare with a Northwind supplement", 0.95, "Medicare with a Northwind supplement"),
                 "prior_auth_needed": v(False, 0.95, "no authorization needed"),
                 "records_attached": v(True, 0.95, "attached the H&P, med list and last ECG"),
                 "patient_initials": v("M.K.", 0.95, "patient initials M.K.")},
         drafts={"reply": "Hi Hannah, thank you, we received the pre-op referral for M.K. from Dr. Sato with the H&P, med list and ECG. With the surgery on September 2 we will work them in this week, and I will send you two options by the end of the day. Please ask the patient to bring their current medication list to the visit."},
         tricky="pre-op with a surgery date next week: urgent"),
    conv("sr_03", "web_form", "Miguel Torres", "miguel.torres@example.com",
         "Patient: does my echo mean heart failure?",
         [msg("inbound", 85, "Name: Miguel Torres\nReferred by: Dr. Okafor, Lakeside Primary Care\nInsurance: Great Lakes PPO\nMessage: My doctor referred me to you after my echo. The report says ejection fraction 40 to 45 percent and mild left ventricular dysfunction. Does this mean I have heart failure? I have been a little short of breath climbing stairs but nothing at rest. My doctor's office said they sent the records over last week. I am very worried.")],
         fields={"referring_practice": v("Lakeside Primary Care", 0.95, "Lakeside Primary Care"),
                 "reason": v("heart_failure", 0.7, "ejection fraction 40 to 45 percent"),
                 "urgency": v("urgent", 0.6, "short of breath climbing stairs"),
                 "insurance": v("Great Lakes PPO", 0.95, "Great Lakes PPO"),
                 "prior_auth_needed": UNKNOWN,
                 "records_attached": UNKNOWN,
                 "patient_initials": v("M.T.", 0.9, "Name: Miguel Torres")},
         drafts={"reply": "Hi Miguel, thank you for writing, and I understand why the report is worrying. I am not able to interpret echo results in writing; the cardiologist will go through the report with you at your visit and answer exactly that question. We have the referral from Dr. Okafor, and I will check that the records arrived and send you appointment times today. If the shortness of breath gets worse or you have chest pain, please call your doctor, or 911 if it is severe."},
         tricky="patient asking what a result means: medical_legal, review before sending"),
    conv("sr_04", "webhook", "Felix Rinaldi", "ehr:ref-20260825-0417",
         "EHR export: hypertension, routine",
         [msg("inbound", 1300, "EHR referral export. Referral ID 20260825-0417. Referring practice: Prairie Health Group, Dr. Lindqvist. Contact: Felix Rinaldi, referral coordinator. Patient initials: J.O. Reason: hypertension, uncontrolled on two agents, home readings 160s over 100s. Priority: routine. Insurance: Northwind PPO, no prior auth required. Attachments: progress note, med list, BMP (3 documents).")],
         fields={"referring_practice": v("Prairie Health Group", 0.97, "Prairie Health Group"),
                 "reason": v("hypertension", 0.97, "hypertension, uncontrolled"),
                 "urgency": v("routine", 0.95, "Priority: routine"),
                 "insurance": v("Northwind PPO", 0.95, "Northwind PPO"),
                 "prior_auth_needed": v(False, 0.95, "no prior auth required"),
                 "records_attached": v(True, 0.95, "Attachments: progress note, med list, BMP"),
                 "patient_initials": v("J.O.", 0.95, "Patient initials: J.O.")},
         drafts={"reply": "Hi Felix, thank you, we received the hypertension referral for J.O. from Dr. Lindqvist with the progress note, med list and labs. It is logged as routine, and I will call the patient this week to schedule and send you the appointment date once it is set."}),
    conv("sr_05", "fax", "Nadia Haddad", "fax:+1 (773) 555-0166",
         "Fax: chest pain workup, records to follow",
         [msg("inbound", 400, "FAX COVER. From: Ridgeline Internal Medicine, Dr. Brennan. To: Lakeview Cardiology referrals. Pages: 1. Patient initials D.V. Reason: intermittent chest pain with exertion over the past month, ECG in office normal. Urgent, please see within two weeks. Insurance: Summit Medicare Advantage HMO, prior authorization required, auth number to follow. Records will follow under separate cover. Contact Nadia at 773 555 0166.")],
         priority="high",
         fields={"referring_practice": v("Ridgeline Internal Medicine", 0.97, "Ridgeline Internal Medicine"),
                 "reason": v("chest_pain", 0.97, "chest pain with exertion"),
                 "urgency": v("urgent", 0.95, "Urgent, please see within two weeks"),
                 "insurance": v("Summit Medicare Advantage HMO", 0.95, "Summit Medicare Advantage HMO"),
                 "prior_auth_needed": v(True, 0.95, "prior authorization required"),
                 "records_attached": v(False, 0.95, "Records will follow under separate cover"),
                 "patient_initials": v("D.V.", 0.95, "Patient initials D.V.")},
         drafts={"reply": "Hi Nadia, thank you, we received the urgent chest pain referral for D.V. from Dr. Brennan. To schedule we still need the office note and the ECG, plus the Summit authorization number. Could you fax those over when you have them? As soon as they arrive I will call the patient with a time inside the two week window."},
         tricky="no records and auth pending: missing records flag and waiting on auth"),
    conv("sr_06", "email", "Omar Abara", "omar.abara@example.org",
         "Heart failure follow up after discharge, Medicaid HMO",
         [msg("inbound", 2900, "Hello, referral from Dr. Moreau at Southside Community Health for patient initials L.P., 58, with known heart failure, recent admission at Lakeside Memorial for fluid overload, discharged Friday. Needs cardiology follow up within two weeks per the discharge plan. Insurance is Prairie State Medicaid HMO, so we are requesting the referral authorization now. Discharge summary, echo report and med list are attached. Thanks, Omar"),
          msg("outbound", 2800, "Hi Omar, thank you, we received the referral for L.P. from Dr. Moreau with the discharge summary, echo and med list. We are holding a slot in the first week of September and will finalize it as soon as the Prairie State authorization comes through. Please send the auth number when you have it.", author="Priya"),
          msg("note", 2790, "Post-discharge HF, needs to be seen within 14 days of 8/21. Slot held Tue 9/1 10:30 with Dr. Nakamura pending Prairie State auth.", author="Priya")],
         stage="waiting_on_auth", assignee="Priya", unread=False,
         fields={"referring_practice": v("Southside Community Health", 0.97, "Southside Community Health"),
                 "reason": v("heart_failure", 0.97, "known heart failure"),
                 "urgency": v("urgent", 0.9, "within two weeks"),
                 "insurance": v("Prairie State Medicaid HMO", 0.95, "Prairie State Medicaid HMO"),
                 "prior_auth_needed": v(True, 0.95, "requesting the referral authorization"),
                 "records_attached": v(True, 0.95, "Discharge summary, echo report and med list are attached"),
                 "patient_initials": v("L.P.", 0.95, "patient initials L.P.")}),
    conv("sr_07", "web_form", "Wren Doyle", "wren.doyle@example.com",
         "Patient form: palpitations, PCP faxed referral",
         [msg("inbound", 600, "Name: Wren Doyle\nReferred by: Dr. Kim, Northline Family Medicine\nInsurance: Great Lakes PPO\nMessage: My PCP referred me for palpitations that come and go, mostly in the evening, a few times a week for the last two months. No chest pain, no fainting. She said she faxed the referral on Monday. I can do any morning.")],
         fields={"referring_practice": v("Northline Family Medicine", 0.95, "Northline Family Medicine"),
                 "reason": v("arrhythmia", 0.9, "palpitations"),
                 "urgency": v("routine", 0.6, "come and go"),
                 "insurance": v("Great Lakes PPO", 0.95, "Great Lakes PPO"),
                 "prior_auth_needed": UNKNOWN,
                 "records_attached": UNKNOWN,
                 "patient_initials": v("W.D.", 0.9, "Name: Wren Doyle")},
         drafts={"reply": "Hi Wren, thank you for reaching out, and I am glad Dr. Kim sent you our way. I will match your form with the referral from Northline Family Medicine and send you morning appointment options within a day. If the palpitations ever come with chest pain, fainting or trouble breathing, please call your doctor, or 911 if it is severe."}),
    conv("sr_08", "fax", "Ana Ferreira", "fax:+1 (630) 555-0152",
         "Fax: hypertension with LVH, routine",
         [msg("inbound", 30000, "FAX COVER. From: Prairie Health Group, Dr. Lindqvist. Patient initials S.B. Reason: hypertension with new left ventricular hypertrophy on ECG. Routine. Insurance: Summit Health PPO, no auth needed. Office note, ECG and labs attached (6 pages). Questions to Ana at 630 555 0152."),
          msg("outbound", 29900, "Hi Ana, thank you, we received the routine referral for S.B. from Dr. Lindqvist with the note, ECG and labs. I will call the patient to schedule and send you the visit date.", author="Marcus"),
          msg("outbound", 29000, "S.B. is scheduled for Tuesday August 18 at 2:15 pm with Dr. Nakamura.", author="Marcus"),
          msg("note", 12000, "Seen 8/18. Consult note faxed to Prairie Health 8/19.", author="Marcus")],
         stage="seen", status="resolved", unread=False, assignee="Marcus",
         fields={"referring_practice": v("Prairie Health Group", 0.97, "Prairie Health Group"),
                 "reason": v("hypertension", 0.97, "hypertension with new left ventricular hypertrophy"),
                 "urgency": v("routine", 0.95, "Routine"),
                 "insurance": v("Summit Health PPO", 0.95, "Summit Health PPO"),
                 "prior_auth_needed": v(False, 0.95, "no auth needed"),
                 "records_attached": v(True, 0.95, "Office note, ECG and labs attached"),
                 "patient_initials": v("S.B.", 0.95, "Patient initials S.B.")}),
    conv("sr_09", "webhook", "Ingrid Varga", "ehr:ref-20260812-0288",
         "EHR export: pediatric murmur, adults only",
         [msg("inbound", 20000, "EHR referral export. Referral ID 20260812-0288. Referring practice: Lakeside Primary Care, Dr. Okafor. Contact: Ingrid Varga. Patient initials A.R., age 9. Reason: heart murmur noted at well child visit, pediatric cardiology evaluation requested. Priority: routine. Insurance: Great Lakes PPO. Attachments: visit note (1 document)."),
          msg("outbound", 19800, "Hi Ingrid, thank you for the referral for A.R. We see adults only, so a pediatric murmur evaluation is outside what we can offer. The Children's Heart Center at Lakeside Memorial takes pediatric cardiology referrals, and I am happy to forward this one if that helps.", author="Priya"),
          msg("inbound", 19500, "Understood, we will redirect it. Thanks.")],
         stage="declined", status="resolved", unread=False, assignee="Priya",
         fields={"referring_practice": v("Lakeside Primary Care", 0.97, "Lakeside Primary Care"),
                 "reason": v("other", 0.9, "heart murmur"),
                 "urgency": v("routine", 0.95, "Priority: routine"),
                 "insurance": v("Great Lakes PPO", 0.95, "Great Lakes PPO"),
                 "prior_auth_needed": UNKNOWN,
                 "records_attached": v(True, 0.9, "Attachments: visit note"),
                 "patient_initials": v("A.R.", 0.95, "Patient initials A.R.")}),
    conv("sr_10", "email", "Tom Quinn", "tom.quinn@example.org",
         "Stat: syncope, ER sent home with monitor",
         [msg("inbound", 25, "Priya, this is Tom at Ridgeline Internal Medicine for Dr. Brennan. Patient initials E.N., 72, passed out at home Sunday, seen in the ER at Lakeside Memorial, ECG showed a brief pause, sent home with a monitor and told to see cardiology stat. Insurance is Medicare, no auth. The ER records and ECG are attached. Can you get them in tomorrow or Friday? Tom, 773 555 0158")],
         priority="urgent",
         fields={"referring_practice": v("Ridgeline Internal Medicine", 0.97, "Ridgeline Internal Medicine"),
                 "reason": v("arrhythmia", 0.85, "ECG showed a brief pause"),
                 "urgency": v("stat", 0.95, "see cardiology stat"),
                 "insurance": v("Medicare", 0.95, "Insurance is Medicare"),
                 "prior_auth_needed": v(False, 0.95, "no auth"),
                 "records_attached": v(True, 0.95, "ER records and ECG are attached"),
                 "patient_initials": v("E.N.", 0.95, "Patient initials E.N.")},
         drafts={"reply": "Hi Tom, thank you, we received the stat referral for E.N. from Dr. Brennan with the ER records and ECG. Stat referrals are seen within 48 hours, so I am looking at tomorrow and Friday now and will call you back within the hour with a time. Please tell the patient that if they pass out again or have chest pain before the visit, they should call 911."}),
    conv("sr_11", "voicemail", "Ruth Adler", "+1 (312) 555-0147",
         "Voicemail: patient asking about referral status",
         [msg("inbound", 960, "Voicemail transcript, 4:52 pm: Hi, my name is Ruth Adler, my doctor Dr. Moreau at Southside Community Health sent a referral to you about two weeks ago for my blood pressure and I have not heard anything. My insurance is Prairie State, I think it needs an authorization. Can somebody call me back at 312 555 0147? Thank you.")],
         fields={"referring_practice": v("Southside Community Health", 0.95, "Southside Community Health"),
                 "reason": v("hypertension", 0.85, "blood pressure"),
                 "urgency": v("routine", 0.5, ""),
                 "insurance": v("Prairie State", 0.9, "My insurance is Prairie State"),
                 "prior_auth_needed": v(True, 0.7, "needs an authorization"),
                 "records_attached": UNKNOWN,
                 "patient_initials": v("R.A.", 0.9, "my name is Ruth Adler")},
         drafts={"reply": "Hi Ruth, thanks for the voicemail, and I am sorry you have been waiting. I am looking up the referral from Dr. Moreau now and will call you back today at the number you left. If the Prairie State authorization is what is holding it up, I will contact their office about it so you do not have to."},
         tricky="patient chasing a referral: check the auth status before replying"),
    conv("sr_12", "web_form", "Noah Sousa", "noah.sousa@example.com",
         "Patient form: pre-op clearance, cataract surgery",
         [msg("inbound", 5000, "Name: Noah Sousa\nReferred by: Dr. Ivers, Clearview Eye Surgeons\nInsurance: Medicare with a Great Lakes supplement\nMessage: I need cardiology clearance before cataract surgery on September 15. I have a pacemaker placed in 2019. The surgeon's office said they emailed the request and my records to you. Afternoons are better for me."),
          msg("outbound", 4900, "Hi Noah, thanks for reaching out. We have the request from Dr. Ivers along with your records, and you are scheduled for Thursday September 3 at 1:45 pm with Dr. Nakamura. Please bring your pacemaker card and a list of your medications.", author="Marcus"),
          msg("note", 4880, "Matched with the Clearview email of 8/21. Pacemaker, device check due; booked the device clinic the same afternoon.", author="Marcus")],
         stage="scheduled", assignee="Marcus", unread=False,
         fields={"referring_practice": v("Clearview Eye Surgeons", 0.95, "Clearview Eye Surgeons"),
                 "reason": v("preop_clearance", 0.95, "cardiology clearance before cataract surgery"),
                 "urgency": v("routine", 0.7, "September 15"),
                 "insurance": v("Medicare with a Great Lakes supplement", 0.95, "Medicare with a Great Lakes supplement"),
                 "prior_auth_needed": v(False, 0.6, ""),
                 "records_attached": v(True, 0.7, "emailed the request and my records"),
                 "patient_initials": v("N.S.", 0.9, "Name: Noah Sousa")}),
    conv("sr_13", "fax", "Sam Patel", "fax:+1 (312) 555-0173",
         "Fax: new heart failure diagnosis, Medicaid",
         [msg("inbound", 1700, "FAX COVER. From: Southside Community Health, Dr. Moreau. Pages: 9. Patient initials T.G. Reason: heart failure, new diagnosis, BNP elevated, echo pending at Lakeside Memorial. Please see within 2 weeks. Insurance: Illinois Medicaid fee for service, no prior auth required. Office note, labs and med list attached. Call Sam at 312 555 0173.")],
         priority="high",
         fields={"referring_practice": v("Southside Community Health", 0.97, "Southside Community Health"),
                 "reason": v("heart_failure", 0.97, "heart failure, new diagnosis"),
                 "urgency": v("urgent", 0.9, "see within 2 weeks"),
                 "insurance": v("Illinois Medicaid fee for service", 0.95, "Illinois Medicaid fee for service"),
                 "prior_auth_needed": v(False, 0.95, "no prior auth required"),
                 "records_attached": v(True, 0.95, "Office note, labs and med list attached"),
                 "patient_initials": v("T.G.", 0.95, "Patient initials T.G.")},
         drafts={"reply": "Hi Sam, thank you, we received the heart failure referral for T.G. from Dr. Moreau with the office note, labs and med list. I will call the patient this week with a visit inside the two week window and send you the date. If the echo report from Lakeside Memorial comes through before then, please fax it so the cardiologist has it at the visit."}),
    conv("sr_14", "email", "Devon Marsh", "devon.marsh@example.org",
         "Referral: PVCs on Holter, records to follow",
         [msg("inbound", 2100, "Hi, Dr. Kim at Northline Family Medicine is referring patient initials C.H. for frequent PVCs on a Holter, symptomatic, routine priority. Insurance Beacon Health HMO, we have requested the authorization. I will send the Holter report and note in a second email once our scanner is back up. Devon")],
         fields={"referring_practice": v("Northline Family Medicine", 0.97, "Northline Family Medicine"),
                 "reason": v("arrhythmia", 0.95, "frequent PVCs"),
                 "urgency": v("routine", 0.95, "routine priority"),
                 "insurance": v("Beacon Health HMO", 0.95, "Beacon Health HMO"),
                 "prior_auth_needed": v(True, 0.9, "requested the authorization"),
                 "records_attached": v(False, 0.9, "I will send the Holter report and note in a second email"),
                 "patient_initials": v("C.H.", 0.95, "patient initials C.H.")},
         drafts={"reply": "Hi Devon, thank you, we received the referral for C.H. from Dr. Kim and have it logged as routine. When the scanner is back, please send the Holter report and office note, plus the Beacon authorization number once it comes through, and I will schedule the patient as soon as both are in."}),
    conv("sr_15", "webhook", "Lena Bell", "ehr:ref-20260826-0512",
         "EHR export: chest pain at rest, urgent",
         [msg("inbound", 200, "EHR referral export. Referral ID 20260826-0512. Referring practice: Westgate Internal Medicine, Dr. Delgado. Contact: Lena Bell. Patient initials P.Q. Reason: chest pain, atypical, two episodes at rest this week, troponin negative in office, ECG nonspecific ST changes. Priority: urgent. Insurance: Northwind PPO, no prior auth required. Attachments: office note, ECG, labs (4 documents).")],
         priority="high",
         fields={"referring_practice": v("Westgate Internal Medicine", 0.97, "Westgate Internal Medicine"),
                 "reason": v("chest_pain", 0.97, "chest pain, atypical"),
                 "urgency": v("urgent", 0.95, "Priority: urgent"),
                 "insurance": v("Northwind PPO", 0.95, "Northwind PPO"),
                 "prior_auth_needed": v(False, 0.95, "no prior auth required"),
                 "records_attached": v(True, 0.95, "Attachments: office note, ECG, labs"),
                 "patient_initials": v("P.Q.", 0.95, "Patient initials P.Q.")},
         drafts={"reply": "Hi Lena, thank you, we received the urgent chest pain referral for P.Q. from Dr. Delgado with the office note, ECG and labs. I will call the patient today to schedule within the week and send you the date. If the patient has chest pain again before the visit, please advise them to call 911."}),
    conv("sr_16", "email", "Jordan Osei", "jordan.osei@example.org",
         "Referral: atrial flutter, urgent",
         [msg("inbound", 40000, "Hi Priya, referral from Dr. Delgado at Westgate Internal Medicine for patient initials F.M., new onset atrial flutter, rate controlled, urgent. Insurance Medicare, no auth. Note and ECG attached. Jordan"),
          msg("outbound", 39900, "Hi Jordan, thank you, we received the urgent referral for F.M. from Dr. Delgado with the note and ECG. I will call the patient today and send you the date.", author="Priya"),
          msg("outbound", 39000, "F.M. is scheduled for Monday August 3 at 9:00 am with Dr. Nakamura.", author="Priya"),
          msg("inbound", 31000, "Thanks Priya, we got the consult note, much appreciated.")],
         stage="seen", status="resolved", unread=False, assignee="Priya",
         fields={"referring_practice": v("Westgate Internal Medicine", 0.97, "Westgate Internal Medicine"),
                 "reason": v("arrhythmia", 0.95, "atrial flutter"),
                 "urgency": v("urgent", 0.9, "rate controlled, urgent"),
                 "insurance": v("Medicare", 0.95, "Insurance Medicare"),
                 "prior_auth_needed": v(False, 0.95, "no auth"),
                 "records_attached": v(True, 0.95, "Note and ECG attached"),
                 "patient_initials": v("F.M.", 0.95, "patient initials F.M.")}),
    conv("sr_17", "fax", "Sofia Castillo", "fax:+1 (630) 555-0129",
         "Fax: irregular pulse, ECG to follow",
         [msg("inbound", 4400, "FAX COVER. From: Clearview Family Practice, Dr. Reyes. Pages: 1. Patient initials H.L. Reason: arrhythmia, irregular pulse noted at visit, patient reports skipped beats. Routine. Insurance: Northwind PPO, no auth needed. ECG to follow. Contact Sofia at 630 555 0129."),
          msg("outbound", 4300, "Hi Sofia, thank you, we received the referral for H.L. from Dr. Reyes. Before we schedule, could you fax the ECG and the office note from that visit? As soon as they arrive I will call the patient with a date.", author="Marcus"),
          msg("note", 4280, "Called Clearview, the ECG was never scanned. They will refax by Friday.", author="Marcus")],
         stage="waiting_on_records", assignee="Marcus", unread=False,
         fields={"referring_practice": v("Clearview Family Practice", 0.97, "Clearview Family Practice"),
                 "reason": v("arrhythmia", 0.9, "irregular pulse"),
                 "urgency": v("routine", 0.95, "Routine"),
                 "insurance": v("Northwind PPO", 0.95, "Northwind PPO"),
                 "prior_auth_needed": v(False, 0.95, "no auth needed"),
                 "records_attached": v(False, 0.95, "ECG to follow"),
                 "patient_initials": v("H.L.", 0.95, "Patient initials H.L.")}),
]

TEMPLATE = {
    "key": "specialty_referrals",
    "name": "Specialty referrals",
    "tagline": "Referrals from fax, referring office email, an EHR export, the patient form and voicemail",
    "example_prompt": "Cardiology clinic. Referrals arrive by fax, email from referring offices, an EHR export, our web form and voicemail.",
    "signals": [("cardiology clinic", 6), ("specialty clinic", 6), ("referring offices", 4), ("cardiology", 5), ("referral", 2), ("referrals", 2), ("referring", 2),
                ("fax", 1), ("prior auth", 4), ("specialist", 3), ("ehr", 3),
                ("pre-op", 2), ("clinic", 1)],
    "must_review": ["medical_legal"],
    "spec": SPEC,
    "questions": QUESTIONS,
    "personas": ["Priya", "Marcus"],
    "ladders": LADDERS,
    "sample_inputs": SAMPLE_INPUTS,
    "prompt_examples": ["add a field for the referring doctor's name",
                        "add a view of pre-op clearances with surgery in the next two weeks",
                        "flag anything from Northline Family Medicine"],
    "conversations": C,
}
