"""WP-B generative chemistry competitor data (research as of 30 Sep 2026).

x = synthesis grounding (0 = none, 10 = every design comes with a make-able route / is made in-house)
y = commercial model (0 = sells tools/software, 10 = owns or partners drug programs)
Scores are team judgement calls, not published figures.
"""

# Tier: Direct / Well-funded AI designer / Incumbent software / Indirect-complementor / Emerging-open / Niche (antibiotics)
COMPETITORS = [
    dict(name="Stoked Bio — SyntheMol / SyntheMol-RL", short="SyntheMol", tier="Client", hq="Hamilton, ON (McMaster spin-out)",
         product="SyntheMol (MCTS, Nat Mach Intell 2024); SyntheMol-RL (RL, Mol Syst Biol 2026)",
         approach="Assembles molecules from commercial building blocks + known reactions (Enamine REAL, ~30B then ~46B space); every output ships with its synthesis recipe. RL version does multi-objective optimisation (activity + solubility).",
         model="Internal pipeline (anti-infectives, microbiome, GBM, Parkinson's); commercial model under evaluation",
         funding="$2.5M seed (announced 1 May 2026; angel-led with insiders, oversubscribed, 99% from Ontario; currency not stated, likely CAD)", funding_usd_m=2.5,
         deals="Exclusive McMaster licence for Enterololin (Crohn's), Feb 2026",
         evidence="v1: 58 made, 6 potent novel A. baumannii actives. RL: 79 made, 13 potent, 7 structurally novel; synthecin effective in MRSA mouse wound model",
         threat="—", x=9.5, y=8,
         why="Baseline for comparison.",
         src="https://www.biospace.com/press-releases/stoked-bio-announces-the-closing-of-seed-financing-round ; https://link.springer.com/article/10.1038/s44320-026-00206-9"),

    # ---------- Direct: synthesis-aware generative design ----------
    dict(name="Iktos", short="Iktos", tier="Direct", hq="Paris, France",
         product="Makya (generative design), Spaya (retrosynthesis), Iktos Robotics",
         approach="Generative design constrained to synthetically accessible chemistry, retrosynthesis to purchasable materials, and AI-orchestrated robotic synthesis (Chemspeed partnership, Mar 2026).",
         model="SaaS licences + partnered discovery + robotics",
         funding="€15.5M Series A (M Ventures, Debiopharm, Omnes); €2.5M EIC Accelerator grant 2025 (+€5M follow-on eligible)", funding_usd_m=20,
         deals="Servier €1B+ multi-target (Jan 2026); Pierre Fabre oncology; Ono; Elsevier (Reaxys retrosynthesis)",
         evidence="Pharma partnerships; no own clinical asset disclosed",
         threat="High", x=8, y=5,
         why="Closest commercial analogue: sells both the generative tool and the synthesis route, and now closes the make loop with robots.",
         src="https://pharmaphorum.com/news/servier-signs-eu1bn-plus-ai-pact-iktos"),
    dict(name="PostEra", short="PostEra", tier="Direct", hq="United States",
         product="Proton platform; Manifold (synthesis-aware search/design)",
         approach="Synthesis-aware generative chemistry; ML retrosynthesis; origin in COVID Moonshot open-science programme.",
         model="Partnered 'AI Lab' deals + internal programs (small molecules, ADC payloads)",
         funding="$24M Series A (Jan 2022, Clermont Group). Also co-leads the NIH-funded ASAP antiviral consortium ($68M initial funding, shared with MSKCC and DNDi)", funding_usd_m=24,
         deals="Pfizer AI Lab: $13M upfront, up to $260M (Jan 2022); expanded Jan 2025 with a further $12M upfront",
         evidence="Partnered programs; antiviral work via NIH AViDD",
         threat="High", x=8, y=7,
         why="Same pitch (AI molecules chemists can actually make) and a proven pharma buyer in Pfizer.",
         src="https://www.pharmtech.com/view/postera-expands-pfizer-partnership-ai-lab-adc-collaborations"),
    dict(name="Onepot AI", short="Onepot", tier="Direct", hq="United States",
         product="onepot CORE (3.4B enumerated space), POT-1 automated lab, 'Phil' AI chemist",
         approach="Enumerated make-on-demand space tied to its own automated synthesis lab; claims molecules delivered 6–10x faster.",
         model="Sells molecules / synthesis-as-a-service to discovery teams",
         funding="$13M pre-seed + seed (Nov 2025; Fifty Years lead, Khosla, Speedinvest, Norrsken)", funding_usd_m=13,
         deals="Early commercial partners (undisclosed)",
         evidence="Commercial deliveries claimed; no public biology validation",
         threat="High", x=9.5, y=3,
         why="Owns the 'make' step that SyntheMol outsources to Enamine; a generative front-end on CORE would replicate SyntheMol's value proposition.",
         src="https://techcrunch.com/2025/11/19/onepot-ai-raises-13m-to-help-make-chemical-drug-creation-easier"),
    dict(name="Chemify", short="Chemify", tier="Direct", hq="Glasgow, UK",
         product="Chemputation platform, Chemifarm automated facilities, Chemify Genesis",
         approach="Digitised, programmable chemistry: design is coupled to robotic synthesis in its own facilities.",
         model="Partnered discovery for pharma, specialty chemicals, materials",
         funding=">$50M Series B (Oct 2025; Wing VC, Insight); £22M grants 2026; ~£110M total", funding_usd_m=145,
         deals="Pharma and materials partners (undisclosed)",
         evidence="First Chemifarm live 2025; larger site due late 2026",
         threat="Medium", x=9, y=4,
         why="Well-funded 'design + make' player; horizontal (not drug-specific) so less direct.",
         src="https://www.insightpartners.com/ideas/chemify-raises-more-than-50-million-in-oversubscribed-series-b-to-drive-global-expansion-of-digital-chemistry-and-discovery"),
    dict(name="Insilico Medicine (Chemistry42)", short="Insilico", tier="Direct", hq="Boston / Hong Kong (HKEX: 3696)",
         product="Pharma.AI: Chemistry42 (generative chemistry), Biology42, Medicine42",
         approach="Ensemble of generative models with synthetic-accessibility scoring and filters; strongest clinical proof of any generative-chemistry company.",
         model="Pipeline + out-licensing dominate; software is a small line",
         funding="HK IPO 30 Dec 2025, ~HK$2.28B raised (largest HK biotech IPO of 2025)", funding_usd_m=290,
         deals="Lilly: $115M upfront, up to $2.75B (Mar 2026); SK Biopharm up to $2.5B; ~$10B aggregate headline value",
         evidence="Rentosertib (TNIK, IPF): Phase 3 launched Jul 2026, first patient dosed 9 Sep 2026. FY2025 revenue $56.2M, of which software only $4.9M; net loss $352M",
         threat="Medium", x=5, y=8.1,
         why="Sets buyer expectations for generative chemistry and publishes list pricing (~$3K/month entry, third-party estimate). Its software revenue shows how small a pure tool business is.",
         src="https://www.itiger.com/news/1172056437"),
    dict(name="XtalPi", short="XtalPi", tier="Direct", hq="Shenzhen / Boston (HKEX: 2228)",
         product="AI + robotics discovery platform, 200+ domain models",
         approach="Physics + AI design with large robotic synthesis/testing labs.",
         model="Drug discovery services + partnerships",
         funding="Public (HKEX); first profitable year 2025", funding_usd_m=None,
         deals="DoveTree up to ~$5.9B ($51M upfront + $49M near-term); 17 of top-20 pharma engaged",
         evidence="2025 revenue RMB 803M (+201%); net profit RMB 124M",
         threat="Medium", x=7.5, y=5.6,
         why="Proof that AI + automated synthesis can be profitable at scale; big-pharma incumbent vendor.",
         src="https://www.itiger.com/news/1142970847"),
    dict(name="Variational AI (Enki)", short="Variational AI", tier="Direct", hq="Vancouver, BC",
         product="Enki foundation model for small-molecule design",
         approach="Generative foundation model for hit/lead design; synthesizability handled as a design objective.",
         model="Platform access for biopharma chemistry teams",
         funding="$3.5M seed (2021) + $5.5M seed extension (Feb 2025; Nimbus Synergies lead, Merck GHIF)", funding_usd_m=9,
         deals="Undisclosed pharma users",
         evidence="Early commercial",
         threat="Medium", x=5, y=3,
         why="Only Canadian pure-play generative-chemistry startup; competes for the same Canadian investors and grants.",
         src="https://www.biospace.com/press-releases/variational-ai-announces-oversubscribed-5-5-million-financing-to-launch-foundation-model-for-small-molecule-drug-discovery"),
    dict(name="Model Medicines (GALILEO)", short="Model Medicines", tier="Direct", hq="La Jolla, CA",
         product="GALILEO generative platform",
         approach="Generative expansion of chemical space (claims 50 trillion-compound solution space); anti-infective focus (antivirals).",
         model="Internal pipeline",
         funding="Not disclosed in sources found", funding_usd_m=None,
         deals="—",
         evidence="Claims 12/12 one-shot antiviral hits (preprint, Jan 2025); MDL-001 broad-spectrum antiviral",
         threat="Medium", x=4, y=8,
         why="Same therapeutic neighbourhood (infectious disease) with a generative 'one-shot' story.",
         src="https://modelmedicines.com/newsroom/demonstrating-end-to-end-drug-discovery-galileo-unlocks-generative-ai-for-chemistry"),

    # ---------- Well-funded AI drug designers ----------
    dict(name="Isomorphic Labs", short="Isomorphic", tier="Well-funded AI designer", hq="London, UK (Alphabet)",
         product="IsoDDE drug design engine (AlphaFold lineage)",
         approach="Structure-first AI design across modalities.",
         model="Internal pipeline + pharma partnerships",
         funding="$600M (2025) + $2.1B Series B (May 2026, Thrive lead) ≈ $2.7B", funding_usd_m=2700,
         deals="Lilly ~$45M upfront / $1.7B; Novartis ~$37.5M / $1.2B (expanded 2025); J&J",
         evidence="First candidates targeted for clinic by end-2026",
         threat="Low", x=3.6, y=9.2,
         why="Doesn't sell tools; competes for pharma partnership budgets and talent, and resets investor expectations.",
         src="https://www.isomorphiclabs.com/press/isomorphic-labs-funding"),
    dict(name="Iambic Therapeutics", short="Iambic", tier="Well-funded AI designer", hq="San Diego, CA",
         product="NeuralPLexer (structure), Enchant (property prediction), generative design",
         approach="AI + automated chemistry; NVIDIA-backed.",
         model="Clinical-stage oncology pipeline + partnerships",
         funding=">$100M (Nov 2025) + $20M (Jan 2026); filed for $100M Nasdaq IPO (IAM), Sep 2026", funding_usd_m=300,
         deals="Takeda: up to $1.7B in milestones, 3 targets (Feb 2026); Lundbeck (migraine, 2024)",
         evidence="Phase 1 oncology assets",
         threat="Low", x=5.9, y=9.4,
         why="Comparable for 'AI platform to clinic' valuation; not a tool competitor.",
         src="https://www.renaissancecapital.com/IPO-Center/News/121805/small-molecule-biotech-iambic-therapeutics-files-for-a-100-million-ipo"),
    dict(name="Genesis Molecular AI", short="Genesis", tier="Well-funded AI designer", hq="Burlingame, CA",
         product="GEMS platform; Pearl structure model",
         approach="Generative + predictive AI with physics; moving toward platform licensing.",
         model="Platform deals + pipeline",
         funding="$200M Series B (2023); >$400M total", funding_usd_m=400,
         deals="Incyte expansion (May 2026): $80M cash + $40M equity, up to $232M milestones per program, 5+ targets; Gilead (2024)",
         evidence="Preclinical",
         threat="Low", x=4.4, y=7.2,
         why="Shows pharma will pay nine-figure upfronts for platform access plus data rights.",
         src="https://fiercebiotech.com/biotech/incyte-pays-genesis-80m-expand-ai-fueled-drug-discovery-pact"),
    dict(name="Terray Therapeutics", short="Terray", tier="Well-funded AI designer", hq="Monrovia, CA",
         product="tNova platform",
         approach="Generative design trained on its own ultra-high-throughput binding data (5B+ measurements).",
         model="Internal immunology pipeline + partnerships",
         funding="$120M Series B (Oct 2024; Bedford Ridge, NVentures); >$200M total", funding_usd_m=200,
         deals="BMS, Calico, Gilead",
         evidence="Preclinical → clinic",
         threat="Low", x=6, y=8,
         why="Model for a 'proprietary data moat' story, which is also Stoked's likely moat argument.",
         src="https://www.fiercebiotech.com/biotech/terray-therapeutics-doubles-series-money-raking-120m-push-programs-clinic"),
    dict(name="Recursion (incl. Exscientia, Cyclica, Valence)", short="Recursion", tier="Well-funded AI designer", hq="Salt Lake City, UT (Nasdaq: RXRX)",
         product="Recursion OS; Exscientia design; Boltz-2 co-developer",
         approach="Phenomics + generative chemistry acquired via Exscientia (2024) and Valence Labs.",
         model="Pipeline + partnerships",
         funding="Public; cut 20% of staff 2025; burn <$390M guided for 2026", funding_usd_m=None,
         deals="Bought Cyclica (Toronto, $40M) and Valence (Montréal, $47.5M) in 2023",
         evidence="Pipeline pruned 2025",
         threat="Low", x=5, y=8.9,
         why="Cyclica/Valence are the relevant Canadian exit comps for a generative-chemistry spin-out.",
         src="https://ir.recursion.com/news-releases/news-release-details/recursion-enters-agreements-acquire-cyclica-and-valence-bolster"),
    dict(name="Aqemia", short="Aqemia", tier="Well-funded AI designer", hq="Paris, France",
         product="Generative AI + quantum/statistical physics scoring",
         approach="Generates designs scored by physics, so it needs little experimental training data.",
         model="Pipeline + pharma partnership",
         funding="€60M Series A (Wendel, Bpifrance, Eurazeo)", funding_usd_m=65,
         deals="Sanofi up to $140M (Dec 2023; expanded Jul 2026)",
         evidence="Preclinical",
         threat="Low", x=3.6, y=6.8,
         why="Low-data pitch overlaps with SyntheMol's low-data antibiotic story.",
         src="https://www.fiercebiotech.com/biotech/sanofi-spins-ai-pact-inking-140m-deal-apply-aqemias-physics-algorithms-drug-discovery"),

    # ---------- Incumbent software ----------
    dict(name="Schrödinger", short="Schrödinger", tier="Incumbent software", hq="New York, NY (Nasdaq: SDGR)",
         product="LiveDesign, AutoDesigner, FEP+; de novo design workflows",
         approach="Physics-based scoring (FEP+) plus reaction-based enumeration and AI design.",
         model="Software licences (ACV) + collaborative/internal pipeline",
         funding="Public; FY2025 revenue $255.9M, software $199.5M (+10.6%)", funding_usd_m=None,
         deals="Many pharma site licences",
         evidence="Established standard in pharma comp-chem",
         threat="Medium", x=5, y=4,
         why="The default budget line a SyntheMol licence would have to displace. Prices are quote-only (not published). Overlaps with Jonathan's comp-chem slide.",
         src="https://www.biospace.com/press-releases/schrodinger-reports-fourth-quarter-and-full-year-2025-financial-results"),

    # ---------- Indirect / complementors ----------
    dict(name="Enamine REAL / Chemspace", short="Enamine REAL", tier="Indirect / complementor", hq="Kyiv, Ukraine / Riga",
         product="REAL Space (94.5B make-on-demand); xREAL (trillions) via Chemspace",
         approach="Enumerated space where every compound is made on demand, 3–4 weeks, >80% success.",
         model="Sells compounds and building blocks",
         funding="Private", funding_usd_m=None,
         deals="Exclusive BioSolveIT partnership (Dec 2023)",
         evidence="Industry-standard supplier",
         threat="Complementor", x=10, y=1,
         why="SyntheMol's chemical space and supplier. A partner, but also a dependency: Enamine or a partner could add generative search itself.",
         src="https://www.biosolveit.de/chemical-spaces/real-space/"),
    dict(name="BioSolveIT (infiniSee)", short="infiniSee", tier="Indirect / complementor", hq="Sankt Augustin, Germany",
         product="infiniSee chemical-space navigation, SeeSAR",
         approach="Searches billions of REAL compounds by similarity/pharmacophore in minutes.",
         model="Software licences",
         funding="Private", funding_usd_m=None,
         deals="Exclusive Enamine collaboration",
         evidence="Widely used",
         threat="Medium", x=9, y=1,
         why="A buyer can get 'synthesizable hits' by searching REAL instead of generating, so this is a substitute for simple use cases.",
         src="https://biosolveit.de/?p=10751"),
    dict(name="Retrosynthesis tools (SYNTHIA, Spaya, Molecule.one)", short="Retrosynthesis", tier="Indirect / complementor", hq="Various",
         product="SYNTHIA (Merck KGaA/MilliporeSigma), Spaya (Iktos), Molecule.one",
         approach="Post-hoc route planning for any designed molecule (SYNTHIA: 12M+ starting materials, 115K+ reaction rules).",
         model="SaaS, organisational pricing",
         funding="Molecule.one won $1M Standard Industries challenge (Dec 2025)", funding_usd_m=None,
         deals="Molecule.one–CAS; SYNTHIA–Dotmatics Luma",
         evidence="Mature",
         threat="Medium", x=8, y=1,
         why="Lets any generative tool bolt on synthesizability after the fact, weakening 'synthesizable by construction' as a sole differentiator.",
         src="https://molecule.one/blog/trustworthy-retrosynthesis-how-a-culture-of-chemist-ai-collaboration-won-1m-and-led-to-a-strategic-partnership-with-grace"),

    # ---------- Emerging / open / free ----------
    dict(name="Open-source synthesizable generators (SynFormer, RxnFlow, SynFlowNet, ReaSyn)", short="Open-source synth. models", tier="Emerging / open", hq="Academic (MIT, KAIST, Cambridge, etc.)",
         product="Research code",
         approach="Build molecules from building blocks and reaction templates, the same basic idea as SyntheMol, using transformers, diffusion or GFlowNets; the field grew rapidly from mid-2024.",
         model="Free", funding="Academic grants", funding_usd_m=None,
         deals="—", evidence="Benchmark papers; limited wet-lab validation",
         threat="High", x=9, y=0,
         why="The core idea is now common in academic work, much of it with public code. SyntheMol's own code is also public on GitHub/PyPI.",
         src="https://arxiv.org/pdf/2405.01155"),
    dict(name="NVIDIA BioNeMo (GenMol NIM)", short="NVIDIA GenMol", tier="Emerging / open", hq="Santa Clara, CA",
         product="GenMol v2 masked-diffusion generator as a hosted NIM microservice",
         approach="Fragment-based generation (SAFE), lead optimisation, scaffold hopping.",
         model="Free/cheap model access to drive GPU demand",
         funding="—", funding_usd_m=None,
         deals="NVentures invests across the field (Terray, Genesis, Iambic, Lila)",
         evidence="ICML 2025",
         threat="Medium", x=3, y=1,
         why="Pushes the price of generic generative models toward zero.",
         src="https://docs.api.nvidia.com/nim/reference/nvidia-genmol"),
    dict(name="AstraZeneca REINVENT 4", short="REINVENT 4", tier="Emerging / open", hq="Gothenburg, Sweden",
         product="Open-source RL SMILES generator",
         approach="RL-tuned generation; synthesizability via add-on scoring only.",
         model="Free (Apache-2.0)", funding="—", funding_usd_m=None,
         deals="—", evidence="Widely used in pharma",
         threat="Medium", x=3, y=0,
         why="Default free baseline inside pharma; buyers will ask 'why not REINVENT?'",
         src="https://arxiv.org/pdf/2505.08774"),
    dict(name="Boltz PBC (Boltz-2)", short="Boltz", tier="Emerging / open", hq="London, UK",
         product="Boltz-2 structure + affinity model (MIT licence)",
         approach="Near-FEP affinity estimates ~1,000x faster; usable as the scoring oracle for any generator.",
         model="Open models + enterprise services",
         funding="$28M seed (Jan 2026; a16z, Zetta, Amplify)", funding_usd_m=28,
         deals="Pfizer collaboration (Jan 2026)",
         evidence="Open benchmarks",
         threat="Low", x=2, y=2,
         why="Complement more than competitor: a free scoring model SyntheMol could plug in for target-based programs.",
         src="https://www.biopharmatrend.com/news/boltz-pbc-launches-with-28m-seed-round-pfizer-collaboration-and-three-guarantees-1455/"),
    dict(name="Lilly TuneLab", short="Lilly TuneLab", tier="Emerging / open", hq="Indianapolis, IN",
         product="18 ADMET/property models trained on >$1B of Lilly data, federated learning",
         approach="Property prediction, not generation.",
         model="Free to selected biotechs (Lilly gets model updates)",
         funding="—", funding_usd_m=None, deals="Circle Pharma, insitro among early users", evidence="Launched Sep 2025",
         threat="Low", x=1, y=2,
         why="Pharma is giving away models to capture data and deal flow, which lowers what start-ups can charge for predictions.",
         src="https://pharmaphorum.com/news/lilly-offers-ai-discovery-models-biotech-partners"),
    dict(name="Tamarind Bio", short="Tamarind", tier="Emerging / open", hq="San Francisco, CA",
         product="No-code hosting of 200+ protein and molecule models",
         approach="Runs open models (possibly including SyntheMol-type tools) without GPUs or code.",
         model="SaaS", funding="$13.6M Series A (Feb 2026; Dimension, YC)", funding_usd_m=14,
         deals="~100 orgs incl. 8 of top-20 pharma",
         evidence="—",
         threat="Medium", x=3, y=1,
         why="A distribution channel or a commoditiser: could host open SyntheMol and capture the user relationship.",
         src="https://www.biopharmatrend.com/news/tamarind-bio-raises-136m-to-run-200-ai-and-simulation-models-in-a-no-code-platform-for-bench-scientists-1505/"),
    dict(name="Lila Sciences", short="Lila", tier="Emerging / open", hq="Cambridge, MA (Flagship)",
         product="Autonomous 'AI science factories'",
         approach="AI + robotic labs running closed-loop experiments across chemistry and life sciences.",
         model="Platform + partnerships",
         funding="$550M total incl. $350M Series A; reported talks at $8.5B valuation", funding_usd_m=550,
         deals="NVIDIA backing",
         evidence="Early",
         threat="Low", x=7.2, y=6.5,
         why="Longer-term threat: closed-loop design-make-test at a scale no small player can match.",
         src="https://www.biopharmadive.com/news/lila-flagship-ai-superintelligence-startup-seed/742213/"),

    # ---------- Niche: AI antibiotics ----------
    dict(name="Phare Bio + Collins Lab (MIT/Wyss)", short="Phare Bio", tier="Niche: AI antibiotics", hq="Boston, MA (non-profit)",
         product="Generative AI antibiotic platform (TARGET project)",
         approach="Generative design of new antibiotic classes; building the first open-source AI antibiotic database.",
         model="Non-profit pipeline, pharma partnering (e.g. Basilea)",
         funding="Up to $27M ARPA-H; TED Audacious; Google.org", funding_usd_m=27,
         deals="Basilea",
         evidence="Generative antibiotics vs MRSA and N. gonorrhoeae (2025)",
         threat="High", x=5.6, y=7.4,
         why="Same therapeutic niche, same academic lineage (Stokes trained in the Collins lab), and grant-funded, so it can give data and models away.",
         src="https://arpa-h.gov/news-and-events/arpa-h-project-accelerate-discovery-and-development-new-antibiotics-using"),
]

# Chai Discovery, Converge Bio, Earendil, Latent Labs: generative BIOLOGICS, excluded (belong to Sophia's AI-drug-discovery slide).
EXCLUDED = [
    ("Chai Discovery", "Antibodies/biologics; $400M Series C Jul 2026 at $3.8B. Adjacent, not small-molecule gen chem."),
    ("Converge Bio", "Antibody/protein design; $25M Series A Jan 2026."),
    ("Earendil Labs", "AI biologics; $787M Mar 2026."),
]

PRICING = [
    ("Schrödinger licence", "Quote-only; not published. One third-party site estimates ~$10K per seat per year", "Third-party estimate (IntuitionLabs); Schrödinger site shows no prices", "Unverified"),
    ("Insilico Pharma.AI / Chemistry42", "Monthly or yearly plans (yearly 16% off); SaaS, on-prem, or 'discovery sprints'. One third-party site says from ~$3K per month", "Insilico site (plans); third-party (price)", "Price unverified"),
    ("Insilico software revenue", "$4.9M in FY2025 (9% of $56.2M revenue)", "FY2025 results", "Reported"),
    ("Schrödinger software revenue", "$199.5M in FY2025; software ACV $198M", "FY2025 results", "Reported"),
    ("Enamine REAL compound", "3–4 weeks, >80% success (Enamine). Cost: one forum estimate of ~$400–700 per compound including basic assays", "Enamine / BioSolveIT; PostEra forum post", "Cost unverified"),
    ("Pharma platform deal upfront", "$12M–$115M upfront; typically 2–5% of headline value", "Isomorphic, Insilico, XtalPi, PostEra, Genesis deals", "Reported"),
    ("Free alternatives", "REINVENT 4, SynFormer/RxnFlow, NVIDIA GenMol, Boltz-2, Lilly TuneLab: $0 for model access", "Public", "Reported"),
]

DEALS = [
    ("Insilico → Lilly", "2026", 115, 2750, "Generative small molecules"),
    ("XtalPi → DoveTree", "2025", 51, 5890, "AI + robotics, multi-TA"),
    ("Isomorphic → Lilly", "2024", 45, 1700, "Small molecules"),
    ("Isomorphic → Novartis", "2024", 37.5, 1200, "Small molecules"),
    ("Genesis → Incyte (expansion)", "2026", 80, 1160, "Plus $40M equity; headline = up to $232M/program × 5 targets"),
    ("PostEra → Pfizer", "2022", 13, 260, "AI Lab; expanded Jan 2025 with $12M more upfront"),
    ("Iktos → Servier", "2026", None, 1080, "€1B+ (≈$1.08B); upfront undisclosed"),
    ("Iambic → Takeda", "2026", None, 1700, "Milestones only; upfront undisclosed"),
    ("Aqemia → Sanofi", "2023", None, 140, "Upfront undisclosed"),
]
